IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID(N'dbo.VIM365RegHierarchyFile'))
	EXEC('CREATE PROCEDURE [dbo].[VIM365RegHierarchyFile] AS BEGIN SET NOCOUNT ON; END')
GO

ALTER PROCEDURE [dbo].[VIM365RegHierarchyFile]
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @365RegionCode varchar(2) = 'TS';

SELECT 
	@365RegionCode AS REGION,  
	HIERARCHY_REF AS REG_HIER_REF,
	HIER_FULL_NAME AS HIER_FULL_NAME,
	HIER_LEVEL AS HIER_LEVEL,
	HIER_PARENT AS HIER_PARERNT,
	HIER_LVL_ID AS HIER_LVL_ID
	FROM NATHIER_CLASS

END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

