//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegionalEventController.Controller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegionalEventController.Controller.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional Event Controller Error: Unhandled Exception in Icon Reference Processor.
        /// </summary>
        internal static string BuildingIconReferenceUnhandledExceptionEmailSubject {
            get {
                return ResourceManager.GetString("BuildingIconReferenceUnhandledExceptionEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred in the Icon Reference Processor..
        /// </summary>
        internal static string BuildingIconReferenceUnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("BuildingIconReferenceUnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional Controller Error: Events with exceptions occurred.
        /// </summary>
        internal static string EmailSubjectFailedEvents {
            get {
                return ResourceManager.GetString("EmailSubjectFailedEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional Controller Error: Unable to run Prepare Regional Controller.
        /// </summary>
        internal static string EmailSubjectRunPrepareRegionalControllerError {
            get {
                return ResourceManager.GetString("EmailSubjectRunPrepareRegionalControllerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional Controller Error: Unable to run Regional Controller.
        /// </summary>
        internal static string EmailSubjectRunRegionalControllerError {
            get {
                return ResourceManager.GetString("EmailSubjectRunRegionalControllerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following events had exceptions during processing and may be failed to process: {0}.
        /// </summary>
        internal static string ErrorFailedEvents {
            get {
                return ResourceManager.GetString("ErrorFailedEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to run Prepare Regional Controller. {0}.
        /// </summary>
        internal static string ErrorFailedToRunPrepareRegionalController {
            get {
                return ResourceManager.GetString("ErrorFailedToRunPrepareRegionalController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to run Regional Controller for {0} region. {1}.
        /// </summary>
        internal static string ErrorFailedToRunRegionalController {
            get {
                return ResourceManager.GetString("ErrorFailedToRunRegionalController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional Event Controller Error: Unhandled Exception in New Item Processor.
        /// </summary>
        internal static string ProcessingNewItemUnhandledExceptionEmailSubject {
            get {
                return ResourceManager.GetString("ProcessingNewItemUnhandledExceptionEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred in the New Item Processor in the {0} region. {1}.
        /// </summary>
        internal static string ProcessingNewItemUnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("ProcessingNewItemUnhandledExceptionMessage", resourceCulture);
            }
        }
    }
}
