
CREATE TYPE [app].[IrmaPushType] AS TABLE(
	[RegionCode] [varchar](4) NOT NULL,
	[BusinessUnitId] [int] NOT NULL,
	[Identifier] [varchar](13) NOT NULL,
	[ChangeType] [varchar](30) NOT NULL,
	[InsertDate] [datetime2](7) NOT NULL,
	[RetailSize] [decimal](9,4) NOT NULL,
	[RetailPackageUom] [varchar](5) NOT NULL,
	[TmDiscountEligible] [bit] NOT NULL,
	[CaseDiscount] [bit] NOT NULL,
	[AgeCode] [int] NULL,
	[Recall] [bit] NOT NULL,
	[RestrictedHours] [bit] NOT NULL,
	[SoldByWeight] [bit] NOT NULL,
	[ScaleForcedTare] [bit] NOT NULL,
	[QuantityRequired] [bit] NOT NULL,
	[PriceRequired] [bit] NOT NULL,
	[QuantityProhibit] [bit] NOT NULL,
	[VisualVerify] [bit] NOT NULL,
	[RestrictSale] [bit] NOT NULL,
	[PosScaleTare] [int] NULL,
	[LinkedIdentifier] [varchar](13) NULL,
	[Price] [money] NULL,
	[RetailUom] [varchar](5) NOT NULL,
	[Multiple] [int] NULL,
	[SaleMultiple] [int] NULL,
	[SalePrice] [money] NULL,
	[SaleStartDate] [smalldatetime] NULL,
	[SaleEndDate] [smalldatetime] NULL,
	[InProcessBy] [varchar](30) NULL,
	[InUdmDate] [datetime2](7) NULL,
	[EsbReadyDate] [datetime2](7) NULL,
	[UdmFailedDate] [datetime2](7) NULL,
	[EsbReadyFailedDate] [datetime2](7) NULL
)
GO
