CREATE TYPE [app].[ItemImportType] AS TABLE(
	[ScanCode] [nvarchar](13) NOT NULL,
	[Product Description] [nvarchar](255) NOT NULL,
	[POS Description] [nvarchar](255) NOT NULL,
	[Package Unit] [nvarchar](255) NOT NULL,
	[Food Stamp Eligible] [nvarchar](255) NOT NULL,
	[POS Scale Tare] [nvarchar](255) NOT NULL,
	[Retail Size] [nvarchar](10) NULL,
	[Retail Uom] [nvarchar](15) NULL,
	[Delivery System] [nvarchar](15) NULL,
	[Brand ID] [nvarchar](9) NOT NULL,
	[Browsing Hierarchy ID] [nvarchar](9) NULL,
	[Merchandise Hierarchy ID] [nvarchar](9) NULL,
	[Tax Class ID] [nvarchar](9) NULL,
	[IsValidated] [nvarchar](1) NOT NULL,
	[DepartmentSale] [nvarchar](1) NULL,
	[HiddenItem] [nvarchar](1) NULL,
	[National Hierarchy ID] [nvarchar](9) NULL,
	[Notes] [nvarchar](255) NULL,
	[AnimalWelfareRatingId] [nvarchar](3) NULL,
	[Biodynamic] [nvarchar](1) NULL,
	[CheeseMilkTypeId] [nvarchar](3) NULL,
	[CheeseRaw] [nvarchar](1) NULL,
	[EcoScaleRatingId] [nvarchar](3) NULL,
	[GlutenFreeAgencyId] [nvarchar](9) NULL,
	[KosherAgencyId] [nvarchar](9) NULL,
	[Msc] [nvarchar](1) NULL,
	[NonGmoAgencyId] [nvarchar](9) NULL,
	[OrganicAgencyId] [nvarchar](9) NULL,
	[PremiumBodyCare] [nvarchar](1) NULL,
	[SeafoodFreshOrFrozenId] [nvarchar](3) NULL,
	[SeafoodCatchTypeId] [nvarchar](3) NULL,
	[VeganAgencyId] [nvarchar](9) NULL,
	[Vegetarian] [nvarchar](1) NULL,
	[WholeTrade] [nvarchar](1) NULL,
	[GrassFed] [nvarchar](1) NULL,
	[PastureRaised] [nvarchar](1) NULL,
	[FreeRange] [nvarchar](1) NULL,
	[DryAged] [nvarchar](1) NULL,
	[AirChilled] [nvarchar](1) NULL,
	[MadeInHouse] [nvarchar](1) NULL,
	[AlcoholByVolume] [nvarchar](255) NULL,
	[CaseinFree] [nvarchar](1) NULL,
	[DrainedWeight] [nvarchar](255) NULL,
	[DrainedWeightUom] [nvarchar](255) NULL,
	[FairTradeCertified] [nvarchar](255) NULL,
	[Hemp] [nvarchar](1) NULL,
	[LocalLoanProducer] [nvarchar](1) NULL,
	[MainProductName] [nvarchar](255) NULL,
	[NutritionRequired] [nvarchar](1) NULL,
	[OrganicPersonalCare] [nvarchar](1) NULL,
	[Paleo] [nvarchar](1) NULL,
	[ProductFlavorType] [nvarchar](255) NULL
)