CREATE TYPE [app].[ItemAddType] AS TABLE(
	[ScanCode] [nvarchar](13) NOT NULL,
	[ProductDescription] [nvarchar](255) NOT NULL,
	[PosDescription] [nvarchar](255) NOT NULL,
	[PackageUnit] [nvarchar](255) NOT NULL,
	[FoodStampEligible] [nvarchar](255) NOT NULL,
	[PosScaleTare] [nvarchar](255) NOT NULL,
	[RetailSize] [nvarchar](10) NOT NULL,
	[RetailUom] [nvarchar](15) NOT NULL,
	[DeliverySystem] [nvarchar](15) NULL,
	[BrandId] [nvarchar](9) NOT NULL,
	[BrandName] [nvarchar](255) NOT NULL,
	[MerchandiseId] [nvarchar](9) NOT NULL,
	[TaxId] [nvarchar](9) NOT NULL,
	[NationalClassId] [nvarchar](9) NOT NULL,
	[BrowsingId] [nvarchar](9) NOT NULL,
	[IsValidated] [nvarchar](1) NOT NULL,
	[AnimalWelfareRatingId] [nvarchar](3) NULL,
	[Biodynamic] [nvarchar](1) NULL,
	[CheeseMilkTypeId] [nvarchar](3) NULL,
	[CheeseRaw] [nvarchar](1) NULL,
	[EcoScaleRatingId] [nvarchar](3) NULL,
	[GlutenFreeAgencyId] [nvarchar](9) NULL,
	[KosherAgencyId] [nvarchar](9) NULL,
	[Msc] [nvarchar](1) NULL,
	[NonGmoAgencyId] [nvarchar](9) NULL,
	[OrganicAgencyId] [nvarchar](9) NULL,
	[PremiumBodyCare] [nvarchar](1) NULL,
	[SeafoodFreshOrFrozenId] [nvarchar](3) NULL,
	[SeafoodCatchTypeId] [nvarchar](3) NULL,
	[VeganAgencyId] [nvarchar](9) NULL,
	[Vegetarian] [nvarchar](1) NULL,
	[WholeTrade] [nvarchar](1) NULL,
	[GrassFed] [nvarchar](1) NULL,
	[PastureRaised] [nvarchar](1) NULL,
	[FreeRange] [nvarchar](1) NULL,
	[DryAged] [nvarchar](1) NULL,
	[AirChilled] [nvarchar](1) NULL,
	[MadeInHouse] [nvarchar](1) NULL,
	[AlcoholByVolume] [nvarchar](255) NULL,
	[CaseinFree] [nvarchar](1) NULL,
	[DrainedWeight] [nvarchar](255) NULL,
	[DrainedWeightUom] [nvarchar](255) NULL,
	[FairTradeCertified] [nvarchar](255) NULL,
	[Hemp] [nvarchar](1) NULL,
	[LocalLoanProducer] [nvarchar](1) NULL,
	[MainProductName] [nvarchar](255) NULL,
	[NutritionRequired] [nvarchar](1) NULL,
	[OrganicPersonalCare] [nvarchar](1) NULL,
	[Paleo] [nvarchar](1) NULL,
	[ProductFlavorType] [nvarchar](255) NULL
)
GO
