CREATE TYPE app.PriceMessageType AS TABLE 
(
    [MessageTypeId]         INT            NOT NULL,
    [MessageStatusId]       INT            NOT NULL,
    [MessageHistoryId]      INT            NULL,
    [IRMAPushID]            INT            NOT NULL,
    [InsertDate]            DATETIME2 (7)  DEFAULT (sysdatetime()) NOT NULL,
    [RegionCode]            NVARCHAR (4)   NOT NULL,
    [BusinessUnit_ID]       INT            NOT NULL,
    [ItemId]                INT            NOT NULL,
    [ItemTypeCode]          NVARCHAR (3)   NOT NULL,
    [ItemTypeDesc]          NVARCHAR (255) NOT NULL,
    [LocaleId]              INT            NOT NULL,
    [LocaleName]            NVARCHAR (255) NOT NULL,
    [ScanCodeId]            INT            NOT NULL,
    [ScanCode]              NVARCHAR (13)  NOT NULL,
    [ScanCodeTypeId]        INT            NOT NULL,
    [ScanCodeTypeDesc]      NVARCHAR (255) NOT NULL,
    [ChangeType]            NVARCHAR (32)  NOT NULL,
    [UomCode]               NVARCHAR (3)   NOT NULL,
    [UomName]               NVARCHAR (100) NULL,
    [CurrencyCode]          NVARCHAR (3)   NOT NULL,
    [Price]                 MONEY          NULL,
    [Multiple]              INT            NULL,
    [SalePrice]             MONEY          NULL,
    [SaleMultiple]          INT            NULL,
    [SaleStartDate]         DATETIME2 (7)  NULL,
    [SaleEndDate]           DATETIME2 (7)  NULL,
    [PreviousSalePrice]     MONEY          NULL,
    [PreviousSaleMultiple]  INT            NULL,
    [PreviousSaleStartDate] DATETIME2 (7)  NULL,
    [PreviousSaleEndDate]   DATETIME2 (7)  NULL,
    [InProcessBy]           INT            NULL,
    [ProcessedDate]         DATETIME2 (7)  NULL
)
GO