//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class County
    {
        public County()
        {
            this.PostalCode = new HashSet<PostalCode>();
            this.City = new HashSet<City>();
        }
    
        public int countyID { get; set; }
        public string countyName { get; set; }
        public int territoryID { get; set; }
    
        public virtual ICollection<PostalCode> PostalCode { get; set; }
        public virtual Territory Territory { get; set; }
        public virtual ICollection<City> City { get; set; }
    }
}
