//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverySystem
    {
        public int DeliverySystemID { get; set; }
        public string DeliverySystemCode { get; set; }
        public string DeliverySystemName { get; set; }
    }
}
