//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hierarchy
    {
        public Hierarchy()
        {
            this.HierarchyClass = new HashSet<HierarchyClass>();
            this.HierarchyPrototype = new HashSet<HierarchyPrototype>();
        }
    
        public int hierarchyID { get; set; }
        public string hierarchyName { get; set; }
    
        public virtual ICollection<HierarchyClass> HierarchyClass { get; set; }
        public virtual ICollection<HierarchyPrototype> HierarchyPrototype { get; set; }
    }
}
