//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HierarchyPrototype
    {
        public HierarchyPrototype()
        {
            this.HierarchyClass = new HashSet<HierarchyClass>();
        }
    
        public int hierarchyID { get; set; }
        public int hierarchyLevel { get; set; }
        public string hierarchyLevelName { get; set; }
        public Nullable<bool> itemsAttached { get; set; }
    
        public virtual Hierarchy Hierarchy { get; set; }
        public virtual ICollection<HierarchyClass> HierarchyClass { get; set; }
    }
}
