//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRMAItemSubscription
    {
        public int IRMAItemSubscriptionID { get; set; }
        public string regioncode { get; set; }
        public string identifier { get; set; }
        public System.DateTime insertDate { get; set; }
        public Nullable<System.DateTime> deleteDate { get; set; }
    }
}
