//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPriceType
    {
        public ItemPriceType()
        {
            this.ItemPrice = new HashSet<ItemPrice>();
        }
    
        public int itemPriceTypeID { get; set; }
        public string itemPriceTypeCode { get; set; }
        public string itemPriceTypeDesc { get; set; }
    
        public virtual ICollection<ItemPrice> ItemPrice { get; set; }
    }
}
