//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMovement
    {
        public int ItemMovementID { get; set; }
        public string ESBMessageID { get; set; }
        public int BusinessUnitID { get; set; }
        public int RegisterNumber { get; set; }
        public int TransactionSequenceNumber { get; set; }
        public int LineItemNumber { get; set; }
        public string Identifier { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> ItemVoid { get; set; }
        public int ItemType { get; set; }
        public decimal BasePrice { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> MarkDownAmount { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InProcessBy { get; set; }
        public Nullable<System.DateTime> ProcessFailedDate { get; set; }
    }
}
