//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ScanCode = new HashSet<ScanCode>();
            this.ItemHierarchyClass = new HashSet<ItemHierarchyClass>();
            this.ItemTrait = new HashSet<ItemTrait>();
            this.ItemPrice = new HashSet<ItemPrice>();
            this.ItemSignAttribute = new HashSet<ItemSignAttribute>();
            this.ItemLink = new HashSet<ItemLink>();
            this.ItemLink1 = new HashSet<ItemLink>();
        }
    
        public int itemID { get; set; }
        public int itemTypeID { get; set; }
        public int productKey { get; set; }
    
        public virtual ICollection<ScanCode> ScanCode { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual ICollection<ItemHierarchyClass> ItemHierarchyClass { get; set; }
        public virtual PLUMap PLUMap { get; set; }
        public virtual ICollection<ItemTrait> ItemTrait { get; set; }
        public virtual ICollection<ItemPrice> ItemPrice { get; set; }
        public virtual ICollection<ItemSignAttribute> ItemSignAttribute { get; set; }
        public virtual ICollection<ItemLink> ItemLink { get; set; }
        public virtual ICollection<ItemLink> ItemLink1 { get; set; }
    }
}
