//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageStatus
    {
        public MessageStatus()
        {
            this.MessageQueueHierarchy = new HashSet<MessageQueueHierarchy>();
            this.MessageQueueItemLocale = new HashSet<MessageQueueItemLocale>();
            this.MessageQueuePrice = new HashSet<MessageQueuePrice>();
            this.MessageQueueProductSelectionGroup = new HashSet<MessageQueueProductSelectionGroup>();
            this.MessageHistory = new HashSet<MessageHistory>();
            this.MessageQueueLocale = new HashSet<MessageQueueLocale>();
            this.MessageQueueProduct = new HashSet<MessageQueueProduct>();
        }
    
        public int MessageStatusId { get; set; }
        public string MessageStatusName { get; set; }
    
        public virtual ICollection<MessageQueueHierarchy> MessageQueueHierarchy { get; set; }
        public virtual ICollection<MessageQueueItemLocale> MessageQueueItemLocale { get; set; }
        public virtual ICollection<MessageQueuePrice> MessageQueuePrice { get; set; }
        public virtual ICollection<MessageQueueProductSelectionGroup> MessageQueueProductSelectionGroup { get; set; }
        public virtual ICollection<MessageHistory> MessageHistory { get; set; }
        public virtual ICollection<MessageQueueLocale> MessageQueueLocale { get; set; }
        public virtual ICollection<MessageQueueProduct> MessageQueueProduct { get; set; }
    }
}
