//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageQueueItemLocale
    {
        public int MessageQueueId { get; set; }
        public int MessageTypeId { get; set; }
        public int MessageStatusId { get; set; }
        public Nullable<int> MessageHistoryId { get; set; }
        public int MessageActionId { get; set; }
        public int IRMAPushID { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string RegionCode { get; set; }
        public int BusinessUnit_ID { get; set; }
        public int ItemId { get; set; }
        public string ItemTypeCode { get; set; }
        public string ItemTypeDesc { get; set; }
        public int LocaleId { get; set; }
        public string LocaleName { get; set; }
        public int ScanCodeId { get; set; }
        public string ScanCode { get; set; }
        public int ScanCodeTypeId { get; set; }
        public string ScanCodeTypeDesc { get; set; }
        public string ChangeType { get; set; }
        public bool LockedForSale { get; set; }
        public bool Recall { get; set; }
        public bool TMDiscountEligible { get; set; }
        public bool Case_Discount { get; set; }
        public Nullable<int> AgeCode { get; set; }
        public bool Restricted_Hours { get; set; }
        public bool Sold_By_Weight { get; set; }
        public bool ScaleForcedTare { get; set; }
        public bool Quantity_Required { get; set; }
        public bool Price_Required { get; set; }
        public bool QtyProhibit { get; set; }
        public bool VisualVerify { get; set; }
        public string LinkedItemScanCode { get; set; }
        public Nullable<int> PosScaleTare { get; set; }
        public Nullable<int> InProcessBy { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public string PreviousLinkedItemScanCode { get; set; }
        public Nullable<int> IrmaItemKey { get; set; }
        public Nullable<bool> DefaultScanCode { get; set; }
    
        public virtual MessageAction MessageAction { get; set; }
        public virtual MessageHistory MessageHistory { get; set; }
        public virtual MessageStatus MessageStatus { get; set; }
        public virtual MessageType MessageType { get; set; }
        public virtual IRMAPush IRMAPush { get; set; }
    }
}
