//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageQueueItem
    {
        public long MessageQueueItemId { get; set; }
        public System.DateTime EsbReadyDateTimeUtc { get; set; }
        public int ItemId { get; set; }
        public System.DateTime InsertDateUtc { get; set; }
    }
}
