//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLURequestChangeType
    {
        public PLURequestChangeType()
        {
            this.PLURequestChangeHistory = new HashSet<PLURequestChangeHistory>();
        }
    
        public int pluRequestChangeTypeID { get; set; }
        public string ChangeTypeDescription { get; set; }
    
        public virtual ICollection<PLURequestChangeHistory> PLURequestChangeHistory { get; set; }
    }
}
