//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSelectionGroupType
    {
        public ProductSelectionGroupType()
        {
            this.ProductSelectionGroup = new HashSet<ProductSelectionGroup>();
            this.MessageQueueProductSelectionGroup = new HashSet<MessageQueueProductSelectionGroup>();
        }
    
        public int ProductSelectionGroupTypeId { get; set; }
        public string ProductSelectionGroupTypeName { get; set; }
    
        public virtual ICollection<ProductSelectionGroup> ProductSelectionGroup { get; set; }
        public virtual ICollection<MessageQueueProductSelectionGroup> MessageQueueProductSelectionGroup { get; set; }
    }
}
