//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionalSettings
    {
        public int RegionalSettingsId { get; set; }
        public int RegionId { get; set; }
        public int SettingsId { get; set; }
        public bool Value { get; set; }
    
        public virtual Regions Regions { get; set; }
        public virtual Settings Settings { get; set; }
    }
}
