//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanCode
    {
        public ScanCode()
        {
            this.Mapping = new HashSet<Mapping>();
            this.Agency = new HashSet<Agency>();
        }
    
        public int scanCodeID { get; set; }
        public int itemID { get; set; }
        public string scanCode { get; set; }
        public int scanCodeTypeID { get; set; }
        public Nullable<int> localeID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ScanCodeType ScanCodeType { get; set; }
        public virtual Locale Locale { get; set; }
        public virtual ICollection<Mapping> Mapping { get; set; }
        public virtual ICollection<Agency> Agency { get; set; }
    }
}
