//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Territory
    {
        public Territory()
        {
            this.County = new HashSet<County>();
            this.PhysicalAddress = new HashSet<PhysicalAddress>();
            this.City = new HashSet<City>();
        }
    
        public int territoryID { get; set; }
        public string territoryCode { get; set; }
        public string territoryName { get; set; }
        public int countryID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<County> County { get; set; }
        public virtual ICollection<PhysicalAddress> PhysicalAddress { get; set; }
        public virtual ICollection<City> City { get; set; }
    }
}
