//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timezone
    {
        public Timezone()
        {
            this.PhysicalAddress = new HashSet<PhysicalAddress>();
        }
    
        public int timezoneID { get; set; }
        public string timezoneCode { get; set; }
        public string timezoneName { get; set; }
        public Nullable<int> gmtOffset { get; set; }
        public Nullable<System.DateTime> dstStart { get; set; }
        public Nullable<System.DateTime> dstEnd { get; set; }
        public string posTimeZoneName { get; set; }
    
        public virtual ICollection<PhysicalAddress> PhysicalAddress { get; set; }
    }
}
