//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icon.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class VimEventQueue
    {
        public int QueueId { get; set; }
        public int EventTypeId { get; set; }
        public int EventReferenceId { get; set; }
        public string EventMessage { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> ProcessedFailedDate { get; set; }
        public Nullable<int> InProcessBy { get; set; }
        public Nullable<int> NumberOfRetry { get; set; }
    
        public virtual VimEventType VimEventType { get; set; }
    }
}
