GRANT SELECT ON ItemVendor  TO TibcoDataWriter
GRANT SELECT ON USERS  TO TibcoDataWriter
GRANT SELECT ON SubTeam  TO TibcoDataWriter
GRANT SELECT ON amz.EVENTTYPE  TO TibcoDataWriter
GRANT SELECT ON OrderItem  TO TibcoDataWriter
GRANT SELECT ON Vendor  TO TibcoDataWriter
GRANT SELECT ON OrderHeader  TO TibcoDataWriter
GRANT SELECT ON AppConfigApp  TO TibcoDataWriter
GRANT SELECT ON Version  TO TibcoDataWriter
GRANT SELECT ON AppConfigEnv  TO TibcoDataWriter
GRANT SELECT ON AppConfigApp  TO TibcoDataWriter
GRANT INSERT,Update,SELECT ON amz.MessageArchive  TO TibcoDataWriter
GRANT SELECT,UPDATE ON amz.ReceiptQueue TO TibcoDataWriter