'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Item_ItemStatusList
    
    '''<summary>
    '''Add_Identifier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Add_Identifier As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Organic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Organic As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''cbListVendorItemStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbListVendorItemStatus As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''Default_Identifier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Default_Identifier As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Pre_Order control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_Order As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Deleted_Identifier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Deleted_Identifier As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Recall_Flag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Recall_Flag As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Discontinue_Item control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Discontinue_Item As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Refrigerated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Refrigerated As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''EXEDistributed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EXEDistributed As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Remove_Identifier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Remove_Identifier As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Full_Pallet_Only control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Full_Pallet_Only As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Retail_Sale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Retail_Sale As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Keep_Frozen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Keep_Frozen As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Scale_Identifier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Scale_Identifier As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''LockAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LockAuth As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Shipper_Item control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Shipper_Item As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''National_Identifier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents National_Identifier As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''HFM_Item control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFM_Item As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''NoDistMarkup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoDistMarkup As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''WFM_Item control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WFM_Item As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Not_Available control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Not_Available As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''btnClearForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClearForm As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmbReportFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbReportFormat As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport As Global.System.Web.UI.WebControls.Button
End Class
