BULK INSERT [IconRebootData] 
   FROM '\\irmadevfile\IRMA\\infor_im_dataDictionary_DRAFT.txt'  
   WITH (
     FIELDTERMINATOR = '\t',
      ROWTERMINATOR = '\n'

);
GO


DELETE [IconRebootData] where name ='Name'

DELETE [IconRebootData] where name

NOT IN (
'Validated',
'Food Stamp Eligible',
'Item Pack',
'POS Scale Tare',
'Prohibit Discount',
'Item Status',
'Product Description',
'POS Description',
'Retail Size',
'UOM',
'Notes',
'Vegetarian',
'Whole Trade',
'Premium Body Care',
'Raw',
'Biodynamic',
'Free Range',
'Made In House',
'Pasture Raised',
'Grass Fed',
'MSC',
'Air Chilled',
'Dry Aged',
'Customer Friendly Description',
'dadlkj',
'EStore Eligible',
'EStore Nutrition Required',
'WFM Eligible',
'GMO Transparency',
'Ownership (Brand Level)',
'Nutrition Required',
'Manufacturer',
'Data Source',
'Organic',
'IX One Brand',
'Labeling',
'Non-GMO',
'Shelf Life',
'Category Management',
'Sold Hot or Cold',
'Kosher Claim',
'Organic Claim',
'SCO Item Tare Group',
'Non GMO Claim',
'Animal Welfare Rating',
'Alcohol By Volume',
'ABF',
'Gluten Free',
'Age/Gender',
'Refrigerated or Shelf Stable',
'Private Label',
'Gluten Free Claim',
'Delivery System',
'Local Loan Producer',
'Country of Origin',
'Global Pricing Program',
'Vegan',
'Fresh or Frozen',
'Packaging Type',
'PMD Verified',
'Flex Sign Text',
'Vegan Claim',
'Beer Style',
'Cheese Attribute: Milk Type',
'Fair Trade Claim',
'Seafood: Wild Or Farm Raised',
'Image Map',
'Juice Content',
'Homeopathic',
'Organic Personal Care',
'Casein Free',
'Hemp',
'Fair Trade Certified',
'Eco-Scale Rating',
'Halal',
'Appellation',
'Travel Size/Single Use/Kit',
'Varietal',
'Rainforest Alliance',
'Drained Weight UOM',
'Natural Claim',
'Drained Weight',
'Paleo Claim',
'Vegetarian Claim',
'Rennet',
'Blackhawk Commission Percent',
'Exclusive (Yes/No)',
'Paleo',
'Regional Local Item',
'Made with Organic Grapes',
'Low Fat Claim',
'Blackhawk Commission Dollar',
'Seasonal In and Out/Gifting',
'Pct Tare Weight',
'365 Eligible',
'No Sulfites',
'Prime',
'Smoked',
'Fat Free Claim',
'Product Flavor or Type',
'Smithsonian Bird Friendly',
'Prime Now Eligible',
'Exclusive (Date)',
'Disposable',
'Accessory',
'Allocated',
'Multipurpose',
'Line',
'Line Extension',
'Hormone Free Claim',
'Kosher',
'Fragrance Free',
'Good Better Best',
'Price Line',
'Other 3P Eligible',
'Skin Type',
'SKU',
'Value Added',
'Variant Size')


