IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID(N'dbo.VIM365RegionalDepartmentFile'))
	EXEC('CREATE PROCEDURE [dbo].[VIM365RegionalDepartmentFile] AS BEGIN SET NOCOUNT ON; END')
GO

ALTER PROCEDURE [dbo].[VIM365RegionalDepartmentFile]
AS
BEGIN

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @365RegionCode varchar(2) = 'TS';

SELECT
	@365RegionCode AS REGION,
	SubTeam.Dept_No AS POS_DEPT,
	SubTeam_Name AS DEPT_NAME
FROM SubTeam (NOLOCK)



END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO


