'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace pp_irma

    Partial Public Class promoorders1

        '''<summary>
        '''Store_Nos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Store_Nos As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''dept control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dept As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''orddates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents orddates As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''getOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents getOrders As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
