CREATE TABLE [dbo].[BarcodeType] (
	 [BarcodeTypeId] INT IDENTITY(1, 1) NOT NULL
	,[BarcodeType] NVARCHAR(255) NOT NULL
	,[BeginRange] NVARCHAR(11) NULL
	,[EndRange] NVARCHAR(11)  NULL
	,CONSTRAINT [BarcodeType_PK] PRIMARY KEY CLUSTERED ([BarcodeTypeId] ASC)	
	WITH (
		PAD_INDEX = OFF
		,STATISTICS_NORECOMPUTE = OFF
		,IGNORE_DUP_KEY = OFF
		,ALLOW_ROW_LOCKS = ON
		,ALLOW_PAGE_LOCKS = ON
		,FILLFACTOR = 80
		) ON [PRIMARY]
		,[ScalePLU] BIT NOT NULL DEFAULT 0
	) ON [PRIMARY]
GO