CREATE TABLE [dbo].[Conv_UserLoader] (
    [RegionCode]                 CHAR (5)       NULL,
    [UserName]                   VARCHAR (25)   NOT NULL,
    [FullName]                   VARCHAR (50)   NULL,
    [accountenabled]             BIT            NOT NULL,
    [SuperUser]                  BIT            DEFAULT ((0)) NOT NULL,
    [SPE]                        BIT            DEFAULT ((0)) NOT NULL,
    [PO_Accountant]              BIT            DEFAULT ((0)) NOT NULL,
    [Accountant]                 BIT            DEFAULT ((0)) NOT NULL,
    [Distributor]                BIT            DEFAULT ((0)) NOT NULL,
    [Credit_Buyer]               BIT            DEFAULT ((0)) NOT NULL,
    [Frequent_Shopper]           BIT            DEFAULT ((0)) NOT NULL,
    [Coordinator]                BIT            DEFAULT ((0)) NOT NULL,
    [Item_Administrator]         BIT            DEFAULT ((0)) NOT NULL,
    [Availability_Administrator] BIT            DEFAULT ((0)) NOT NULL,
    [Vendor_Administrator]       BIT            DEFAULT ((0)) NOT NULL,
    [Lock_Administrator]         BIT            DEFAULT ((0)) NOT NULL,
    [Delete_Access]              BIT            DEFAULT ((0)) NOT NULL,
    [Warehouse]                  BIT            DEFAULT ((0)) NOT NULL,
    [Non_PO_Administrator]       BIT            DEFAULT ((0)) NOT NULL,
    [PriceBatchProcessor]        BIT            DEFAULT ((0)) NOT NULL,
    [Inventory_Administrator]    BIT            DEFAULT ((0)) NOT NULL,
    [BatchBuildOnly]             BIT            DEFAULT ((0)) NOT NULL,
    [UserAdmin]                  BIT            NULL,
    [ItemRequest]                BIT            NULL,
    [VendorRequest]              BIT            NULL,
    [IRMAPush]                   BIT            NULL,
    [StoreSpecials]              BIT            NULL,
    [RetailCost]                 BIT            NULL,
    [Authorizations]             BIT            NULL,
    [WebQuery]                   BIT            NULL,
    [ScaleInfo]                  BIT            DEFAULT ((0)) NOT NULL,
    [storelist]                  VARCHAR (200)  NULL,
    [subteamlist]                VARCHAR (8000) NULL
);

