CREATE TABLE [dbo].[cxspricd] (
    [upcno]        CHAR (13)      NULL,
    [pzone]        SMALLINT       NULL,
    [dept]         CHAR (4)       NULL,
    [store]        SMALLINT       NULL,
    [effpm]        SMALLINT       NULL,
    [effprice]     NUMERIC (6, 2) NULL,
    [ptype]        CHAR (3)       NULL,
    [holdpm]       SMALLINT       NULL,
    [holdprice]    NUMERIC (6, 2) NULL,
    [efflock]      CHAR (1)       NULL,
    [senslevel]    SMALLINT       NULL,
    [enabalt]      CHAR (1)       NULL,
    [altpm]        SMALLINT       NULL,
    [altprice]     NUMERIC (6, 2) NULL,
    [backorder]    SMALLINT       NULL,
    [target_gm]    NUMERIC (5, 2) NULL,
    [aisleloc]     CHAR (6)       NULL,
    [invonhand]    INT            NULL,
    [ordtrig]      SMALLINT       NULL,
    [saletrig]     INT            NULL,
    [qtyord]       INT            NULL,
    [reordqty]     INT            NULL,
    [qtyrecvd]     INT            NULL,
    [mixmatch]     SMALLINT       NULL,
    [reptcode]     CHAR (2)       NULL,
    [activeflag]   CHAR (1)       NULL,
    [tax1]         CHAR (1)       NULL,
    [tax2]         CHAR (1)       NULL,
    [tax3]         CHAR (1)       NULL,
    [foodstamp]    CHAR (1)       NULL,
    [tradestamp]   CHAR (1)       NULL,
    [qtyreq]       CHAR (1)       NULL,
    [qtyprob]      CHAR (1)       NULL,
    [visual]       CHAR (1)       NULL,
    [coupon]       CHAR (1)       NULL,
    [restricted]   CHAR (1)       NULL,
    [scale]        CHAR (1)       NULL,
    [tare]         SMALLINT       NULL,
    [replink]      CHAR (1)       NULL,
    [levreorder]   CHAR (1)       NULL,
    [shlffactor]   NUMERIC (6, 3) NULL,
    [shlfctqty]    SMALLINT       NULL,
    [linkdept]     CHAR (4)       NULL,
    [sioverride]   CHAR (1)       NULL,
    [link_price]   NUMERIC (4, 2) NULL,
    [bundmixmatch] CHAR (1)       NULL,
    [rescode]      CHAR (2)       NULL,
    [datacap]      CHAR (1)       NULL,
    [itemdisc]     CHAR (1)       NULL,
    [panelist]     CHAR (1)       NULL,
    [lqdflag]      CHAR (1)       NULL,
    [coupmult]     CHAR (1)       NULL,
    [bonus]        SMALLINT       NULL,
    [linkcode]     CHAR (13)      NULL,
    [discntamt]    NUMERIC (6, 2) NULL,
    [frbuyer]      CHAR (1)       NULL,
    [audaction1]   CHAR (1)       NULL,
    [audaction2]   CHAR (1)       NULL,
    [audaction3]   CHAR (1)       NULL,
    [prsdisc1]     CHAR (1)       NULL,
    [prsdisc2]     CHAR (1)       NULL,
    [prsdisc3]     CHAR (1)       NULL,
    [lastprice]    NUMERIC (6, 2) NULL,
    [lastpm]       SMALLINT       NULL,
    [lastdate]     SMALLDATETIME  NULL,
    [tax4]         CHAR (1)       NULL,
    [userflag1]    CHAR (1)       NULL,
    [userflag2]    CHAR (1)       NULL,
    [userflag3]    CHAR (1)       NULL,
    [userflag4]    CHAR (1)       NULL,
    [aditem]       CHAR (1)       NULL,
    [prohsale]     CHAR (1)       NULL,
    [miscint1]     INT            NULL,
    [miscint2]     INT            NULL,
    [deprec]       CHAR (1)       NULL,
    [refrec]       CHAR (1)       NULL,
    [depretrec]    CHAR (1)       NULL,
    [miscreprec]   CHAR (1)       NULL,
    [miscporec]    CHAR (1)       NULL,
    [mfgcouprec]   CHAR (1)       NULL,
    [pricereq]     CHAR (1)       NULL,
    [keepmovt]     CHAR (1)       NULL,
    [coupmultall]  CHAR (1)       NULL,
    [shelflabel]   CHAR (1)       NULL,
    [termoff]      CHAR (1)       NULL,
    [prevfam]      CHAR (3)       NULL,
    [uexit1]       SMALLINT       NULL,
    [uexit2]       SMALLINT       NULL,
    [aliasno]      CHAR (13)      NULL,
    [usealias]     CHAR (1)       NULL,
    [miscadded]    CHAR (3)       NULL,
    [miscsub]      CHAR (3)       NULL,
    [si1]          CHAR (1)       NULL,
    [si2]          CHAR (1)       NULL,
    [si3]          CHAR (1)       NULL,
    [vat1]         CHAR (1)       NULL,
    [vat2]         CHAR (1)       NULL,
    [vat3]         CHAR (1)       NULL,
    [vat4]         CHAR (1)       NULL,
    [vat5]         CHAR (1)       NULL,
    [vat6]         CHAR (1)       NULL,
    [vat7]         CHAR (1)       NULL,
    [wastctr]      INT            NULL,
    [jrnprint]     CHAR (1)       NULL,
    [pronewprice]  CHAR (1)       NULL,
    [proretrn]     CHAR (1)       NULL,
    [prorepeat]    CHAR (1)       NULL,
    [skureq]       CHAR (1)       NULL,
    [slipreq]      CHAR (1)       NULL,
    [superreq]     CHAR (1)       NULL,
    [mancost]      CHAR (1)       NULL,
    [enabsale]     CHAR (1)       NULL,
    [enabset]      CHAR (1)       NULL,
    [asmmult]      CHAR (1)       NULL,
    [plulab]       CHAR (1)       NULL,
    [kiloitem]     CHAR (1)       NULL,
    [fracitem]     CHAR (1)       NULL,
    [invind]       CHAR (1)       NULL,
    [ex21271]      CHAR (1)       NULL,
    [ex21272]      CHAR (1)       NULL,
    [ex21273]      CHAR (1)       NULL,
    [comm2127]     CHAR (4)       NULL,
    [freqitem]     CHAR (4)       NULL,
    [coupstart]    SMALLDATETIME  NULL,
    [coupend]      SMALLDATETIME  NULL,
    [couptype]     CHAR (2)       NULL,
    [wghtlimit]    SMALLINT       NULL,
    [resweek]      CHAR (7)       NULL,
    [res1start]    INT            NULL,
    [res1end]      INT            NULL,
    [res2start]    INT            NULL,
    [res2end]      INT            NULL,
    [plumesg]      CHAR (2)       NULL,
    [qtylimit]     SMALLINT       NULL,
    [posmethod]    CHAR (10)      NULL,
    [pospm1]       SMALLINT       NULL,
    [posprice1]    NUMERIC (6, 2) NULL,
    [pospm2]       SMALLINT       NULL,
    [posprice2]    NUMERIC (6, 2) NULL,
    [pospm3]       SMALLINT       NULL,
    [posprice3]    NUMERIC (6, 2) NULL,
    [prompr]       CHAR (1)       NULL,
    [coupv7000]    CHAR (13)      NULL,
    [res2_4680]    CHAR (1)       NULL,
    [res3_4680]    CHAR (1)       NULL,
    [resflg1]      CHAR (1)       NULL,
    [resflg2]      CHAR (1)       NULL,
    [resflg3]      CHAR (1)       NULL,
    [resflg4]      CHAR (1)       NULL,
    [resflg5]      CHAR (1)       NULL,
    [resflg6]      CHAR (1)       NULL,
    [resflg7]      CHAR (1)       NULL,
    [freqcode]     SMALLINT       NULL,
    [shlfwdth]     SMALLINT       NULL,
    [shlfdpth]     SMALLINT       NULL,
    [shlfhght]     SMALLINT       NULL,
    [discprom]     INT            NULL,
    [minpurch]     CHAR (1)       NULL,
    [operover]     CHAR (1)       NULL,
    [item7000]     CHAR (10)      NULL,
    [agecode]      CHAR (2)       NULL,
    [storcode]     CHAR (13)      NULL,
    [thfamcde]     CHAR (3)       NULL,
    [prohrefd]     CHAR (1)       NULL,
    [taxincfl]     CHAR (1)       NULL,
    [frbyvdcp]     CHAR (1)       NULL,
    [prohmark]     CHAR (1)       NULL,
    [atdamtfl]     CHAR (1)       NULL,
    [atdpctfl]     CHAR (1)       NULL,
    [retrecfl]     CHAR (1)       NULL,
    [sptxitem]     CHAR (1)       NULL,
    [negitem]      CHAR (1)       NULL,
    [kydpover]     CHAR (1)       NULL,
    [notincmo]     CHAR (1)       NULL,
    [prowicsa]     CHAR (1)       NULL,
    [si4]          CHAR (1)       NULL,
    [si5]          CHAR (1)       NULL,
    [si6]          CHAR (1)       NULL,
    [si7]          CHAR (1)       NULL,
    [si8]          CHAR (1)       NULL,
    [minordpr]     NUMERIC (6, 2) NULL,
    [msrp]         NUMERIC (6, 2) NULL,
    [autdamt]      NUMERIC (6, 2) NULL,
    [autdpct]      NUMERIC (5, 2) NULL,
    [cpmfgnum]     INT            NULL,
    [cpminpur]     NUMERIC (6, 2) NULL,
    [cpseqnum]     SMALLINT       NULL,
    [itranstr]     SMALLINT       NULL,
    [itranmfg]     SMALLINT       NULL,
    [itmreqcp]     SMALLINT       NULL,
    [exitminp]     CHAR (1)       NULL,
    [minpmfg]      CHAR (1)       NULL,
    [minpdept]     CHAR (1)       NULL,
    [unitcoup]     CHAR (1)       NULL,
    [netvalcp]     CHAR (1)       NULL,
    [bonptsap]     CHAR (1)       NULL,
    [bonptson]     CHAR (1)       NULL,
    [salprend]     SMALLDATETIME  NULL,
    [fstprice]     CHAR (10)      NULL,
    [priclnk]      INT            NULL
);




GO



GO



GO



GO


