CREATE TABLE [dbo].[item_prep] (
    [Item_Key]                INT            NOT NULL,
    [Item_Description]        VARCHAR (30)   NULL,
    [Sign_Description]        VARCHAR (50)   NULL,
    [Ingredients]             VARCHAR (972)  NULL,
    [SubTeam_No]              CHAR (4)       NULL,
    [Sales_Account]           INT            NULL,
    [Package_Desc1]           INT            NULL,
    [Package_Desc2]           NUMERIC (7, 3) NULL,
    [Package_Unit_ID]         INT            NULL,
    [Min_Temperature]         INT            NOT NULL,
    [Max_Temperature]         INT            NOT NULL,
    [Units_Per_Pallet]        INT            NOT NULL,
    [Average_Unit_Weight]     INT            NOT NULL,
    [Tie]                     INT            NOT NULL,
    [High]                    INT            NOT NULL,
    [Yield]                   INT            NOT NULL,
    [Brand_ID]                INT            NULL,
    [Category_ID]             INT            NULL,
    [Origin_ID]               INT            NULL,
    [ShelfLife_Id]            INT            NULL,
    [ShelfLife_Length]        SMALLINT       NOT NULL,
    [Retail_Unit_ID]          INT            NULL,
    [Vendor_Unit_ID]          INT            NOT NULL,
    [Distribution_Unit_ID]    INT            NOT NULL,
    [Deleted_Item]            INT            NOT NULL,
    [Discontinue_Item]        INT            NOT NULL,
    [WFM_Item]                INT            NOT NULL,
    [Not_Available]           INT            NOT NULL,
    [Pre_Order]               INT            NOT NULL,
    [Remove_Item]             INT            NOT NULL,
    [NoDistMarkup]            INT            NOT NULL,
    [Organic]                 INT            NOT NULL,
    [Refrigerated]            INT            NOT NULL,
    [Keep_Frozen]             INT            NOT NULL,
    [Shipper_Item]            INT            NOT NULL,
    [Full_Pallet_Only]        INT            NOT NULL,
    [User_ID]                 INT            NULL,
    [POS_Description]         VARCHAR (25)   NULL,
    [Retail_Sale]             INT            NOT NULL,
    [Food_Stamps]             BIT            NULL,
    [Discountable]            BIT            NULL,
    [Price_Required]          INT            NULL,
    [Quantity_Required]       BIT            NULL,
    [ItemType_ID]             INT            NOT NULL,
    [HFM_Item]                INT            NOT NULL,
    [ScaleDesc1]              VARCHAR (32)   NULL,
    [ScaleDesc2]              VARCHAR (32)   NULL,
    [Not_AvailableNote]       INT            NULL,
    [CountryProc_ID]          INT            NULL,
    [Insert_Date]             DATETIME       NULL,
    [Manufacturing_Unit_ID]   INT            NOT NULL,
    [EXEDistributed]          INT            NOT NULL,
    [ClassID]                 INT            NOT NULL,
    [User_ID_Date]            INT            NULL,
    [DistSubTeam_No]          CHAR (4)       NULL,
    [CostedByWeight]          INT            NOT NULL,
    [TaxClassID]              INT            NOT NULL,
    [LabelType_ID]            INT            NOT NULL,
    [ScaleDesc3]              VARCHAR (32)   NULL,
    [ScaleDesc4]              VARCHAR (32)   NULL,
    [ScaleTare]               SMALLINT       NULL,
    [ScaleUseBy]              SMALLINT       NULL,
    [ScaleForcedTare]         CHAR (1)       NULL,
    [QtyProhibit]             BIT            NULL,
    [GroupList]               SMALLINT       NULL,
    [Recall_Flag]             INT            NOT NULL,
    [LockAuth]                CHAR (4)       NULL,
    [SameChain]               SMALLINT       NULL,
    [chain_code]              CHAR (13)      NULL,
    [Identifier]              VARCHAR (12)   NULL,
    [CheckDigit]              INT            NULL,
    [sku_number]              CHAR (12)      NULL,
    [National_Identifier]     INT            NOT NULL,
    [IdentifierType]          VARCHAR (1)    NOT NULL,
    [Scale_Identifier]        BIT            NULL,
    [NumPluDigitsSentToScale] INT            NULL,
    [upcno]                   CHAR (13)      NULL,
    [unit_abbreviation]       VARCHAR (5)    NULL,
    [unit_name]               VARCHAR (25)   NULL,
    [Extra_Text]              VARCHAR (972)  NULL,
    [Scale_ScaleUOMUnit_Id]   INT            NULL,
    [Scale_ByCount]           SMALLINT       NULL,
    [Scale_FixedWeight]       INT            NULL,
    [Scale_LabelFormat]       SMALLINT       NOT NULL,
    [Venue]                   CHAR (6)       NULL,
    [GoLocal]                 CHAR (2)       NULL,
    [MiscAlpha2]              CHAR (26)      NULL,
    [Commodity]               SMALLINT       NULL,
    [MiscAlpha1]              CHAR (10)      NULL,
    [DiscoDate]               SMALLDATETIME  NULL,
    [Unit_Price_Category]     INT            NULL,
    [Product_Code]            VARCHAR (15)   NULL
);




GO
CREATE NONCLUSTERED INDEX [ip_u]
    ON [dbo].[item_prep]([upcno] ASC);


GO
CREATE NONCLUSTERED INDEX [ip_i]
    ON [dbo].[item_prep]([Item_Key] ASC);

