CREATE TABLE [dbo].[JDA_ItemSync] (
    [JDA_ItemSync_ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [ActionCode]                  CHAR (1)        NOT NULL,
    [ApplyDate]                   DATETIME        NOT NULL,
    [Item_Key]                    INT             NOT NULL,
    [Item_Description]            VARCHAR (60)    NULL,
    [JDA_Dept]                    INT             NULL,
    [JDA_SubDept]                 INT             NULL,
    [JDA_Class]                   INT             NULL,
    [JDA_SubClass]                INT             NULL,
    [Package_Desc1]               INT             NULL,
    [Package_Desc2]               DECIMAL (10, 2) NULL,
    [Package_Unit_Id]             VARCHAR (6)     NULL,
    [JDA_Brand_ID]                VARCHAR (6)     NULL,
    [Retail_Unit_ID]              VARCHAR (6)     NULL,
    [Deleted_Item]                BIT             NULL,
    [Discontinue_Item]            BIT             NULL,
    [WFM_Item]                    BIT             NULL,
    [Vendor_Unit_ID]              VARCHAR (6)     NULL,
    [Manager_ID]                  TINYINT         NULL,
    [SyncState]                   TINYINT         DEFAULT ((0)) NOT NULL,
    [IRMA_Subteam_No]             INT             NULL,
    [IRMA_Category_ID]            INT             NULL,
    [IRMA_ProdHierarchyLevel3_ID] INT             NULL,
    [IRMA_ProdHierarchyLevel4_ID] INT             NULL,
    [IRMA_Brand_ID]               INT             NULL,
    [IRMA_Package_Unit_ID]        INT             NULL,
    [IRMA_Retail_Unit_ID]         INT             NULL,
    [IRMA_Vendor_Unit_ID]         INT             NULL,
    CONSTRAINT [PK_JDA_ItemSync] PRIMARY KEY CLUSTERED ([JDA_ItemSync_ID] ASC)
);

