CREATE PROCEDURE [dbo].[AddOrUpdateItemAttributesNutrition]
	@nutritionAttributes [dbo].ItemNutritionAttributesType READONLY
AS
BEGIN
	-- =========================================
	-- Locale Variables
	-- =========================================
	DECLARE @today DATETIME = GETDATE();
	DECLARE @totalRecordCount int;
	DECLARE @insertRecordCount int;

	-- =========================================
	-- Insert / Update based on ItemID
	-- =========================================
	SELECT * INTO #nutrition FROM @nutritionAttributes;
	SET @totalRecordCount = @@ROWCOUNT;

	SELECT
		ItemID,
		RecipeName,
		Allergens,
		Ingredients,
		ServingsPerPortion,
		ServingSizeDesc,
		ServingPerContainer,
		HshRating,
		ServingUnits,
		SizeWeight,
		Calories,
		CaloriesFat,
		CaloriesSaturatedFat,
		TotalFatWeight,
		TotalFatPercentage,
		SaturatedFatWeight,
		SaturatedFatPercent,
		PolyunsaturatedFat,
		MonounsaturatedFat,
		CholesterolWeight,
		CholesterolPercent,
		SodiumWeight,
		SodiumPercent,
		PotassiumWeight,
		PotassiumPercent,
		TotalCarbohydrateWeight,
		TotalCarbohydratePercent,
		DietaryFiberWeight,
		DietaryFiberPercent,
		SolubleFiber,
		InsolubleFiber,
		Sugar,
		SugarAlcohol,
		OtherCarbohydrates,
		ProteinWeight,
		ProteinPercent,
		VitaminA,
		Betacarotene,
		VitaminC,
		Calcium,
		Iron,
		VitaminD,
		VitaminE,
		Thiamin,
		Riboflavin,
		Niacin,
		VitaminB6,
		Folate,
		VitaminB12,
		Biotin,
		PantothenicAcid,
		Phosphorous,
		Iodine,
		Magnesium,
		Zinc,
		Copper,
		TransFat,
		CaloriesFromTransFat,
		Om6Fatty,
		Om3Fatty,
		Starch,
		Chloride,
		Chromium,
		VitaminK,
		Manganese,
		Molybdenum,
		Selenium,
		TransFatWeight
	INTO #insertNutrition
	FROM #nutrition n
	WHERE NOT EXISTS (SELECT 1 FROM dbo.ItemAttributes_Nutrition i WHERE i.ItemID = n.ItemID);

	SET @insertRecordCount = @@ROWCOUNT

	BEGIN TRY
	BEGIN TRAN
		IF @totalRecordCount <> @insertRecordCount
			UPDATE n
			SET
				n.RecipeName = t.RecipeName,
				n.Allergens = t.Allergens,
				n.Ingredients = t.Ingredients,
				n.ServingsPerPortion = t.ServingsPerPortion,
				n.ServingSizeDesc = t.ServingSizeDesc,
				n.ServingPerContainer = t.ServingPerContainer,
				n.HshRating = t.HshRating,
				n.ServingUnits = t.ServingUnits,
				n.SizeWeight = t.SizeWeight,
				n.Calories = t.Calories,
				n.CaloriesFat = t.CaloriesFat,
				n.CaloriesSaturatedFat = t.CaloriesSaturatedFat,
				n.TotalFatWeight = t.TotalFatWeight,
				n.TotalFatPercentage = t.TotalFatPercentage,
				n.SaturatedFatWeight = t.SaturatedFatWeight,
				n.SaturatedFatPercent = t.SaturatedFatPercent,
				n.PolyunsaturatedFat = t.PolyunsaturatedFat,
				n.MonounsaturatedFat = t.MonounsaturatedFat,
				n.CholesterolWeight = t.CholesterolWeight,
				n.CholesterolPercent = t.CholesterolPercent,
				n.SodiumWeight = t.SodiumWeight,
				n.SodiumPercent = t.SodiumPercent,
				n.PotassiumWeight = t.PotassiumWeight,
				n.PotassiumPercent = t.PotassiumPercent,
				n.TotalCarbohydrateWeight = t.TotalCarbohydrateWeight,
				n.TotalCarbohydratePercent = t.TotalCarbohydratePercent,
				n.DietaryFiberWeight = t.DietaryFiberWeight,
				n.DietaryFiberPercent = t.DietaryFiberPercent,
				n.SolubleFiber = t.SolubleFiber,
				n.InsolubleFiber = t.InsolubleFiber,
				n.Sugar = t.Sugar,
				n.SugarAlcohol = t.SugarAlcohol,
				n.OtherCarbohydrates = t.OtherCarbohydrates,
				n.ProteinWeight = t.ProteinWeight,
				n.ProteinPercent = t.ProteinPercent,
				n.VitaminA = t.VitaminA,
				n.Betacarotene = t.Betacarotene,
				n.VitaminC = t.VitaminC,
				n.Calcium = t.Calcium,
				n.Iron = t.Iron,
				n.VitaminD = t.VitaminD,
				n.VitaminE = t.VitaminE,
				n.Thiamin = t.Thiamin,
				n.Riboflavin = t.Riboflavin,
				n.Niacin = t.Niacin,
				n.VitaminB6 = t.VitaminB6,
				n.Folate = t.Folate,
				n.VitaminB12 = t.VitaminB12,
				n.Biotin = t.Biotin,
				n.PantothenicAcid = t.PantothenicAcid,
				n.Phosphorous = t.Phosphorous,
				n.Iodine = t.Iodine,
				n.Magnesium = t.Magnesium,
				n.Zinc = t.Zinc,
				n.Copper = t.Copper,
				n.TransFat = t.TransFat,
				n.CaloriesFromTransFat = t.CaloriesFromTransFat,
				n.Om6Fatty = t.Om6Fatty,
				n.Om3Fatty = t.Om3Fatty,
				n.Starch = t.Starch,
				n.Chloride = t.Chloride,
				n.Chromium = t.Chromium,
				n.VitaminK = t.VitaminK,
				n.Manganese = t.Manganese,
				n.Molybdenum = t.Molybdenum,
				n.Selenium = t.Selenium,
				n.TransFatWeight = t.TransFatWeight
			FROM dbo.ItemAttributes_Nutrition	n
			INNER JOIN #nutrition				t on n.ItemID = t.ItemID

		IF @insertRecordCount > 0
			INSERT INTO dbo.ItemAttributes_Nutrition
			(
				ItemID,
				RecipeName,
				Allergens,
				Ingredients,
				ServingsPerPortion,
				ServingSizeDesc,
				ServingPerContainer,
				HshRating,
				ServingUnits,
				SizeWeight,
				Calories,
				CaloriesFat,
				CaloriesSaturatedFat,
				TotalFatWeight,
				TotalFatPercentage,
				SaturatedFatWeight,
				SaturatedFatPercent,
				PolyunsaturatedFat,
				MonounsaturatedFat,
				CholesterolWeight,
				CholesterolPercent,
				SodiumWeight,
				SodiumPercent,
				PotassiumWeight,
				PotassiumPercent,
				TotalCarbohydrateWeight,
				TotalCarbohydratePercent,
				DietaryFiberWeight,
				DietaryFiberPercent,
				SolubleFiber,
				InsolubleFiber,
				Sugar,
				SugarAlcohol,
				OtherCarbohydrates,
				ProteinWeight,
				ProteinPercent,
				VitaminA,
				Betacarotene,
				VitaminC,
				Calcium,
				Iron,
				VitaminD,
				VitaminE,
				Thiamin,
				Riboflavin,
				Niacin,
				VitaminB6,
				Folate,
				VitaminB12,
				Biotin,
				PantothenicAcid,
				Phosphorous,
				Iodine,
				Magnesium,
				Zinc,
				Copper,
				TransFat,
				CaloriesFromTransFat,
				Om6Fatty,
				Om3Fatty,
				Starch,
				Chloride,
				Chromium,
				VitaminK,
				Manganese,
				Molybdenum,
				Selenium,
				TransFatWeight,
				AddedDate
			)
			SELECT
				ItemID,
				RecipeName,
				Allergens,
				Ingredients,
				ServingsPerPortion,
				ServingSizeDesc,
				ServingPerContainer,
				HshRating,
				ServingUnits,
				SizeWeight,
				Calories,
				CaloriesFat,
				CaloriesSaturatedFat,
				TotalFatWeight,
				TotalFatPercentage,
				SaturatedFatWeight,
				SaturatedFatPercent,
				PolyunsaturatedFat,
				MonounsaturatedFat,
				CholesterolWeight,
				CholesterolPercent,
				SodiumWeight,
				SodiumPercent,
				PotassiumWeight,
				PotassiumPercent,
				TotalCarbohydrateWeight,
				TotalCarbohydratePercent,
				DietaryFiberWeight,
				DietaryFiberPercent,
				SolubleFiber,
				InsolubleFiber,
				Sugar,
				SugarAlcohol,
				OtherCarbohydrates,
				ProteinWeight,
				ProteinPercent,
				VitaminA,
				Betacarotene,
				VitaminC,
				Calcium,
				Iron,
				VitaminD,
				VitaminE,
				Thiamin,
				Riboflavin,
				Niacin,
				VitaminB6,
				Folate,
				VitaminB12,
				Biotin,
				PantothenicAcid,
				Phosphorous,
				Iodine,
				Magnesium,
				Zinc,
				Copper,
				TransFat,
				CaloriesFromTransFat,
				Om6Fatty,
				Om3Fatty,
				Starch,
				Chloride,
				Chromium,
				VitaminK,
				Manganese,
				Molybdenum,
				Selenium,
				TransFatWeight,
				@today
			FROM #insertNutrition

		COMMIT TRAN
    END TRY
    BEGIN CATCH
	    ROLLBACK TRAN;
	    THROW
    END CATCH
END
GO

GRANT EXECUTE ON [dbo].[AddOrUpdateItemAttributesNutrition] TO [MammothRole]
GO