using System;
using Irma.Framework;
using Mammoth.Price.Controller.DataAccess.Tests;

namespace Irma.Testing.Builders
{
    public class TestPriceBatchDetailBuilder
    {
        private int priceBatchDetailID;
        private int item_Key;
        private int store_No;
        private System.Nullable<int> priceBatchHeaderID;
        private System.Nullable<byte> itemChgTypeID;
        private System.Nullable<byte> priceChgTypeID;
        private System.Nullable<System.DateTime> startDate;
        private System.Nullable<byte> multiple;
        private System.Nullable<decimal> price;
        private System.Nullable<decimal> mSRPPrice;
        private System.Nullable<byte> mSRPMultiple;
        private System.Nullable<int> pricingMethod_ID;
        private System.Nullable<byte> sale_Multiple;
        private System.Nullable<decimal> sale_Price;
        private System.Nullable<System.DateTime> sale_End_Date;
        private System.Nullable<byte> sale_Max_Quantity;
        private System.Nullable<short> sale_Mix_Match;
        private System.Nullable<byte> sale_Earned_Disc1;
        private System.Nullable<byte> sale_Earned_Disc2;
        private System.Nullable<byte> sale_Earned_Disc3;
        private System.Nullable<decimal> case_Price;
        private string sign_Description;
        private string ingredients;
        private string identifier;
        private System.Nullable<bool> sold_By_Weight;
        private System.Nullable<int> subTeam_No;
        private string origin_Name;
        private string brand_Name;
        private string retail_Unit_Abbr;
        private string retail_Unit_Full;
        private string package_Unit;
        private System.Nullable<decimal> package_Desc1;
        private System.Nullable<decimal> package_Desc2;
        private System.Nullable<bool> organic;
        private System.Nullable<int> vendor_Id;
        private System.Nullable<int> itemType_ID;
        private string scaleDesc1;
        private string scaleDesc2;
        private string pOS_Description;
        private System.Nullable<bool> restricted_Hours;
        private System.Nullable<bool> quantity_Required;
        private System.Nullable<bool> price_Required;
        private System.Nullable<bool> retail_Sale;
        private System.Nullable<bool> discountable;
        private System.Nullable<bool> food_Stamps;
        private System.Nullable<bool> iBM_Discount;
        private System.Nullable<bool> hobart_Item;
        private bool printSign;
        private bool lineDrive;
        private System.Nullable<decimal> pOSPrice;
        private System.Nullable<decimal> pOSSale_Price;
        private System.Nullable<int> offer_ID;
        private System.Nullable<System.DateTime> avgCostUpdated;
        private System.Nullable<bool> notAuthorizedForSale;
        private bool deleted_Item;
        private System.Nullable<int> user_ID;
        private System.Nullable<System.DateTime> user_ID_Date;
        private System.Nullable<int> labelType_ID;
        private System.DateTime insert_Date;
        private System.Nullable<byte> offerChgTypeID;
        private System.Nullable<bool> qtyProhibit;
        private System.Nullable<int> groupList;
        private System.Nullable<int> posTare;
        private System.Nullable<int> linkedItem;
        private System.Nullable<bool> grillPrint;
        private System.Nullable<int> ageCode;
        private System.Nullable<bool> visualVerify;
        private System.Nullable<bool> srCitizenDiscount;
        private System.Nullable<System.DateTime> asOfDate;
        private bool autoGenerated;
        private bool expired;
        private string pOSLinkCode;
        private string insertApplication;
        private System.Nullable<bool> retailUnit_WeightUnit;
        private System.Nullable<int> tagTypeID;
        private System.Nullable<int> tagTypeID2;
        private bool endedEarly;
        private System.Nullable<int> mixMatch;
        private System.Nullable<decimal> purchaseThresholdCouponAmount;
        private System.Nullable<bool> purchaseThresholdCouponSubTeam;
        private bool reAuthFlag;
        private System.Nullable<int> retail_Unit_ID;
        private System.Nullable<int> package_Unit_ID;
        private string item_Description;
        private System.Nullable<bool> case_Discount;
        private System.Nullable<bool> coupon_Multiplier;
        private System.Nullable<short> misc_Transaction_Sale;
        private System.Nullable<short> misc_Transaction_Refund;
        private System.Nullable<bool> recall_Flag;
        private System.Nullable<int> ice_Tare;
        private string product_Code;
        private System.Nullable<int> unit_Price_Category;
        private System.Nullable<int> kitchenRoute_ID;
        private System.Nullable<byte> routing_Priority;
        private System.Nullable<bool> consolidate_Price_To_Prev_Item;
        private System.Nullable<bool> print_Condiment_On_Receipt;
        private System.Nullable<bool> age_Restrict;
        private System.Nullable<int> sLIMRequestID;
        private System.Nullable<bool> localItem;
        private System.Nullable<bool> fSA_Eligible;
        private System.Nullable<int> itemSurcharge;
        private System.Nullable<bool> cancelAllSales;
        private Irma.Framework.Item item;
        private Irma.Framework.Item item1;
        private Irma.Framework.ItemUnit itemUnit;
        private Irma.Framework.ItemUnit itemUnit1;
        private Irma.Framework.Store store;

        public TestPriceBatchDetailBuilder()
        {
            this.priceBatchDetailID = 0;
            this.item_Key = 0;
            this.store_No = 0;
            this.priceBatchHeaderID = null;
            this.itemChgTypeID = null;
            this.priceChgTypeID = null;
            this.startDate = null;
            this.multiple = null;
            this.price = null;
            this.mSRPPrice = null;
            this.mSRPMultiple = null;
            this.pricingMethod_ID = null;
            this.sale_Multiple = null;
            this.sale_Price = null;
            this.sale_End_Date = null;
            this.sale_Max_Quantity = null;
            this.sale_Mix_Match = null;
            this.sale_Earned_Disc1 = null;
            this.sale_Earned_Disc2 = null;
            this.sale_Earned_Disc3 = null;
            this.case_Price = null;
            this.sign_Description = null;
            this.ingredients = null;
            this.identifier = null;
            this.sold_By_Weight = null;
            this.subTeam_No = null;
            this.origin_Name = null;
            this.brand_Name = null;
            this.retail_Unit_Abbr = null;
            this.retail_Unit_Full = null;
            this.package_Unit = null;
            this.package_Desc1 = null;
            this.package_Desc2 = null;
            this.organic = null;
            this.vendor_Id = null;
            this.itemType_ID = null;
            this.scaleDesc1 = null;
            this.scaleDesc2 = null;
            this.pOS_Description = null;
            this.restricted_Hours = null;
            this.quantity_Required = null;
            this.price_Required = null;
            this.retail_Sale = null;
            this.discountable = null;
            this.food_Stamps = null;
            this.iBM_Discount = null;
            this.hobart_Item = null;
            this.printSign = false;
            this.lineDrive = false;
            this.pOSPrice = null;
            this.pOSSale_Price = null;
            this.offer_ID = null;
            this.avgCostUpdated = null;
            this.notAuthorizedForSale = null;
            this.deleted_Item = false;
            this.user_ID = null;
            this.user_ID_Date = null;
            this.labelType_ID = null;
            this.insert_Date = DateTime.Now;
            this.offerChgTypeID = null;
            this.qtyProhibit = null;
            this.groupList = null;
            this.posTare = null;
            this.linkedItem = null;
            this.grillPrint = null;
            this.ageCode = null;
            this.visualVerify = null;
            this.srCitizenDiscount = null;
            this.asOfDate = null;
            this.autoGenerated = false;
            this.expired = false;
            this.pOSLinkCode = null;
            this.insertApplication = null;
            this.retailUnit_WeightUnit = null;
            this.tagTypeID = null;
            this.tagTypeID2 = null;
            this.endedEarly = false;
            this.mixMatch = null;
            this.purchaseThresholdCouponAmount = null;
            this.purchaseThresholdCouponSubTeam = null;
            this.reAuthFlag = false;
            this.retail_Unit_ID = null;
            this.package_Unit_ID = null;
            this.item_Description = null;
            this.case_Discount = null;
            this.coupon_Multiplier = null;
            this.misc_Transaction_Sale = null;
            this.misc_Transaction_Refund = null;
            this.recall_Flag = null;
            this.ice_Tare = null;
            this.product_Code = null;
            this.unit_Price_Category = null;
            this.kitchenRoute_ID = null;
            this.routing_Priority = null;
            this.consolidate_Price_To_Prev_Item = null;
            this.print_Condiment_On_Receipt = null;
            this.age_Restrict = null;
            this.sLIMRequestID = null;
            this.localItem = null;
            this.fSA_Eligible = null;
            this.itemSurcharge = null;
            this.cancelAllSales = null;
            this.item = null;
            this.item1 = null;
            this.itemUnit = null;
            this.itemUnit1 = null;
            this.store = null;
        }

        public TestPriceBatchDetailBuilder WithPriceBatchDetailID(int priceBatchDetailID)
        {
            this.priceBatchDetailID = priceBatchDetailID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithItem_Key(int item_Key)
        {
            this.item_Key = item_Key;
            return this;
        }

        public TestPriceBatchDetailBuilder WithStore_No(int store_No)
        {
            this.store_No = store_No;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPriceBatchHeaderID(System.Nullable<int> priceBatchHeaderID)
        {
            this.priceBatchHeaderID = priceBatchHeaderID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithItemChgTypeID(System.Nullable<byte> itemChgTypeID)
        {
            this.itemChgTypeID = itemChgTypeID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPriceChgTypeID(System.Nullable<byte> priceChgTypeID)
        {
            this.priceChgTypeID = priceChgTypeID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithStartDate(System.Nullable<System.DateTime> startDate)
        {
            this.startDate = startDate;
            return this;
        }

        public TestPriceBatchDetailBuilder WithMultiple(System.Nullable<byte> multiple)
        {
            this.multiple = multiple;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPrice(System.Nullable<decimal> price)
        {
            this.price = price;
            return this;
        }

        public TestPriceBatchDetailBuilder WithMSRPPrice(System.Nullable<decimal> mSRPPrice)
        {
            this.mSRPPrice = mSRPPrice;
            return this;
        }

        public TestPriceBatchDetailBuilder WithMSRPMultiple(System.Nullable<byte> mSRPMultiple)
        {
            this.mSRPMultiple = mSRPMultiple;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPricingMethod_ID(System.Nullable<int> pricingMethod_ID)
        {
            this.pricingMethod_ID = pricingMethod_ID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithSale_Multiple(System.Nullable<byte> sale_Multiple)
        {
            this.sale_Multiple = sale_Multiple;
            return this;
        }

        public TestPriceBatchDetailBuilder WithSale_Price(System.Nullable<decimal> sale_Price)
        {
            this.sale_Price = sale_Price;
            return this;
        }

        public TestPriceBatchDetailBuilder WithSale_End_Date(System.Nullable<System.DateTime> sale_End_Date)
        {
            this.sale_End_Date = sale_End_Date;
            return this;
        }

        public TestPriceBatchDetailBuilder WithSale_Max_Quantity(System.Nullable<byte> sale_Max_Quantity)
        {
            this.sale_Max_Quantity = sale_Max_Quantity;
            return this;
        }

        public TestPriceBatchDetailBuilder WithSale_Mix_Match(System.Nullable<short> sale_Mix_Match)
        {
            this.sale_Mix_Match = sale_Mix_Match;
            return this;
        }

        public TestPriceBatchDetailBuilder WithSale_Earned_Disc1(System.Nullable<byte> sale_Earned_Disc1)
        {
            this.sale_Earned_Disc1 = sale_Earned_Disc1;
            return this;
        }

        public TestPriceBatchDetailBuilder WithSale_Earned_Disc2(System.Nullable<byte> sale_Earned_Disc2)
        {
            this.sale_Earned_Disc2 = sale_Earned_Disc2;
            return this;
        }

        public TestPriceBatchDetailBuilder WithSale_Earned_Disc3(System.Nullable<byte> sale_Earned_Disc3)
        {
            this.sale_Earned_Disc3 = sale_Earned_Disc3;
            return this;
        }

        public TestPriceBatchDetailBuilder WithCase_Price(System.Nullable<decimal> case_Price)
        {
            this.case_Price = case_Price;
            return this;
        }

        public TestPriceBatchDetailBuilder WithSign_Description(string sign_Description)
        {
            this.sign_Description = sign_Description;
            return this;
        }

        public TestPriceBatchDetailBuilder WithIngredients(string ingredients)
        {
            this.ingredients = ingredients;
            return this;
        }

        public TestPriceBatchDetailBuilder WithIdentifier(string identifier)
        {
            this.identifier = identifier;
            return this;
        }

        public TestPriceBatchDetailBuilder WithSold_By_Weight(System.Nullable<bool> sold_By_Weight)
        {
            this.sold_By_Weight = sold_By_Weight;
            return this;
        }

        public TestPriceBatchDetailBuilder WithSubTeam_No(System.Nullable<int> subTeam_No)
        {
            this.subTeam_No = subTeam_No;
            return this;
        }

        public TestPriceBatchDetailBuilder WithOrigin_Name(string origin_Name)
        {
            this.origin_Name = origin_Name;
            return this;
        }

        public TestPriceBatchDetailBuilder WithBrand_Name(string brand_Name)
        {
            this.brand_Name = brand_Name;
            return this;
        }

        public TestPriceBatchDetailBuilder WithRetail_Unit_Abbr(string retail_Unit_Abbr)
        {
            this.retail_Unit_Abbr = retail_Unit_Abbr;
            return this;
        }

        public TestPriceBatchDetailBuilder WithRetail_Unit_Full(string retail_Unit_Full)
        {
            this.retail_Unit_Full = retail_Unit_Full;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPackage_Unit(string package_Unit)
        {
            this.package_Unit = package_Unit;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPackage_Desc1(System.Nullable<decimal> package_Desc1)
        {
            this.package_Desc1 = package_Desc1;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPackage_Desc2(System.Nullable<decimal> package_Desc2)
        {
            this.package_Desc2 = package_Desc2;
            return this;
        }

        public TestPriceBatchDetailBuilder WithOrganic(System.Nullable<bool> organic)
        {
            this.organic = organic;
            return this;
        }

        public TestPriceBatchDetailBuilder WithVendor_Id(System.Nullable<int> vendor_Id)
        {
            this.vendor_Id = vendor_Id;
            return this;
        }

        public TestPriceBatchDetailBuilder WithItemType_ID(System.Nullable<int> itemType_ID)
        {
            this.itemType_ID = itemType_ID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithScaleDesc1(string scaleDesc1)
        {
            this.scaleDesc1 = scaleDesc1;
            return this;
        }

        public TestPriceBatchDetailBuilder WithScaleDesc2(string scaleDesc2)
        {
            this.scaleDesc2 = scaleDesc2;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPOS_Description(string pOS_Description)
        {
            this.pOS_Description = pOS_Description;
            return this;
        }

        public TestPriceBatchDetailBuilder WithRestricted_Hours(System.Nullable<bool> restricted_Hours)
        {
            this.restricted_Hours = restricted_Hours;
            return this;
        }

        public TestPriceBatchDetailBuilder WithQuantity_Required(System.Nullable<bool> quantity_Required)
        {
            this.quantity_Required = quantity_Required;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPrice_Required(System.Nullable<bool> price_Required)
        {
            this.price_Required = price_Required;
            return this;
        }

        public TestPriceBatchDetailBuilder WithRetail_Sale(System.Nullable<bool> retail_Sale)
        {
            this.retail_Sale = retail_Sale;
            return this;
        }

        public TestPriceBatchDetailBuilder WithDiscountable(System.Nullable<bool> discountable)
        {
            this.discountable = discountable;
            return this;
        }

        public TestPriceBatchDetailBuilder WithFood_Stamps(System.Nullable<bool> food_Stamps)
        {
            this.food_Stamps = food_Stamps;
            return this;
        }

        public TestPriceBatchDetailBuilder WithIBM_Discount(System.Nullable<bool> iBM_Discount)
        {
            this.iBM_Discount = iBM_Discount;
            return this;
        }

        public TestPriceBatchDetailBuilder WithHobart_Item(System.Nullable<bool> hobart_Item)
        {
            this.hobart_Item = hobart_Item;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPrintSign(bool printSign)
        {
            this.printSign = printSign;
            return this;
        }

        public TestPriceBatchDetailBuilder WithLineDrive(bool lineDrive)
        {
            this.lineDrive = lineDrive;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPOSPrice(System.Nullable<decimal> pOSPrice)
        {
            this.pOSPrice = pOSPrice;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPOSSale_Price(System.Nullable<decimal> pOSSale_Price)
        {
            this.pOSSale_Price = pOSSale_Price;
            return this;
        }

        public TestPriceBatchDetailBuilder WithOffer_ID(System.Nullable<int> offer_ID)
        {
            this.offer_ID = offer_ID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithAvgCostUpdated(System.Nullable<System.DateTime> avgCostUpdated)
        {
            this.avgCostUpdated = avgCostUpdated;
            return this;
        }

        public TestPriceBatchDetailBuilder WithNotAuthorizedForSale(System.Nullable<bool> notAuthorizedForSale)
        {
            this.notAuthorizedForSale = notAuthorizedForSale;
            return this;
        }

        public TestPriceBatchDetailBuilder WithDeleted_Item(bool deleted_Item)
        {
            this.deleted_Item = deleted_Item;
            return this;
        }

        public TestPriceBatchDetailBuilder WithUser_ID(System.Nullable<int> user_ID)
        {
            this.user_ID = user_ID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithUser_ID_Date(System.Nullable<System.DateTime> user_ID_Date)
        {
            this.user_ID_Date = user_ID_Date;
            return this;
        }

        public TestPriceBatchDetailBuilder WithLabelType_ID(System.Nullable<int> labelType_ID)
        {
            this.labelType_ID = labelType_ID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithInsert_Date(System.DateTime insert_Date)
        {
            this.insert_Date = insert_Date;
            return this;
        }

        public TestPriceBatchDetailBuilder WithOfferChgTypeID(System.Nullable<byte> offerChgTypeID)
        {
            this.offerChgTypeID = offerChgTypeID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithQtyProhibit(System.Nullable<bool> qtyProhibit)
        {
            this.qtyProhibit = qtyProhibit;
            return this;
        }

        public TestPriceBatchDetailBuilder WithGroupList(System.Nullable<int> groupList)
        {
            this.groupList = groupList;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPosTare(System.Nullable<int> posTare)
        {
            this.posTare = posTare;
            return this;
        }

        public TestPriceBatchDetailBuilder WithLinkedItem(System.Nullable<int> linkedItem)
        {
            this.linkedItem = linkedItem;
            return this;
        }

        public TestPriceBatchDetailBuilder WithGrillPrint(System.Nullable<bool> grillPrint)
        {
            this.grillPrint = grillPrint;
            return this;
        }

        public TestPriceBatchDetailBuilder WithAgeCode(System.Nullable<int> ageCode)
        {
            this.ageCode = ageCode;
            return this;
        }

        public TestPriceBatchDetailBuilder WithVisualVerify(System.Nullable<bool> visualVerify)
        {
            this.visualVerify = visualVerify;
            return this;
        }

        public TestPriceBatchDetailBuilder WithSrCitizenDiscount(System.Nullable<bool> srCitizenDiscount)
        {
            this.srCitizenDiscount = srCitizenDiscount;
            return this;
        }

        public TestPriceBatchDetailBuilder WithAsOfDate(System.Nullable<System.DateTime> asOfDate)
        {
            this.asOfDate = asOfDate;
            return this;
        }

        public TestPriceBatchDetailBuilder WithAutoGenerated(bool autoGenerated)
        {
            this.autoGenerated = autoGenerated;
            return this;
        }

        public TestPriceBatchDetailBuilder WithExpired(bool expired)
        {
            this.expired = expired;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPOSLinkCode(string pOSLinkCode)
        {
            this.pOSLinkCode = pOSLinkCode;
            return this;
        }

        public TestPriceBatchDetailBuilder WithInsertApplication(string insertApplication)
        {
            this.insertApplication = insertApplication;
            return this;
        }

        public TestPriceBatchDetailBuilder WithRetailUnit_WeightUnit(System.Nullable<bool> retailUnit_WeightUnit)
        {
            this.retailUnit_WeightUnit = retailUnit_WeightUnit;
            return this;
        }

        public TestPriceBatchDetailBuilder WithTagTypeID(System.Nullable<int> tagTypeID)
        {
            this.tagTypeID = tagTypeID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithTagTypeID2(System.Nullable<int> tagTypeID2)
        {
            this.tagTypeID2 = tagTypeID2;
            return this;
        }

        public TestPriceBatchDetailBuilder WithEndedEarly(bool endedEarly)
        {
            this.endedEarly = endedEarly;
            return this;
        }

        public TestPriceBatchDetailBuilder WithMixMatch(System.Nullable<int> mixMatch)
        {
            this.mixMatch = mixMatch;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPurchaseThresholdCouponAmount(System.Nullable<decimal> purchaseThresholdCouponAmount)
        {
            this.purchaseThresholdCouponAmount = purchaseThresholdCouponAmount;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPurchaseThresholdCouponSubTeam(System.Nullable<bool> purchaseThresholdCouponSubTeam)
        {
            this.purchaseThresholdCouponSubTeam = purchaseThresholdCouponSubTeam;
            return this;
        }

        public TestPriceBatchDetailBuilder WithReAuthFlag(bool reAuthFlag)
        {
            this.reAuthFlag = reAuthFlag;
            return this;
        }

        public TestPriceBatchDetailBuilder WithRetail_Unit_ID(System.Nullable<int> retail_Unit_ID)
        {
            this.retail_Unit_ID = retail_Unit_ID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPackage_Unit_ID(System.Nullable<int> package_Unit_ID)
        {
            this.package_Unit_ID = package_Unit_ID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithItem_Description(string item_Description)
        {
            this.item_Description = item_Description;
            return this;
        }

        public TestPriceBatchDetailBuilder WithCase_Discount(System.Nullable<bool> case_Discount)
        {
            this.case_Discount = case_Discount;
            return this;
        }

        public TestPriceBatchDetailBuilder WithCoupon_Multiplier(System.Nullable<bool> coupon_Multiplier)
        {
            this.coupon_Multiplier = coupon_Multiplier;
            return this;
        }

        public TestPriceBatchDetailBuilder WithMisc_Transaction_Sale(System.Nullable<short> misc_Transaction_Sale)
        {
            this.misc_Transaction_Sale = misc_Transaction_Sale;
            return this;
        }

        public TestPriceBatchDetailBuilder WithMisc_Transaction_Refund(System.Nullable<short> misc_Transaction_Refund)
        {
            this.misc_Transaction_Refund = misc_Transaction_Refund;
            return this;
        }

        public TestPriceBatchDetailBuilder WithRecall_Flag(System.Nullable<bool> recall_Flag)
        {
            this.recall_Flag = recall_Flag;
            return this;
        }

        public TestPriceBatchDetailBuilder WithIce_Tare(System.Nullable<int> ice_Tare)
        {
            this.ice_Tare = ice_Tare;
            return this;
        }

        public TestPriceBatchDetailBuilder WithProduct_Code(string product_Code)
        {
            this.product_Code = product_Code;
            return this;
        }

        public TestPriceBatchDetailBuilder WithUnit_Price_Category(System.Nullable<int> unit_Price_Category)
        {
            this.unit_Price_Category = unit_Price_Category;
            return this;
        }

        public TestPriceBatchDetailBuilder WithKitchenRoute_ID(System.Nullable<int> kitchenRoute_ID)
        {
            this.kitchenRoute_ID = kitchenRoute_ID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithRouting_Priority(System.Nullable<byte> routing_Priority)
        {
            this.routing_Priority = routing_Priority;
            return this;
        }

        public TestPriceBatchDetailBuilder WithConsolidate_Price_To_Prev_Item(System.Nullable<bool> consolidate_Price_To_Prev_Item)
        {
            this.consolidate_Price_To_Prev_Item = consolidate_Price_To_Prev_Item;
            return this;
        }

        public TestPriceBatchDetailBuilder WithPrint_Condiment_On_Receipt(System.Nullable<bool> print_Condiment_On_Receipt)
        {
            this.print_Condiment_On_Receipt = print_Condiment_On_Receipt;
            return this;
        }

        public TestPriceBatchDetailBuilder WithAge_Restrict(System.Nullable<bool> age_Restrict)
        {
            this.age_Restrict = age_Restrict;
            return this;
        }

        public TestPriceBatchDetailBuilder WithSLIMRequestID(System.Nullable<int> sLIMRequestID)
        {
            this.sLIMRequestID = sLIMRequestID;
            return this;
        }

        public TestPriceBatchDetailBuilder WithLocalItem(System.Nullable<bool> localItem)
        {
            this.localItem = localItem;
            return this;
        }

        public TestPriceBatchDetailBuilder WithFSA_Eligible(System.Nullable<bool> fSA_Eligible)
        {
            this.fSA_Eligible = fSA_Eligible;
            return this;
        }

        public TestPriceBatchDetailBuilder WithItemSurcharge(System.Nullable<int> itemSurcharge)
        {
            this.itemSurcharge = itemSurcharge;
            return this;
        }

        public TestPriceBatchDetailBuilder WithCancelAllSales(System.Nullable<bool> cancelAllSales)
        {
            this.cancelAllSales = cancelAllSales;
            return this;
        }

        public TestPriceBatchDetailBuilder WithItem(Irma.Framework.Item item)
        {
            this.item = item;
            return this;
        }

        public TestPriceBatchDetailBuilder WithItem1(Irma.Framework.Item item1)
        {
            this.item1 = item1;
            return this;
        }

        public TestPriceBatchDetailBuilder WithItemUnit(Irma.Framework.ItemUnit itemUnit)
        {
            this.itemUnit = itemUnit;
            return this;
        }

        public TestPriceBatchDetailBuilder WithItemUnit1(Irma.Framework.ItemUnit itemUnit1)
        {
            this.itemUnit1 = itemUnit1;
            return this;
        }

        public TestPriceBatchDetailBuilder WithStore(Irma.Framework.Store store)
        {
            this.store = store;
            return this;
        }

        public PriceBatchDetail Build()
        {
            PriceBatchDetail priceBatchDetail = new PriceBatchDetail();

            priceBatchDetail.PriceBatchDetailID = this.priceBatchDetailID;
            priceBatchDetail.Item_Key = this.item_Key;
            priceBatchDetail.Store_No = this.store_No;
            priceBatchDetail.PriceBatchHeaderID = this.priceBatchHeaderID;
            priceBatchDetail.ItemChgTypeID = this.itemChgTypeID;
            priceBatchDetail.PriceChgTypeID = this.priceChgTypeID;
            priceBatchDetail.StartDate = this.startDate;
            priceBatchDetail.Multiple = this.multiple;
            priceBatchDetail.Price = this.price;
            priceBatchDetail.MSRPPrice = this.mSRPPrice;
            priceBatchDetail.MSRPMultiple = this.mSRPMultiple;
            priceBatchDetail.PricingMethod_ID = this.pricingMethod_ID;
            priceBatchDetail.Sale_Multiple = this.sale_Multiple;
            priceBatchDetail.Sale_Price = this.sale_Price;
            priceBatchDetail.Sale_End_Date = this.sale_End_Date;
            priceBatchDetail.Sale_Max_Quantity = this.sale_Max_Quantity;
            priceBatchDetail.Sale_Mix_Match = this.sale_Mix_Match;
            priceBatchDetail.Sale_Earned_Disc1 = this.sale_Earned_Disc1;
            priceBatchDetail.Sale_Earned_Disc2 = this.sale_Earned_Disc2;
            priceBatchDetail.Sale_Earned_Disc3 = this.sale_Earned_Disc3;
            priceBatchDetail.Case_Price = this.case_Price;
            priceBatchDetail.Sign_Description = this.sign_Description;
            priceBatchDetail.Ingredients = this.ingredients;
            priceBatchDetail.Identifier = this.identifier;
            priceBatchDetail.Sold_By_Weight = this.sold_By_Weight;
            priceBatchDetail.SubTeam_No = this.subTeam_No;
            priceBatchDetail.Origin_Name = this.origin_Name;
            priceBatchDetail.Brand_Name = this.brand_Name;
            priceBatchDetail.Retail_Unit_Abbr = this.retail_Unit_Abbr;
            priceBatchDetail.Retail_Unit_Full = this.retail_Unit_Full;
            priceBatchDetail.Package_Unit = this.package_Unit;
            priceBatchDetail.Package_Desc1 = this.package_Desc1;
            priceBatchDetail.Package_Desc2 = this.package_Desc2;
            priceBatchDetail.Organic = this.organic;
            priceBatchDetail.Vendor_Id = this.vendor_Id;
            priceBatchDetail.ItemType_ID = this.itemType_ID;
            priceBatchDetail.ScaleDesc1 = this.scaleDesc1;
            priceBatchDetail.ScaleDesc2 = this.scaleDesc2;
            priceBatchDetail.POS_Description = this.pOS_Description;
            priceBatchDetail.Restricted_Hours = this.restricted_Hours;
            priceBatchDetail.Quantity_Required = this.quantity_Required;
            priceBatchDetail.Price_Required = this.price_Required;
            priceBatchDetail.Retail_Sale = this.retail_Sale;
            priceBatchDetail.Discountable = this.discountable;
            priceBatchDetail.Food_Stamps = this.food_Stamps;
            priceBatchDetail.IBM_Discount = this.iBM_Discount;
            priceBatchDetail.Hobart_Item = this.hobart_Item;
            priceBatchDetail.PrintSign = this.printSign;
            priceBatchDetail.LineDrive = this.lineDrive;
            priceBatchDetail.POSPrice = this.pOSPrice;
            priceBatchDetail.POSSale_Price = this.pOSSale_Price;
            priceBatchDetail.Offer_ID = this.offer_ID;
            priceBatchDetail.AvgCostUpdated = this.avgCostUpdated;
            priceBatchDetail.NotAuthorizedForSale = this.notAuthorizedForSale;
            priceBatchDetail.Deleted_Item = this.deleted_Item;
            priceBatchDetail.User_ID = this.user_ID;
            priceBatchDetail.User_ID_Date = this.user_ID_Date;
            priceBatchDetail.LabelType_ID = this.labelType_ID;
            priceBatchDetail.Insert_Date = this.insert_Date;
            priceBatchDetail.OfferChgTypeID = this.offerChgTypeID;
            priceBatchDetail.QtyProhibit = this.qtyProhibit;
            priceBatchDetail.GroupList = this.groupList;
            priceBatchDetail.PosTare = this.posTare;
            priceBatchDetail.LinkedItem = this.linkedItem;
            priceBatchDetail.GrillPrint = this.grillPrint;
            priceBatchDetail.AgeCode = this.ageCode;
            priceBatchDetail.VisualVerify = this.visualVerify;
            priceBatchDetail.SrCitizenDiscount = this.srCitizenDiscount;
            priceBatchDetail.AsOfDate = this.asOfDate;
            priceBatchDetail.AutoGenerated = this.autoGenerated;
            priceBatchDetail.Expired = this.expired;
            priceBatchDetail.POSLinkCode = this.pOSLinkCode;
            priceBatchDetail.InsertApplication = this.insertApplication;
            priceBatchDetail.RetailUnit_WeightUnit = this.retailUnit_WeightUnit;
            priceBatchDetail.TagTypeID = this.tagTypeID;
            priceBatchDetail.TagTypeID2 = this.tagTypeID2;
            priceBatchDetail.EndedEarly = this.endedEarly;
            priceBatchDetail.MixMatch = this.mixMatch;
            priceBatchDetail.PurchaseThresholdCouponAmount = this.purchaseThresholdCouponAmount;
            priceBatchDetail.PurchaseThresholdCouponSubTeam = this.purchaseThresholdCouponSubTeam;
            priceBatchDetail.ReAuthFlag = this.reAuthFlag;
            priceBatchDetail.Retail_Unit_ID = this.retail_Unit_ID;
            priceBatchDetail.Package_Unit_ID = this.package_Unit_ID;
            priceBatchDetail.Item_Description = this.item_Description;
            priceBatchDetail.Case_Discount = this.case_Discount;
            priceBatchDetail.Coupon_Multiplier = this.coupon_Multiplier;
            priceBatchDetail.Misc_Transaction_Sale = this.misc_Transaction_Sale;
            priceBatchDetail.Misc_Transaction_Refund = this.misc_Transaction_Refund;
            priceBatchDetail.Recall_Flag = this.recall_Flag;
            priceBatchDetail.Ice_Tare = this.ice_Tare;
            priceBatchDetail.Product_Code = this.product_Code;
            priceBatchDetail.Unit_Price_Category = this.unit_Price_Category;
            priceBatchDetail.KitchenRoute_ID = this.kitchenRoute_ID;
            priceBatchDetail.Routing_Priority = this.routing_Priority;
            priceBatchDetail.Consolidate_Price_To_Prev_Item = this.consolidate_Price_To_Prev_Item;
            priceBatchDetail.Print_Condiment_On_Receipt = this.print_Condiment_On_Receipt;
            priceBatchDetail.Age_Restrict = this.age_Restrict;
            priceBatchDetail.SLIMRequestID = this.sLIMRequestID;
            priceBatchDetail.LocalItem = this.localItem;
            priceBatchDetail.FSA_Eligible = this.fSA_Eligible;
            priceBatchDetail.ItemSurcharge = this.itemSurcharge;
            priceBatchDetail.CancelAllSales = this.cancelAllSales;

            return priceBatchDetail;
        }

        public static implicit operator PriceBatchDetail(TestPriceBatchDetailBuilder builder)
        {
            return builder.Build();
        }
    }
}
