'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Misc_UPCCostAudit

    '''<summary>
    '''dteBeginDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteBeginDate As Global.Infragistics.WebUI.WebSchedule.WebDateChooser

    '''<summary>
    '''reqfld_BeginDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqfld_BeginDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rngValid_BeginDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngValid_BeginDate As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''dteEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteEndDate As Global.Infragistics.WebUI.WebSchedule.WebDateChooser

    '''<summary>
    '''reqfld_EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqfld_EndDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rngValid_EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngValid_EndDate As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''cmbTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTeam As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''IC_Team control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IC_Team As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmbSubTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSubTeam As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''IC_SubTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IC_SubTeam As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmbVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbVendor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''IC_Vendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IC_Vendor As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txtIdentifiers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdentifiers As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbReportFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbReportFormat As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''comp_DateRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comp_DateRange As Global.System.Web.UI.WebControls.CompareValidator
End Class
