namespace Mammoth.Esb.ProductListener.Models
{
    public class NutritionAttributesModel
    {
        public int ItemID { get; set; }
        public string RecipeName { get; set; }
        public string Allergens { get; set; }
        public string Ingredients { get; set; }
        public float? ServingsPerPortion { get; set; }
        public string ServingSizeDesc { get; set; }
        public string ServingPerContainer { get; set; }
        public int? HshRating { get; set; }
        public int? ServingUnits { get; set; }
        public int? SizeWeight { get; set; }
        public int? Calories { get; set; }
        public int? CaloriesFat { get; set; }
        public int? CaloriesSaturatedFat { get; set; }
        public decimal? TotalFatWeight { get; set; }
        public int? TotalFatPercentage { get; set; }
        public decimal? SaturatedFatWeight { get; set; }
        public int? SaturatedFatPercent { get; set; }
        public decimal? PolyunsaturatedFat { get; set; }
        public decimal? MonounsaturatedFat { get; set; }
        public decimal? CholesterolWeight { get; set; }
        public int? CholesterolPercent { get; set; }
        public decimal? SodiumWeight { get; set; }
        public int? SodiumPercent { get; set; }
        public decimal? PotassiumWeight { get; set; }
        public int? PotassiumPercent { get; set; }
        public decimal? TotalCarbohydrateWeight { get; set; }
        public int? TotalCarbohydratePercent { get; set; }
        public decimal? DietaryFiberWeight { get; set; }
        public int? DietaryFiberPercent { get; set; }
        public decimal? SolubleFiber { get; set; }
        public decimal? InsolubleFiber { get; set; }
        public decimal? Sugar { get; set; }
        public decimal? SugarAlcohol { get; set; }
        public decimal? OtherCarbohydrates { get; set; }
        public decimal? ProteinWeight { get; set; }
        public int? ProteinPercent { get; set; }
        public int? VitaminA { get; set; }
        public int? Betacarotene { get; set; }
        public int? VitaminC { get; set; }
        public int? Calcium { get; set; }
        public int? Iron { get; set; }
        public int? VitaminD { get; set; }
        public int? VitaminE { get; set; }
        public int? Thiamin { get; set; }
        public int? Riboflavin { get; set; }
        public int? Niacin { get; set; }
        public int? VitaminB6 { get; set; }
        public int? Folate { get; set; }
        public int? VitaminB12 { get; set; }
        public int? Biotin { get; set; }
        public int? PantothenicAcid { get; set; }
        public int? Phosphorous { get; set; }
        public int? Iodine { get; set; }
        public int? Magnesium { get; set; }
        public int? Zinc { get; set; }
        public int? Copper { get; set; }
        public decimal? TransFat { get; set; }
        public decimal? TransFatWeight { get; set; }
        public int? CaloriesFromTransFat { get; set; }
        public decimal? Om6Fatty { get; set; }
        public decimal? Om3Fatty { get; set; }
        public decimal? Starch { get; set; }
        public int? Chloride { get; set; }
        public int? Chromium { get; set; }
        public int? VitaminK { get; set; }
        public int? Manganese { get; set; }
        public int? Molybdenum { get; set; }
        public int? Selenium { get; set; }
        public decimal? AddedSugarsWeight { get; set; }
        public int? AddedSugarsPercent { get; set; }
        public decimal? CalciumWeight { get; set; }
        public decimal? IronWeight { get; set; }
        public decimal? VitaminDWeight { get; set; }
        public int? ProfitCenter { get; set; }
        public string CanadaAllergens { get; set; }
        public string CanadaIngredients { get; set; }
        public int? CanadaSugarPercent { get; set; }
    }
}
