CREATE TABLE [icon].[ItemSignAttribute] (
    [ItemSignAttributeID]    INT NOT NULL,
    [ItemID]                 INT NOT NULL,
    [AnimalWelfareRatingId]  INT NULL,
    [Biodynamic]             BIT NULL,
    [CheeseMilkTypeId]       INT NULL,
    [CheeseRaw]              BIT NULL,
    [EcoScaleRatingId]       INT NULL,
    [GlutenFreeAgencyId]     INT NULL,
    [HealthyEatingRatingId]  INT NULL,
    [KosherAgencyId]         INT NULL,
    [Msc]                    BIT NULL,
    [NonGmoAgencyId]         INT NULL,
    [OrganicAgencyId]        INT NULL,
    [PremiumBodyCare]        BIT NULL,
    [SeafoodFreshOrFrozenId] INT NULL,
    [SeafoodCatchTypeId]     INT NULL,
    [VeganAgencyId]          INT NULL,
    [Vegetarian]             BIT NULL,
    [WholeTrade]             BIT NULL,
    [GrassFed]               BIT NULL,
    [PastureRaised]          BIT NULL,
    [FreeRange]              BIT NULL,
    [DryAged]                BIT NULL,
    [AirChilled]             BIT NULL,
    [MadeInHouse]            BIT NULL,
    CONSTRAINT [PK_ItemSignAttribute] PRIMARY KEY CLUSTERED ([ItemSignAttributeID] ASC) WITH (FILLFACTOR = 100)
);

