<?xml version="1.0" encoding="utf-8"?><Database Name="ItemCatalog_Test" Class="IRMAUserAuditConsoleDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=idt-mw\mwt;Initial Catalog=ItemCatalog_Test;Integrated Security=True" SettingsObjectName="IRMAUserAuditConsole.Properties.Settings" SettingsPropertyName="ItemCatalog_TestConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Store" Member="Stores">
    <Type Name="Store">
      <Column Name="Store_No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Store_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone_Number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Mega_Store" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Distribution_Center" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Manufacturer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WFM_Store" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Internal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TelnetUser" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="TelnetPassword" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="BatchID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BatchRecords" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BusinessUnit_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Zone_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UNFI_Store" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="LastRecvLogDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastRecvLog_No" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RecvLogUser_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EXEWarehouse" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Regional" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastSalesUpdateDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="StoreAbbr" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="PLUMStoreNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaxJurisdictionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="POSSystemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSI_Store_No" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StoreJurisdictionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseAvgCostHistory" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GeoCode" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="Store_UserStoreTeamTitle" Member="UserStoreTeamTitles" ThisKey="Store_No" OtherKey="Store_No" Type="UserStoreTeamTitle" />
      <Association Name="Store_User" Member="Users1" ThisKey="Store_No" OtherKey="Telxon_Store_Limit" Type="User" />
      <Association Name="Store_User1" Member="Users" ThisKey="Store_No" OtherKey="Telxon_Store_Limit" Type="User" />
      <Association Name="User_Store" Member="User" ThisKey="RecvLogUser_ID" OtherKey="User_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Title" Member="Titles">
    <Type Name="Title">
      <Column Name="Title_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title_Desc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Title_TitleDefaultPermission" Member="TitleDefaultPermissions" ThisKey="Title_ID" OtherKey="TitleId" Type="TitleDefaultPermission" />
      <Association Name="Title_UserStoreTeamTitle" Member="UserStoreTeamTitles" ThisKey="Title_ID" OtherKey="Title_ID" Type="UserStoreTeamTitle" />
      <Association Name="Title_User" Member="Users" ThisKey="Title_ID" OtherKey="Title" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.TitlePermissionOverride" Member="TitlePermissionOverrides">
    <Type Name="TitlePermissionOverride">
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PermissionName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PermissionValue" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Shrink" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShrinkAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_TitlePermissionOverride" Member="User" ThisKey="UserId" OtherKey="User_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TitleDefaultPermission" Member="TitleDefaultPermissions">
    <Type Name="TitleDefaultPermission">
      <Column Name="TitleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Accountant" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BatchBuildOnly" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Buyer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Coordinator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CostAdministrator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FacilityCreditProcessor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DCAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EInvoicing" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InventoryAdministrator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ItemAdministrator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LockAdministrator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="POAccountant" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="POApprovalAdministrator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PriceBatchProcessor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Distributor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SuperUser" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VendorAdministrator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VendorCostDiscrepancyAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Warehouse" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ApplicationConfigAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DataAdministrator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="JobAdministrator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="POSInterfaceAdministrator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SecurityAdministrator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StoreAdministrator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SystemConfigurationAdministrator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserMaintenance" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Shrink" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShrinkAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="POEditor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletePO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TaxAdministrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Title_TitleDefaultPermission" Member="Title" ThisKey="TitleId" OtherKey="Title_ID" Type="Title" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Team" Member="Teams">
    <Type Name="Team">
      <Column Name="Team_No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Team_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Team_Abbreviation" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Team_UserStoreTeamTitle" Member="UserStoreTeamTitles" ThisKey="Team_No" OtherKey="Team_No" Type="UserStoreTeamTitle" />
    </Type>
  </Table>
  <Table Name="dbo.UserStoreTeamTitle" Member="UserStoreTeamTitles">
    <Type Name="UserStoreTeamTitle">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Store_No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Team_No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Store_UserStoreTeamTitle" Member="Store" ThisKey="Store_No" OtherKey="Store_No" Type="Store" IsForeignKey="true" />
      <Association Name="Team_UserStoreTeamTitle" Member="Team" ThisKey="Team_No" OtherKey="Team_No" Type="Team" IsForeignKey="true" />
      <Association Name="Title_UserStoreTeamTitle" Member="Title" ThisKey="Title_ID" OtherKey="Title_ID" Type="Title" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SlimAccess" Member="SlimAccesses">
    <Type Name="SlimAccess">
      <Column Name="SlimAccess_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ItemRequest" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VendorRequest" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IRMAPush" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StoreSpecials" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RetailCost" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Authorizations" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="WebQuery" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Insert_Date" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ScaleInfo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Printer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CoverPage" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EMail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pager_Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fax_Number" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="AccountEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SuperUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PO_Accountant" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Accountant" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Distributor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FacilityCreditProcessor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Buyer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Coordinator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Item_Administrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Vendor_Administrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Lock_Administrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Telxon_Store_Limit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone_Number" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Title" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RecvLog_Store_Limit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Warehouse" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PriceBatchProcessor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Inventory_Administrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BatchBuildOnly" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DCAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PromoAccessLevel" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CostAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="POApprovalAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EInvoicing_Administrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="VendorCostDiscrepancyAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationConfigAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DataAdministrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="JobAdministrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="POSInterfaceAdministrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SecurityAdministrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="StoreAdministrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SystemConfigurationAdministrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserMaintenance" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Shrink" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShrinkAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="POEditor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletePO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TaxAdministrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_Store" Member="Stores" ThisKey="User_ID" OtherKey="RecvLogUser_ID" Type="Store" />
      <Association Name="User_TitlePermissionOverride" Member="TitlePermissionOverrides" ThisKey="User_ID" OtherKey="UserId" Type="TitlePermissionOverride" />
      <Association Name="User_AppConfigApp" Member="AppConfigApps" ThisKey="User_ID" OtherKey="LastUpdateUserID" Type="AppConfigApp" />
      <Association Name="User_AppConfigEnv" Member="AppConfigEnvs" ThisKey="User_ID" OtherKey="LastUpdateUserID" Type="AppConfigEnv" />
      <Association Name="Store_User" Member="Store1" ThisKey="Telxon_Store_Limit" OtherKey="Store_No" Type="Store" IsForeignKey="true" />
      <Association Name="Store_User1" Member="Store" ThisKey="Telxon_Store_Limit" OtherKey="Store_No" Type="Store" IsForeignKey="true" />
      <Association Name="Title_User" Member="Title1" ThisKey="Title" OtherKey="Title_ID" Type="Title" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsersHistory" Member="UsersHistories">
    <Type Name="UsersHistory">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Printer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CoverPage" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EMail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pager_Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fax_Number" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="AccountEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SuperUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PO_Accountant" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Accountant" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Distributor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FacilityCreditProcessor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Buyer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Coordinator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Item_Administrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Vendor_Administrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Lock_Administrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Telxon_Store_Limit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone_Number" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="RecvLog_Store_Limit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Warehouse" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Effective_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HOST_NAME" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PriceBatchProcessor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Inventory_Administrator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BatchBuildOnly" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DCAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PromoAccessLevel" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CostAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="VendorCostDiscrepancyAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="POApprovalAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AppConfigApp" Member="AppConfigApps">
    <Type Name="AppConfigApp">
      <Column Name="ApplicationID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EnvironmentID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Configuration" Type="System.Xml.Linq.XElement" DbType="Xml NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdateUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_AppConfigApp" Member="User" ThisKey="LastUpdateUserID" OtherKey="User_ID" Type="User" IsForeignKey="true" />
      <Association Name="AppConfigEnv_AppConfigApp" Member="AppConfigEnv" ThisKey="EnvironmentID" OtherKey="EnvironmentID" Type="AppConfigEnv" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AppConfigEnv" Member="AppConfigEnvs">
    <Type Name="AppConfigEnv">
      <Column Name="EnvironmentID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdateUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AppConfigEnv_AppConfigApp" Member="AppConfigApps" ThisKey="EnvironmentID" OtherKey="EnvironmentID" Type="AppConfigApp" />
      <Association Name="User_AppConfigEnv" Member="User" ThisKey="LastUpdateUserID" OtherKey="User_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.Administration_UserAdmin_DeleteUser" Method="Administration_UserAdmin_DeleteUser">
    <Parameter Name="User_Id" Parameter="user_Id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Administration_UserAdmin_UpdateUser" Method="Administration_UserAdmin_UpdateUser">
    <Parameter Name="AccountEnabled" Parameter="accountEnabled" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CoverPage" Parameter="coverPage" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="EMail" Parameter="eMail" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Fax_Number" Parameter="fax_Number" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="FullName" Parameter="fullName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pager_Email" Parameter="pager_Email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Phone_Number" Parameter="phone_Number" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="Printer" Parameter="printer" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RecvLog_Store_Limit" Parameter="recvLog_Store_Limit" Type="System.Int32" DbType="Int" />
    <Parameter Name="Telxon_Store_Limit" Parameter="telxon_Store_Limit" Type="System.Int32" DbType="Int" />
    <Parameter Name="Title" Parameter="title" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_Id" Parameter="user_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="Accountant" Parameter="accountant" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ApplicationConfigAdmin" Parameter="applicationConfigAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="BatchBuildOnly" Parameter="batchBuildOnly" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Buyer" Parameter="buyer" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Coordinator" Parameter="coordinator" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CostAdmin" Parameter="costAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FacilityCreditProcessor" Parameter="facilityCreditProcessor" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="DataAdministrator" Parameter="dataAdministrator" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="DCAdmin" Parameter="dCAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Distributor" Parameter="distributor" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="DeletePO" Parameter="deletePO" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EInvoicingAdmin" Parameter="eInvoicingAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Inventory_Administrator" Parameter="inventory_Administrator" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Item_Administrator" Parameter="item_Administrator" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="JobAdministrator" Parameter="jobAdministrator" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Lock_Administrator" Parameter="lock_Administrator" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SuperUser" Parameter="superUser" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PO_Accountant" Parameter="pO_Accountant" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="POApprovalAdmin" Parameter="pOApprovalAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="POEditor" Parameter="pOEditor" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="POSInterfaceAdministrator" Parameter="pOSInterfaceAdministrator" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PriceBatchProcessor" Parameter="priceBatchProcessor" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PromoAccessLevel" Parameter="promoAccessLevel" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="SecurityAdministrator" Parameter="securityAdministrator" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Shrink" Parameter="shrink" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ShrinkAdmin" Parameter="shrinkAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="StoreAdministrator" Parameter="storeAdministrator" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SystemConfigurationAdministrator" Parameter="systemConfigurationAdministrator" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="TaxAdministrator" Parameter="taxAdministrator" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserMaintenance" Parameter="userMaintenance" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Vendor_Administrator" Parameter="vendor_Administrator" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="VendorCostDiscrepancyAdmin" Parameter="vendorCostDiscrepancyAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Warehouse" Parameter="warehouse" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Authorizations" Parameter="authorizations" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IRMAPush" Parameter="iRMAPush" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ItemRequest" Parameter="itemRequest" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="RetailCost" Parameter="retailCost" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ScaleInfo" Parameter="scaleInfo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="StoreSpecials" Parameter="storeSpecials" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserAdmin" Parameter="userAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="VendorRequest" Parameter="vendorRequest" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="WebQuery" Parameter="webQuery" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetStoreList" Method="GetStoreList">
    <ElementType Name="GetStoreListResult">
      <Column Name="Store_No" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Store_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetConfigurationData" Method="GetConfigurationData">
    <ElementType Name="GetConfigurationDataResult">
      <Column Name="ConfigKey" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ConfigValue" Type="System.Object" DbType="Variant" CanBeNull="true" />
      <Column Name="BaseType" Type="System.Object" DbType="Variant" CanBeNull="true" />
      <Column Name="Precision" Type="System.Object" DbType="Variant" CanBeNull="true" />
      <Column Name="Scale" Type="System.Object" DbType="Variant" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetConfigurationValue" Method="GetConfigurationValue">
    <Parameter Name="iConfigKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="GetConfigurationValueResult">
      <Column Name="" Member="Column1" Type="System.Object" DbType="Variant" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>