'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace pp_irma

    Partial Public Class index

        '''<summary>
        '''dept control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dept As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''buildPromo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents buildPromo As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkUploadPromos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkUploadPromos As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dates As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''revPromos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revPromos As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''orddates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents orddates As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''getOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents getOrders As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dates2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dates2 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''revPromos2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents revPromos2 As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
