create table [nutrition].ItemNutrition
(
	RecipeId					int identity(1,1) not null,
	Plu							varchar(50) null,
	RecipeName					nvarchar(100) null,
	Allergens					nvarchar(510) null,
	Ingredients					nvarchar(4000) null,
	ServingsPerPortion			float null,
	ServingSizeDesc				nvarchar(50) null,
	ServingPerContainer			nvarchar(50) null,
	HshRating					int null,
	ServingUnits				tinyint null,
	SizeWeight					int null,
	Calories					int null,
	CaloriesFat					int null,
	CaloriesSaturatedFat		int null,
	TotalFatWeight				decimal(10,1) null,
	TotalFatPercentage			smallint null,
	SaturatedFatWeight			decimal(10,1) null,
	SaturatedFatPercent			smallint null,
	PolyunsaturatedFat			decimal(10,1) null,
	MonounsaturatedFat			decimal(10,1) null,
	CholesterolWeight			decimal(10,1) null,
	CholesterolPercent			smallint null,
	SodiumWeight				decimal(10,1) null,
	SodiumPercent				smallint null,
	PotassiumWeight				decimal(10,1) null,
	PotassiumPercent			smallint null,
	TotalCarbohydrateWeight		decimal(10,1) null,
	TotalCarbohydratePercent	smallint null,
	DietaryFiberWeight			decimal(10,1) null,
	DietaryFiberPercent			smallint null,
	SolubleFiber				decimal(10,1) null,
	InsolubleFiber				decimal(10,1) null,
	Sugar						decimal(10,1) null,
	SugarAlcohol				decimal(10,1) null,
	OtherCarbohydrates			decimal(10,1) null,
	ProteinWeight				decimal(10,1) null,
	ProteinPercent				smallint null,
	VitaminA					smallint null,
	Betacarotene				smallint null,
	VitaminC					smallint null,
	Calcium						smallint null,
	Iron						smallint null,
	VitaminD					smallint null,
	VitaminE					smallint null,
	Thiamin						smallint null,
	Riboflavin					smallint null,
	Niacin						smallint null,
	VitaminB6					smallint null,
	Folate						smallint null,
	VitaminB12					smallint null,
	Biotin						smallint null,
	PantothenicAcid				smallint null,
	Phosphorous					smallint null,
	Iodine						smallint null,
	Magnesium					smallint null,
	Zinc						smallint null,
	Copper						smallint null,
	Transfat					decimal(10,1) null,
	CaloriesFromTransfat		int null,
	Om6Fatty					decimal(10,1) null,
	Om3Fatty					decimal(10,1) null,
	Starch						decimal(10,1) null,
	Chloride					smallint null,
	Chromium					smallint null,
	VitaminK					smallint null,
	Manganese					smallint null,
	Molybdenum					smallint null,
	Selenium					smallint null,
	TransfatWeight				decimal(10,1) null,
	InsertDate					datetime2(7) not null default sysdatetime(),
	ModifiedDate				datetime2(7) null,
	constraint [PK_nutrition.ItemNutrition] primary key clustered ([RecipeId])
)

GO

CREATE INDEX [ItemNutrition_Plu_Idx] ON [nutrition].[ItemNutrition] ([Plu]) 
GO