'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5456.
'
Namespace quiver_tst
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="VimLookupSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class VimLookup
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://quiver-tst:3215/VimLookup.asmx"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllRegions", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAllRegions() As String()
            Dim results() As Object = Me.Invoke("GetAllRegions", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Function BeginGetAllRegions(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAllRegions", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetAllRegions(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllStoreAbbrs", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAllStoreAbbrs() As String()
            Dim results() As Object = Me.Invoke("GetAllStoreAbbrs", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Function BeginGetAllStoreAbbrs(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAllStoreAbbrs", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetAllStoreAbbrs(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStoreRegion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStoreRegion(ByVal store As String) As String
            Dim results() As Object = Me.Invoke("GetStoreRegion", New Object() {store})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetStoreRegion(ByVal store As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetStoreRegion", New Object() {store}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetStoreRegion(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartment", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDepartment(ByVal upc As String, ByVal storeabbr As String) As String
            Dim results() As Object = Me.Invoke("GetDepartment", New Object() {upc, storeabbr})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetDepartment(ByVal upc As String, ByVal storeabbr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetDepartment", New Object() {upc, storeabbr}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetDepartment(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTeam", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTeam(ByVal upc As String, ByVal storeabbr As String) As vimTeam()
            Dim results() As Object = Me.Invoke("GetTeam", New Object() {upc, storeabbr})
            Return CType(results(0),vimTeam())
        End Function
        
        '''<remarks/>
        Public Function BeginGetTeam(ByVal upc As String, ByVal storeabbr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTeam", New Object() {upc, storeabbr}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetTeam(ByVal asyncResult As System.IAsyncResult) As vimTeam()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),vimTeam())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCategory", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCategory(ByVal upc As String) As String
            Dim results() As Object = Me.Invoke("GetCategory", New Object() {upc})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetCategory(ByVal upc As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetCategory", New Object() {upc}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetCategory(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllStoreAbbrsByRegion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAllStoreAbbrsByRegion(ByVal region As String) As String()
            Dim results() As Object = Me.Invoke("GetAllStoreAbbrsByRegion", New Object() {region})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Function BeginGetAllStoreAbbrsByRegion(ByVal region As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAllStoreAbbrsByRegion", New Object() {region}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetAllStoreAbbrsByRegion(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllStoreNames", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAllStoreNames() As String()
            Dim results() As Object = Me.Invoke("GetAllStoreNames", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Function BeginGetAllStoreNames(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAllStoreNames", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetAllStoreNames(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllStoreNamesByRegion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAllStoreNamesByRegion(ByVal region As String) As String()
            Dim results() As Object = Me.Invoke("GetAllStoreNamesByRegion", New Object() {region})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Function BeginGetAllStoreNamesByRegion(ByVal region As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAllStoreNamesByRegion", New Object() {region}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetAllStoreNamesByRegion(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductByUPC", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProductByUPC(ByVal upc As String) As vimProduct()
            Dim results() As Object = Me.Invoke("GetProductByUPC", New Object() {upc})
            Return CType(results(0),vimProduct())
        End Function
        
        '''<remarks/>
        Public Function BeginGetProductByUPC(ByVal upc As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetProductByUPC", New Object() {upc}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetProductByUPC(ByVal asyncResult As System.IAsyncResult) As vimProduct()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),vimProduct())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductBySearchingVIM", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProductBySearchingVIM(ByVal searchstr As String) As vimProduct()
            Dim results() As Object = Me.Invoke("GetProductBySearchingVIM", New Object() {searchstr})
            Return CType(results(0),vimProduct())
        End Function
        
        '''<remarks/>
        Public Function BeginGetProductBySearchingVIM(ByVal searchstr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetProductBySearchingVIM", New Object() {searchstr}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetProductBySearchingVIM(ByVal asyncResult As System.IAsyncResult) As vimProduct()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),vimProduct())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVendorDetails", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetVendorDetails(ByVal UPC As String, ByVal Store As String) As vimVendor()
            Dim results() As Object = Me.Invoke("GetVendorDetails", New Object() {UPC, Store})
            Return CType(results(0),vimVendor())
        End Function
        
        '''<remarks/>
        Public Function BeginGetVendorDetails(ByVal UPC As String, ByVal Store As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetVendorDetails", New Object() {UPC, Store}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetVendorDetails(ByVal asyncResult As System.IAsyncResult) As vimVendor()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),vimVendor())
        End Function
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class vimTeam
        
        '''<remarks/>
        Public Team_Name As String
        
        '''<remarks/>
        Public Subteam_Name As String
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class vimVendor
        
        '''<remarks/>
        Public VENDOR_KEY As String
        
        '''<remarks/>
        Public VEND_ITEM_NUM As String
        
        '''<remarks/>
        Public VENDOR_ID As String
        
        '''<remarks/>
        Public COMPANY_NAME As String
        
        '''<remarks/>
        Public ADDRESS_LINE_1 As String
        
        '''<remarks/>
        Public ADDRESS_LINE_2 As String
        
        '''<remarks/>
        Public CITY As String
        
        '''<remarks/>
        Public STATE As String
        
        '''<remarks/>
        Public ZIP_CODE As String
        
        '''<remarks/>
        Public COUNTRY As String
        
        '''<remarks/>
        Public PHONE As String
        
        '''<remarks/>
        Public FAX As String
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class vimProduct
        
        '''<remarks/>
        Public UPC As String
        
        '''<remarks/>
        Public Brand As String
        
        '''<remarks/>
        Public BrandName As String
        
        '''<remarks/>
        Public ProductName As String
        
        '''<remarks/>
        Public LotCode As String
        
        '''<remarks/>
        Public BestByDate As String
    End Class
End Namespace
