CREATE TABLE [esb].[MessageQueuePrice]
(
    [MessageQueueId]	INT				IDENTITY (1, 1) NOT NULL,
    [MessageTypeId]		INT				NOT NULL,
    [MessageStatusId]	INT				NOT NULL,
    [MessageHistoryId]	INT				NULL,
    [MessageActionId]	INT				NOT NULL,
    [InsertDate]		DATETIME2 (7)  CONSTRAINT [DF_MessageQueuePrice_InsertDate] DEFAULT (sysdatetime()) NOT NULL,
	[ItemId]			INT				NOT NULL,
	[ItemTypeCode]		NVARCHAR(3)		NOT NULL,
	[ItemTypeDesc]		NVARCHAR(255)	NOT NULL,
	[BusinessUnitId]	INT				NOT NULL,
	[LocaleName]		NVARCHAR(255)	NOT NULL,
	[ScanCode]			NVARCHAR(13)	NOT NULL,
	[UomCode]			NVARCHAR(3)		NOT NULL,
	[CurrencyCode]		NVARCHAR(3)		NOT NULL,
	[PriceTypeCode]		NVARCHAR(3)		NOT NULL,
	[SubPriceTypeCode]	NVARCHAR(3)		NULL,
	[Price]				MONEY			NOT NULL,
	[Multiple]			INT				NOT NULL,
	[StartDate]			DATETIME2(7)	NOT NULL,
	[EndDate]			DATETIME2(7)	NULL,	
	[InProcessBy]		INT				NULL,
    [ProcessedDate]		DATETIME2 (7)	NULL,
    CONSTRAINT [PK_MessageQueuePrice] PRIMARY KEY CLUSTERED ([MessageQueueId] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_MessageQueuePrice_MessageActionId] FOREIGN KEY ([MessageActionId]) REFERENCES [esb].[MessageAction] ([MessageActionId]),
    CONSTRAINT [FK_MessageQueuePrice_MessageHistoryId] FOREIGN KEY ([MessageHistoryId]) REFERENCES [esb].[MessageHistory] ([MessageHistoryId]) ON DELETE CASCADE,
    CONSTRAINT [FK_MessageQueuePrice_MessageStatusId] FOREIGN KEY ([MessageStatusId]) REFERENCES [esb].[MessageStatus] ([MessageStatusId]),
    CONSTRAINT [FK_MessageQueuePrice_MessageTypeId] FOREIGN KEY ([MessageTypeId]) REFERENCES [esb].[MessageType] ([MessageTypeId])
)
