IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Conversion_AddItemsFromPrep]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Conversion_AddItemsFromPrep]
GO
CREATE   PROCEDURE [dbo].[Conversion_AddItemsFromPrep]  AS
BEGIN
declare 
	@Item_Key int,
	@Item_Description char(30),
	@Sign_Description varchar(50),
	@Ingredients varchar(3000),
	@SubTeam_No char(4),
	@Sales_Account int,
	@Package_Desc1 decimal(9,4),
	@Package_Desc2 decimal(9,4),
	@Package_Unit_ID int,
	@Min_Temperature int,
	@Max_Temperature int,
	@Units_Per_Pallet int,
	@Average_Unit_Weight int,
	@Tie int,
	@High int,
	@Yield int,
	@Brand_ID int,
	@Category_ID int,
	@Origin_ID int,
	@ShelfLife_Id int,
	@ShelfLife_Length smallint,
	@Retail_Unit_ID int,
	@Vendor_Unit_ID int,
	@Distribution_Unit_ID int,
	@Deleted_Item int,
	@WFM_Item int,
	@Not_Available int,
	@Pre_Order int,
	@Remove_Item int,
	@NoDistMarkup int,
	@Organic int,
	@Refrigerated int,
	@Keep_Frozen int,
	@Shipper_Item int,
	@Full_Pallet_Only int,
	@User_ID int,
	@POS_Description char(25),
	@Retail_Sale int,
	@Food_Stamps int,
--	@Discountable int,
	@Price_Required int,
	@Quantity_Required int,
	@ItemType_ID int,
	@HFM_Item int,
	@ScaleDesc1 char(32),
	@ScaleDesc2 char(32),
	@Not_AvailableNote int,
	@CountryProc_ID int,
	@Insert_Date datetime,
	@Manufacturing_Unit_ID int,
	@EXEDistributed int,
	@ClassID int,
	@User_ID_Date int,
	@DistSubTeam_No int,
	@CostedByWeight int,
	@TaxClassID int,
	@LabelType_ID int,
	@ScaleDesc3 char(32),
	@ScaleDesc4 char(32),
	@ScaleTare smallint,
	@ScaleUseBy int,
	@ScaleForcedTare char(1),
	@QtyProhibit int,
	@GroupList smallint,
	@Recall_Flag bit,
	@LockAuth bit,
	@Identifier varchar(12),
	@CheckDigit char(1),
	@sku_number char(12),
	@IdentifierType char(1),
	@National_Identifier bit,
	@Scale_Identifier bit,
	@NumPluDigitsSentToScale smallint,
	@upcno char(13)

SET NOCOUNT ON

declare @CrsrVar Cursor

set @CrsrVar = Cursor for
	select 
		Item_Key,
		Item_Description,
		Sign_Description,
		Ingredients,
		SubTeam_No,
		Sales_Account,
		Package_Desc1,
		Package_Desc2,
		Package_Unit_ID,
		Min_Temperature,
		Max_Temperature,
		Units_Per_Pallet,
		Average_Unit_Weight,
		Tie,
		High,
		Yield,
		Brand_ID,
		Category_ID,
		Origin_ID,
		ShelfLife_Id,
		ShelfLife_Length,
		Retail_Unit_ID,
		Vendor_Unit_ID,
		Distribution_Unit_ID,
		Deleted_Item,
		WFM_Item,
		Not_Available,
		Pre_Order,
		Remove_Item,
		NoDistMarkup,
		Organic,
		Refrigerated,
		Keep_Frozen,
		Shipper_Item,
		Full_Pallet_Only,
		User_ID,
		POS_Description,
		Retail_Sale,
		Food_Stamps,
--		Discountable,
		Price_Required,
		Quantity_Required,
		ItemType_ID,
		HFM_Item,
		ScaleDesc1,
		ScaleDesc2,
		Not_AvailableNote,
		CountryProc_ID,
		Insert_Date,
		Manufacturing_Unit_ID,
		EXEDistributed,
		ClassID,
		User_ID_Date,
		DistSubTeam_No,
		CostedByWeight,
		TaxClassID,
		LabelType_ID,
		ScaleDesc3,
		ScaleDesc4,
		ScaleTare,
		ScaleUseBy,
		ScaleForcedTare,
		QtyProhibit,
		GroupList,
		Recall_Flag,
		LockAuth,
		Identifier,
		CheckDigit,
		sku_number,
		National_Identifier,
		IdentifierType,
		Scale_Identifier,
		NumPluDigitsSentToScale,
		upcno
	from Item_Prep 
	where Item_Key = 0
	  and (		SameChain != 1
			or	Chain_Code = upcno) -- If it's a "same chain", only take the primary member

open @CrsrVar

Fetch Next from @CrsrVar Into 
	@Item_Key,
	@Item_Description,
	@Sign_Description,
	@Ingredients,
	@SubTeam_No,
	@Sales_Account,
	@Package_Desc1,
	@Package_Desc2,
	@Package_Unit_ID,
	@Min_Temperature,
	@Max_Temperature,
	@Units_Per_Pallet,
	@Average_Unit_Weight,
	@Tie,
	@High,
	@Yield,
	@Brand_ID,
	@Category_ID,
	@Origin_ID,
	@ShelfLife_Id,
	@ShelfLife_Length,
	@Retail_Unit_ID,
	@Vendor_Unit_ID,
	@Distribution_Unit_ID,
	@Deleted_Item,
	@WFM_Item,
	@Not_Available,
	@Pre_Order,
	@Remove_Item,
	@NoDistMarkup,
	@Organic,
	@Refrigerated,
	@Keep_Frozen,
	@Shipper_Item,
	@Full_Pallet_Only,
	@User_ID,
	@POS_Description,
	@Retail_Sale,
	@Food_Stamps,
--	@Discountable,
	@Price_Required,
	@Quantity_Required,
	@ItemType_ID,
	@HFM_Item,
	@ScaleDesc1,
	@ScaleDesc2,
	@Not_AvailableNote,
	@CountryProc_ID,
	@Insert_Date,
	@Manufacturing_Unit_ID,
	@EXEDistributed,
	@ClassID,
	@User_ID_Date,
	@DistSubTeam_No,
	@CostedByWeight,
	@TaxClassID,
	@LabelType_ID,
	@ScaleDesc3,
	@ScaleDesc4,
	@ScaleTare,
	@ScaleUseBy,
	@ScaleForcedTare,
	@QtyProhibit,
	@GroupList,
	@Recall_Flag,
	@LockAuth,
	@Identifier,
	@CheckDigit,
	@sku_number,
	@National_Identifier,
	@IdentifierType,
	@Scale_Identifier,
	@NumPluDigitsSentToScale,
	@upcno

while (@@FETCH_STATUS = 0)

begin

	Insert into Item(
		Item_Description,
		Sign_Description,
		Ingredients,
		SubTeam_No,
		Sales_Account,
		Package_Desc1,
		Package_Desc2,
		Package_Unit_ID,
		Min_Temperature,
		Max_Temperature,
		Units_Per_Pallet,
		Average_Unit_Weight,
		Tie,
		High,
		Yield,
		Brand_ID,
		Category_ID,
		Origin_ID,
		ShelfLife_Id,
		ShelfLife_Length,
		Retail_Unit_ID,
		Vendor_Unit_ID,
		Distribution_Unit_ID,
		Deleted_Item,
		WFM_Item,
		Not_Available,
		Pre_Order,
		Remove_Item,
		NoDistMarkup,
		Organic,
		Refrigerated,
		Keep_Frozen,
		Shipper_Item,
		Full_Pallet_Only,
		User_ID,
		POS_Description,
		Retail_Sale,
		Food_Stamps,
--		Discountable,
		Price_Required,
		Quantity_Required,
		ItemType_ID,
		HFM_Item,
		ScaleDesc1,
		ScaleDesc2,
		Not_AvailableNote,
		CountryProc_ID,
		Insert_Date,
		Manufacturing_Unit_ID,
		EXEDistributed,
		ClassID,
		User_ID_Date,
		DistSubTeam_No,
		CostedByWeight,
		TaxClassID,
		LabelType_ID,
		ScaleDesc3,
		ScaleDesc4,
		ScaleTare,
		ScaleUseBy,
		ScaleForcedTare,
		QtyProhibit,
		GroupList,
		Recall_Flag,
		LockAuth)
	values (
		@Item_Description,
		@Sign_Description,
		@Ingredients,
		@SubTeam_No,
		@Sales_Account,
		@Package_Desc1,
		@Package_Desc2,
		@Package_Unit_ID,
		@Min_Temperature,
		@Max_Temperature,
		@Units_Per_Pallet,
		@Average_Unit_Weight,
		@Tie,
		@High,
		@Yield,
		@Brand_ID,
		@Category_ID,
		@Origin_ID,
		@ShelfLife_Id,
		@ShelfLife_Length,
		@Retail_Unit_ID,
		@Vendor_Unit_ID,
		@Distribution_Unit_ID,
		@Deleted_Item,
		@WFM_Item,
		@Not_Available,
		@Pre_Order,
		@Remove_Item,
		@NoDistMarkup,
		@Organic,
		@Refrigerated,
		@Keep_Frozen,
		@Shipper_Item,
		@Full_Pallet_Only,
		@User_ID,
		@POS_Description,
		@Retail_Sale,
		@Food_Stamps,
--		@Discountable,
		@Price_Required,
		@Quantity_Required,
		@ItemType_ID,
		@HFM_Item,
		@ScaleDesc1,
		@ScaleDesc2,
		@Not_AvailableNote,
		@CountryProc_ID,
		@Insert_Date,
		@Manufacturing_Unit_ID,
		@EXEDistributed,
		@ClassID,
		@User_ID_Date,
		@DistSubTeam_No,
		@CostedByWeight,
		@TaxClassID,
		@LabelType_ID,
		@ScaleDesc3,
		@ScaleDesc4,
		@ScaleTare,
		@ScaleUseBy,
		@ScaleForcedTare,
		@QtyProhibit,
		@GroupList,
		@Recall_Flag,
		@LockAuth)

	if @@error <> 0 
		BEGIN
			PRINT 'Error Occured: Could not insert into item, upcno:'+ CAST(@upcno AS VARCHAR) 
		END	
	else
		BEGIN
		set @Item_Key = SCOPE_IDENTITY()

		insert into iriskeytoirmakey (item_key, iris_prod_code) 
		values (@Item_Key, @upcno)
		if @@error <> 0 
			BEGIN
				PRINT 'Error Occured: Could not insert into iriskeytoirmakey upcno:'+ CAST(@upcno AS VARCHAR) + 'item_key:'+ CAST(@item_key AS VARCHAR) 
			END	
		END

		INSERT INTO ItemIdentifier (Item_Key,Identifier,Default_Identifier,Deleted_Identifier,Add_Identifier,Remove_Identifier,National_Identifier,IdentifierType,CheckDigit, Scale_Identifier, NumPluDigitsSentToScale)
		VALUES(@Item_Key, @Identifier, 1,@Deleted_Item,0,0,@National_Identifier,@IdentifierType,null, @Scale_Identifier, @NumPluDigitsSentToScale)

		
	if @@error <> 0 
		BEGIN
			PRINT 'Error Occured: Could not insert into ItemIdentifier upcno:'+ CAST(@upcno AS VARCHAR) + 'item_key:'+ CAST(@item_key AS VARCHAR) 
		END	
--sku_number if logic

	Fetch Next from @CrsrVar
	Into 
		@Item_Key,
		@Item_Description,
		@Sign_Description,
		@Ingredients,
		@SubTeam_No,
		@Sales_Account,
		@Package_Desc1,
		@Package_Desc2,
		@Package_Unit_ID,
		@Min_Temperature,
		@Max_Temperature,
		@Units_Per_Pallet,
		@Average_Unit_Weight,
		@Tie,
		@High,
		@Yield,
		@Brand_ID,
		@Category_ID,
		@Origin_ID,
		@ShelfLife_Id,
		@ShelfLife_Length,
		@Retail_Unit_ID,
		@Vendor_Unit_ID,
		@Distribution_Unit_ID,
		@Deleted_Item,
		@WFM_Item,
		@Not_Available,
		@Pre_Order,
		@Remove_Item,
		@NoDistMarkup,
		@Organic,
		@Refrigerated,
		@Keep_Frozen,
		@Shipper_Item,
		@Full_Pallet_Only,
		@User_ID,
		@POS_Description,
		@Retail_Sale,
		@Food_Stamps,
--		@Discountable,
		@Price_Required,
		@Quantity_Required,
		@ItemType_ID,
		@HFM_Item,
		@ScaleDesc1,
		@ScaleDesc2,
		@Not_AvailableNote,
		@CountryProc_ID,
		@Insert_Date,
		@Manufacturing_Unit_ID,
		@EXEDistributed,
		@ClassID,
		@User_ID_Date,
		@DistSubTeam_No,
		@CostedByWeight,
		@TaxClassID,
		@LabelType_ID,
		@ScaleDesc3,
		@ScaleDesc4,
		@ScaleTare,
		@ScaleUseBy,
		@ScaleForcedTare,
		@QtyProhibit,
		@GroupList,
		@Recall_Flag,
		@LockAuth,
		@Identifier,
		@CheckDigit,
		@sku_number,
		@National_Identifier,
		@IdentifierType,
		@Scale_Identifier,
		@NumPluDigitsSentToScale,
		@upcno

end

begin
-- update Price.LinkCode

SET NOCOUNT OFF

update item_prep 
set item_key = isnull((select max(ir.item_key) 
				from	iriskeytoirmakey ir
				where	ir.iris_prod_code = upcno),0)

end

Close @CrsrVar
Deallocate @CrsrVar
END
GO