SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[GetTablesWithRetentionPolicy]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].GetTablesWithRetentionPolicy
GO
CREATE PROCEDURE dbo.GetTablesWithRetentionPolicy
AS
BEGIN

	SELECT DISTINCT [TABLE] FROM [RetentionPolicy]
	ORDER BY [TABLE] ASC

END

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO 