using System;
using Icon.Framework;
using System.Collections.Generic;

namespace KitBuilder.ESB.Listeners.Item.Service.Constants.ItemValidation
{
    public static class ValidationErrorCodes
    {
        public const string InvalidProductDescription = "InvalidProductDescription";
        public const string InvalidItemId = "ItemIdRequired";
        public const string InvalidItemTypeCode = "InvalidItemTypeCode";
        public const string InvalidBooleanString = "InvalidBooleanString";
        public const string InvalidAirChilled = "InvalidAirChilled";
        public const string InvalidAlcoholByVolume = "InvalidAlcoholByVolume";
        public const string InvalidAnimalWelfareRating = "InvalidAnimalWelfareRating";
        public const string InvalidBiodynamic = "InvalidBiodynamic";
        public const string InvalidBrand = "InvalidBrand";
        public const string InvalidCaseinFree = "InvalidCaseinFree";
        public const string InvalidCheeseMilkType = "InvalidCheeseMilkType";
        public const string InvalidCheeseRaw = "InvalidCheeseRaw";
        public const string InvalidDeliverySystem = "InvalidDeliverySystem";
        public const string InvalidDrainedWeight = "InvalidDrainedWeight";
        public const string InvalidDrainedWeightUom = "InvalidDrainedWeightUom";
        public const string InvalidDryAged = "InvalidDryAged";
        public const string InvalidEcoScaleRating = "InvalidEcoScaleRating";
        public const string InvalidFairTradeCertified = "InvalidFairTradeCertified";
        public const string InvalidFinancialHierarchyClassId = "InvalidFinancialHierarchyClassId";
        public const string InvalidFoodStampEligible = "InvalidFoodStampEligible";
        public const string InvalidFreeRange = "InvalidFreeRange";
        public const string InvalidFreshOrFrozen = "InvalidFreshOrFrozen";
        public const string InvalidGrassFed = "InvalidGrassFed";
        public const string InvalidGlutenFree = "InvalidGlutenFree";
        public const string InvalidHemp = "InvalidHemp";
        public const string InvalidHiddenItem = "InvalidHiddenItem";
        public const string InvalidInforMessageId = "InvalidMessageId";
        public const string InvalidKosher = "InvalidKosher";
        public const string InvalidLocalLoanProducer = "InvalidLocalLoanProducer";
        public const string InvalidMadeInHouse = "InvalidMadeInHouse";
        public const string InvalidMainProductName = "InvalidMainProductName";
        public const string InvalidMerchandiseHierarchyClassId = "InvalidMerchandiseHierarchyClassId";
        public const string InvalidModifiedDate = "InvalidModifiedDate";
        public const string InvalidModifiedUser = "InvalidModifiedUser";
        public const string InvalidMsc = "InvalidMsc";
        public const string InvalidNationalHierarchyClassId = "InvalidNationalHierarchyClassId";
        public const string InvalidNotes = "InvalidNotes";
        public const string InvalidNonGmo = "InvalidNonGmo";
        public const string InvalidNutritionRequired = "InvalidNutritionRequired";
        public const string InvalidOrganic = "InvalidOrganic";
        public const string InvalidOrganicPersonalCare = "InvalidOrganicPersonalCare";
        public const string InvalidPackageUnit = "InvalidPackageUnit";
        public const string InvalidPaleo = "InvalidPaleo";
        public const string InvalidPastureRaised = "InvalidPastureRaised";
        public const string InvalidPosDescription = "InvalidPosDescription";
        public const string RequiredPosScaleTare = "RequiredPosScaleTare";
        public const string InvalidPosScaleTare = "InvalidPosScaleTare";
        public const string InvalidPremiumBodyCare = "InvalidPremiumBodyCare";
        public const string InvalidProductFlavorType = "InvalidProductFlavorType";
        public const string InvalidProhibitDiscount = "InvalidProhibitDiscount";
        public const string InvalidRetailSize = "InvalidRetailSize";
        public const string InvalidRetailUom = "InvalidRetailUom";
        public const string InvalidScanCode = "InvalidScanCode";
        public const string InvalidScanCodeType = "InvalidScanCodeType";
        public const string InvalidSeafoodCatchType = "InvalidSeafoodCatchType";
        public const string InvalidTaxHierarchyClassId = "InvalidTaxHierarchyClassId";
        public const string InvalidVegan = "InvalidVegan";
        public const string InvalidVegetarian = "InvalidVegetarian";
        public const string InvalidWholeTrade = "InvalidWholeTrade";
        public const string DuplicateMerchandiseHierarchyClass = "DuplicateMerchandiseHierarchyClass";
        public const string DuplicateNationalHierarchyClass = "DuplicateNationalHierarchyClass";
        public const string NonExistentBrand = "NonExistentBrand";
        public const string NonExistentSubTeam = "NonExistentSubTeam";
        public const string NonExistentSubBrick = "NonExistentSubBrick";
        public const string NonExistentNationalClass = "NonExistentNationalClass";
        public const string NonExistentTax = "NonExistentTax";
        public const string OutOfSyncItemUpdateErrorCode = "OutOfSyncItemUpdateErrorCode";
        public const string InvalidCustomerFriendlyDescription = "InvalidCustomerFriendlyDescription";
        public const string InvalidGlobalPricingProgram = "InvalidGlobalPricingProgram";
        public const string InvalidWicEligible = "InvalidWicEligible";
        public const string InvalidSmithsonianBirdFriendly = "InvalidSmithsonianBirdFriendly";
        public const string InvalidRefrigerated = "InvalidRefrigerated";
        public const string InvalidRainforestAlliance = "InvalidRainforestAlliance";
        public const string InvalidPrimeBeef = "InvalidPrimeBeef";
        public const string InvalidMadeWithOrganicGrapes = "InvalidMadeWithOrganicGrapes";
        public const string InvalidFlexibleText = "InvalidFlexibleText";
        public const string InvalidShelfLife = "InvalidShelfLife";
        public const string InvalidSelfCheckoutItemTareGroup = "InvalidSelfCheckoutItemTareGroup";
        public const string InvalidLine = "InvalidLine";
        public const string InvalidSKU = "InvalidSKU";
        public const string InvalidPriceLine = "InvalidPriceLine";
        public const string InvalidVariantSize = "InvalidVariantSize";
        public const string InvalidEStoreNutritionRequired = "InvalidEStoreNutritionRequired";
        public const string InvalidPrimeNowEligible = "InvalidPrimeNowEligiblep";
        public const string InvalidEstoreEligible = "InvalidEstoreEligible";
        public const string InvalidTSFEligible = "InvalidTSFEligible";
        public const string InvalidWFMEligilble = "InvalidWFMEligilble";
        public const string InvalidOther3PEligible = "InvalidOther3PEligible";
    }
}