CREATE TABLE [dbo].[cxbstorr] (
    [store]          SMALLINT  NULL,
    [company]        SMALLINT  NULL,
    [region]         SMALLINT  NULL,
    [district]       SMALLINT  NULL,
    [name1]          CHAR (25) NULL,
    [name2]          CHAR (25) NULL,
    [address]        CHAR (25) NULL,
    [city]           CHAR (20) NULL,
    [state]          CHAR (2)  NULL,
    [zip]            CHAR (10) NULL,
    [modemno]        CHAR (36) NULL,
    [manager]        CHAR (25) NULL,
    [postype]        CHAR (1)  NULL,
    [protocol]       CHAR (6)  NULL,
    [fmtcode]        CHAR (6)  NULL,
    [primgroup]      SMALLINT  NULL,
    [mixmatchflag]   CHAR (1)  NULL,
    [primline]       SMALLINT  NULL,
    [secgroup]       SMALLINT  NULL,
    [secline]        SMALLINT  NULL,
    [storeid]        CHAR (15) NULL,
    [hostid]         CHAR (15) NULL,
    [mnt_code]       CHAR (1)  NULL,
    [dsdflag]        CHAR (1)  NULL,
    [scaletype]      CHAR (1)  NULL,
    [mzone]          SMALLINT  NULL,
    [print_rept]     CHAR (1)  NULL,
    [auto_print]     CHAR (1)  NULL,
    [addrep_for_chg] CHAR (1)  NULL,
    [cost_method]    INT       NULL,
    [rbx50]          CHAR (1)  NULL
);

