CREATE TABLE [dbo].[cxbupcmr] (
    [upcno]           CHAR (13)      NULL,
    [longdesc]        CHAR (30)      NULL,
    [itemsize]        NUMERIC (7, 3) NULL,
    [itemuom]         CHAR (2)       NULL,
    [dept]            CHAR (4)       NULL,
    [posdesc]         CHAR (25)      NULL,
    [miscalpha1]      CHAR (10)      NULL,
    [miscalpha2]      CHAR (26)      NULL,
    [commodity]       SMALLINT       NULL,
    [category]        INT            NULL,
    [class]           SMALLINT       NULL,
    [family]          SMALLINT       NULL,
    [supplyitem]      CHAR (1)       NULL,
    [createdate]      DATETIME       NULL,
    [plucode]         INT            NULL,
    [relateflag]      CHAR (1)       NULL,
    [coupfamily]      SMALLINT       NULL,
    [seasonal]        CHAR (2)       NULL,
    [tagqty]          SMALLINT       NULL,
    [tagtype]         CHAR (1)       NULL,
    [unitcatg]        SMALLINT       NULL,
    [package]         SMALLINT       NULL,
    [perunitdiv]      NUMERIC (6, 2) NULL,
    [perunituom]      CHAR (8)       NULL,
    [massmaint]       SMALLINT       NULL,
    [firstsold]       DATETIME       NULL,
    [firsttime]       INT            NULL,
    [lastsold]        DATETIME       NULL,
    [lasttime]        INT            NULL,
    [hicode1]         CHAR (4)       NULL,
    [hicode2]         CHAR (6)       NULL,
    [hicode3]         CHAR (16)      NULL,
    [item_status]     CHAR (1)       NULL,
    [shlfgrap]        CHAR (30)      NULL,
    [ad_group]        SMALLINT       NULL,
    [chain_code]      CHAR (13)      NULL,
    [misc_group]      CHAR (6)       NULL,
    [itembrand]       CHAR (30)      NULL,
    [ravendor1]       CHAR (8)       NULL,
    [ravendor2]       CHAR (8)       NULL,
    [ravendor3]       CHAR (8)       NULL,
    [ravendor4]       CHAR (8)       NULL,
    [privlabl]        CHAR (1)       NULL,
    [retailitm]       CHAR (1)       NULL,
    [cost_method]     INT            NULL,
    [item_added_time] DATETIME       NULL,
    [added_by_user]   CHAR (20)      NULL,
    [weight_factor]   FLOAT (53)     NULL,
    [item_type_code]  SMALLINT       NULL,
    [sku_number]      CHAR (12)      NULL
);

