CREATE TABLE [dbo].[cxspromd] (
    [upcno]          CHAR (13)      NULL,
    [store]          SMALLINT       NULL,
    [vendor]         CHAR (8)       NULL,
    [warehouse]      CHAR (12)      NULL,
    [salepm]         SMALLINT       NULL,
    [saleprice]      NUMERIC (6, 2) NULL,
    [saledstart]     SMALLDATETIME  NULL,
    [saledend]       SMALLDATETIME  NULL,
    [saletstart]     CHAR (8)       NULL,
    [saletend]       CHAR (8)       NULL,
    [salecost]       NUMERIC (8, 4) NULL,
    [pzone]          SMALLINT       NULL,
    [projunits]      INT            NULL,
    [regunits]       INT            NULL,
    [mktcode]        CHAR (4)       NULL,
    [displaycode]    CHAR (4)       NULL,
    [promotecode]    CHAR (4)       NULL,
    [comment1]       CHAR (50)      NULL,
    [comment2]       CHAR (50)      NULL,
    [billback]       NUMERIC (6, 2) NULL,
    [sortcode]       CHAR (4)       NULL,
    [ovr_ride_slcst] CHAR (1)       NULL
);

