CREATE TABLE [dbo].[dept] (
    [dp_dept_number]     CHAR (4)       NULL,
    [dp_group_number]    CHAR (4)       NULL,
    [dp_pos_dept_desc]   CHAR (6)       NULL,
    [dp_dept_desc]       CHAR (20)      NULL,
    [dp_halo]            NUMERIC (8, 2) NULL,
    [dp_lalo]            NUMERIC (8, 2) NULL,
    [dp_si_1]            CHAR (1)       NULL,
    [dp_si_2]            CHAR (1)       NULL,
    [dp_si_3]            CHAR (1)       NULL,
    [dp_tax_4]           CHAR (1)       NULL,
    [dp_food_stamp]      CHAR (1)       NULL,
    [dp_trade_stamp]     CHAR (1)       NULL,
    [dp_item_discount]   CHAR (1)       NULL,
    [dp_disc_itmzr_1]    CHAR (1)       NULL,
    [dp_disc_itmzr_2]    CHAR (1)       NULL,
    [dp_disc_itmzr_3]    CHAR (1)       NULL,
    [dp_consumer_panel]  CHAR (1)       NULL,
    [dp_fixed_gm_percen] REAL           NULL,
    [dp_budget_period]   CHAR (1)       NULL,
    [dp_budget_amount]   NUMERIC (8, 2) NULL,
    [dp_sales_ptd]       NUMERIC (8, 2) NULL,
    [dp_sales_last_rese] NUMERIC (8, 2) NULL,
    [dp_2127_si_1]       CHAR (1)       NULL,
    [dp_2127_si_2]       CHAR (1)       NULL,
    [dp_2127_si_3]       CHAR (1)       NULL,
    [dp_vat_1]           CHAR (1)       NULL,
    [dp_vat_2]           CHAR (1)       NULL,
    [dp_vat_3]           CHAR (1)       NULL,
    [dp_vat_4]           CHAR (1)       NULL,
    [dp_vat_5]           CHAR (1)       NULL,
    [dp_vat_6]           CHAR (1)       NULL,
    [dp_vat_7]           CHAR (1)       NULL,
    [dp_kg_item_flag]    CHAR (1)       NULL,
    [dp_frac_item]       CHAR (1)       NULL,
    [dp_promo_price]     CHAR (1)       NULL,
    [dp_2127_reserved_1] CHAR (1)       NULL,
    [dp_2127_reserved_2] CHAR (1)       NULL,
    [dp_2127_reserved_3] CHAR (1)       NULL,
    [dp_2127_reserved_4] CHAR (1)       NULL,
    [dp_2127_reserved_5] CHAR (1)       NULL,
    [dp_2127_reserved_6] CHAR (1)       NULL,
    [dp_2127_reserved_7] CHAR (1)       NULL,
    [dp_limit_action1]   CHAR (1)       NULL,
    [dp_limit_action2]   CHAR (1)       NULL,
    [dp_limit_action3]   CHAR (1)       NULL,
    [dp_user_exit_1]     CHAR (1)       NULL,
    [dp_user_exit_2]     CHAR (1)       NULL,
    [dp_user_exit_3]     CHAR (1)       NULL,
    [dp_coup_mult]       CHAR (1)       NULL
);

