CREATE TABLE [dbo].[ItemScaleOverrideHistory] (
    [Insert_Date]               DATETIME     CONSTRAINT [DF_ItemScaleOverrideHistory_Insert_Date] DEFAULT (getdate()) NOT NULL,
    [Item_Key]                  INT          NULL,
    [StoreJurisdictionID]       INT          NULL,
    [Scale_Description1]        VARCHAR (64) NULL,
    [Scale_Description2]        VARCHAR (64) NULL,
    [Scale_Description3]        VARCHAR (64) NULL,
    [Scale_Description4]        VARCHAR (64) NULL,
    [Scale_ExtraText_ID]        INT          NULL,
    [Scale_Tare_ID]             INT          NULL,
    [Scale_LabelStyle_ID]       INT          NULL,
    [Scale_ScaleUOMUnit_ID]     INT          NULL,
    [Scale_RandomWeightType_ID] INT          NULL,
    [Scale_FixedWeight]         VARCHAR (25) NULL,
    [Scale_ByCount]             INT          NULL,
    [ShelfLife_Length]          SMALLINT     NULL,
    [ForceTare]                 BIT          NULL,
    [Scale_Alternate_Tare_ID]   INT          NULL,
    [Scale_EatBy_ID]            INT          NULL,
    [Scale_Grade_ID]            INT          NULL,
    [PrintBlankShelfLife]       BIT          NULL,
    [PrintBlankEatBy]           BIT          NULL,
    [PrintBlankPackDate]        BIT          NULL,
    [PrintBlankWeight]          BIT          NULL,
    [PrintBlankUnitPrice]       BIT          NULL,
    [PrintBlankTotalPrice]      BIT          NULL,
    [Nutrifact_ID]              INT          NULL
);

