CREATE TABLE [dbo].[OrderItemCOOL4010Detail] (
    [OrderItemCOOL4010DetailID] INT        IDENTITY (1, 1) NOT NULL,
    [OrderItem_ID]              INT        NOT NULL,
    [ActionCode]                CHAR (1)   NULL,
    [ShippingDC]                NCHAR (2)  NULL,
    [ShippingWarehouse]         NCHAR (2)  NULL,
    [ISRID]                     NCHAR (10) NULL,
    [OutboundPalletID]          NCHAR (18) NULL,
    [ShipmentDate]              NCHAR (10) NULL,
    [ShipmentTime]              NCHAR (8)  NULL,
    [Product]                   NCHAR (18) NULL,
    [ProductDetail]             NCHAR (5)  NULL,
    [ProductDescription]        NCHAR (30) NULL,
    [ProductSize]               NCHAR (10) NULL,
    [ShippedQuantity]           NCHAR (10) NULL,
    [InvoiceID]                 NCHAR (10) NULL,
    [RecipientName]             NCHAR (30) NULL,
    [RecipientAddress1]         NCHAR (30) NULL,
    [RecipientAddress2]         NCHAR (30) NULL,
    [RecipientCity]             NCHAR (30) NULL,
    [RecipientState]            NCHAR (15) NULL,
    [RecipientZip]              NCHAR (10) NULL,
    [RecipientPhone]            NCHAR (20) NULL,
    [RecipientCountry]          NCHAR (15) NULL,
    [RecipientContact]          NCHAR (30) NULL,
    [SupplierName]              NCHAR (30) NULL,
    [SupplierAddress1]          NCHAR (30) NULL,
    [SupplierAddress2]          NCHAR (30) NULL,
    [SupplierCity]              NCHAR (30) NULL,
    [SupplierState]             NCHAR (15) NULL,
    [SupplierZip]               NCHAR (10) NULL,
    [SupplierPhone]             NCHAR (20) NULL,
    [SupplierCountry]           NCHAR (15) NULL,
    [SupplierContact]           NCHAR (30) NULL,
    [ReceiptID]                 NCHAR (10) NULL,
    [ReceiptDate]               NCHAR (10) NULL,
    [ReceiptQuantity]           NCHAR (10) NULL,
    [Type]                      NCHAR (1)  NULL,
    [ExclusivelyFrom]           NCHAR (3)  NULL,
    [Processed]                 NCHAR (3)  NULL,
    [Caught]                    NCHAR (3)  NULL,
    [Hatch]                     NCHAR (3)  NULL,
    [Raise]                     NCHAR (3)  NULL,
    [Harvest]                   NCHAR (3)  NULL,
    [LotNumber]                 NCHAR (20) NULL,
    [OutboundCarrierName]       NCHAR (99) NULL,
    [OutboundCarrierAddress1]   NCHAR (50) NULL,
    [OutboundCarrierAddress2]   NCHAR (30) NULL,
    [OutboundCarrierCity]       NCHAR (29) NULL,
    [OutboundCarrierState]      NCHAR (15) NULL,
    [OutboundCarrierZip]        NCHAR (10) NULL,
    [OutboundCarrierPhone]      NCHAR (10) NULL,
    [OutboundCarrierCountry]    NCHAR (20) NULL,
    [OutboundDriverFirst]       NCHAR (15) NULL,
    [OutboundDriverInitial]     NCHAR (1)  NULL,
    [OutboundDriverLast]        NCHAR (30) NULL,
    [OutboundTrailerNumber]     NCHAR (10) NULL,
    [OutboundTrailerOwner]      NCHAR (99) NULL,
    [InboundCarrierName]        NCHAR (99) NULL,
    [InboundCarrierAddress1]    NCHAR (50) NULL,
    [InboundCarrierAddress2]    NCHAR (30) NULL,
    [InboundCarrierCity]        NCHAR (29) NULL,
    [InboundCarrierState]       NCHAR (15) NULL,
    [InboundCarrierZip]         NCHAR (10) NULL,
    [InboundCarrierPhone]       NCHAR (10) NULL,
    [InboundCarrierCountry]     NCHAR (20) NULL,
    [IIPSRefNumber]             NCHAR (14) NULL,
    [IIPSRefSequence]           NCHAR (4)  NULL,
    [CreateDate]                DATETIME   DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_OrderItem4010CoolDetail] PRIMARY KEY CLUSTERED ([OrderItemCOOL4010DetailID] ASC),
    CONSTRAINT [FK_OrderItemCOOL4010Detail_OrderItem] FOREIGN KEY ([OrderItem_ID]) REFERENCES [dbo].[OrderItem] ([OrderItem_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_Cool4010_OrderItemId]
    ON [dbo].[OrderItemCOOL4010Detail]([OrderItem_ID] ASC) WITH (FILLFACTOR = 90);

