-- Task 3343

/*
Deployment script for IconWurk2

This code was generated by a tool.  << yeah it was.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "IconTestStage2"
:setvar DefaultFilePrefix "IconTestStage2"
:setvar DefaultDataPath "E:\SQL_DATA"
:setvar DefaultLogPath "E:\SQL_LOGS"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping Country_PhysicalAddress_FK1...';


GO
ALTER TABLE [dbo].[PhysicalAddress] DROP CONSTRAINT [Country_PhysicalAddress_FK1];


GO
PRINT N'Dropping Country_PostalCode_FK1...';


GO
ALTER TABLE [dbo].[PostalCode] DROP CONSTRAINT [Country_PostalCode_FK1];


GO
PRINT N'Dropping Country_Territory_FK1...';


GO
ALTER TABLE [dbo].[Territory] DROP CONSTRAINT [Country_Territory_FK1];


GO
PRINT N'Dropping CurrencyType_ItemPrice_FK1...';


GO
ALTER TABLE [dbo].[ItemPrice] DROP CONSTRAINT [CurrencyType_ItemPrice_FK1];


GO
PRINT N'Dropping UOM_ItemPrice_FK1...';


GO
ALTER TABLE [dbo].[ItemPrice] DROP CONSTRAINT [UOM_ItemPrice_FK1];


GO
PRINT N'Dropping ItemPriceType_ItemPrice_FK1...';


GO
ALTER TABLE [dbo].[ItemPrice] DROP CONSTRAINT [ItemPriceType_ItemPrice_FK1];


GO
PRINT N'Dropping UOM_ItemTrait_FK1...';


GO
ALTER TABLE [dbo].[ItemTrait] DROP CONSTRAINT [UOM_ItemTrait_FK1];


GO
PRINT N'Dropping ItemType_Item_FK1...';


GO
ALTER TABLE [dbo].[Item] DROP CONSTRAINT [ItemType_Item_FK1];


GO
PRINT N'Dropping UOM_LocaleTrait_FK1...';


GO
ALTER TABLE [dbo].[LocaleTrait] DROP CONSTRAINT [UOM_LocaleTrait_FK1];


GO
PRINT N'Dropping LocaleType_Locale_FK1...';


GO
ALTER TABLE [dbo].[Locale] DROP CONSTRAINT [LocaleType_Locale_FK1];


GO
PRINT N'Dropping Organization_Locale_FK1...';


GO
ALTER TABLE [dbo].[Locale] DROP CONSTRAINT [Organization_Locale_FK1];


GO
PRINT N'Dropping Party_Organization_FK1...';


GO
ALTER TABLE [dbo].[Organization] DROP CONSTRAINT [Party_Organization_FK1];


GO
PRINT N'Dropping Organization_Organization_FK1...';


GO
ALTER TABLE [dbo].[Organization] DROP CONSTRAINT [Organization_Organization_FK1];


GO
PRINT N'Dropping OrganizationType_Organization_FK1...';


GO
ALTER TABLE [dbo].[Organization] DROP CONSTRAINT [OrganizationType_Organization_FK1];


GO
PRINT N'Dropping Organization_OrganizationName_FK1...';


GO
ALTER TABLE [dbo].[OrganizationName] DROP CONSTRAINT [Organization_OrganizationName_FK1];


GO
PRINT N'Dropping PartyType_Party_FK1...';


GO
ALTER TABLE [dbo].[Party] DROP CONSTRAINT [PartyType_Party_FK1];


GO
PRINT N'Dropping PostalCode_PhysicalAddress_FK1...';


GO
ALTER TABLE [dbo].[PhysicalAddress] DROP CONSTRAINT [PostalCode_PhysicalAddress_FK1];


GO
PRINT N'Dropping County_PostalCode_FK1...';


GO
ALTER TABLE [dbo].[PostalCode] DROP CONSTRAINT [County_PostalCode_FK1];


GO
PRINT N'Dropping Trait_ItemTrait_FK1...';


GO
ALTER TABLE [dbo].[ItemTrait] DROP CONSTRAINT [Trait_ItemTrait_FK1];


GO
PRINT N'Dropping Trait_LocaleTrait_FK1...';


GO
ALTER TABLE [dbo].[LocaleTrait] DROP CONSTRAINT [Trait_LocaleTrait_FK1];


GO
PRINT N'Dropping TraitGroup_Trait_FK1...';


GO
ALTER TABLE [dbo].[Trait] DROP CONSTRAINT [TraitGroup_Trait_FK1];


--GO
--PRINT N'Creating [WFM\TFSAdmin]...';

GO
PRINT N'Starting rebuilding table [dbo].[Country]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Country] (
    [countryCode] NVARCHAR (3)   NOT NULL,
    [countryName] NVARCHAR (255) NULL,
    CONSTRAINT [tmp_ms_xx_constraint_Country_PK] PRIMARY KEY CLUSTERED ([countryCode] ASC) WITH (FILLFACTOR = 80)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Country])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_Country] ([countryCode], [countryName])
        SELECT   [countryCode],
                 [countryName]
        FROM     [dbo].[Country]
        ORDER BY [countryCode] ASC;
    END

DROP TABLE [dbo].[Country];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Country]', N'Country';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_Country_PK]', N'Country_PK', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
/*
The column [dbo].[CurrencyType].[currencyTypeCode] on table [dbo].[CurrencyType] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/
GO
PRINT N'Starting rebuilding table [dbo].[CurrencyType]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_CurrencyType] (
    [currencyTypeID]   INT            IDENTITY (1, 1) NOT NULL,
    [currencyTypeCode] NVARCHAR (3)   NOT NULL,
    [currencyTypeDesc] NVARCHAR (255) NULL,
    CONSTRAINT [tmp_ms_xx_constraint_CurrencyType_PK] PRIMARY KEY CLUSTERED ([currencyTypeID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [tmp_ms_xx_constraint_AK_currencyTypeCode_currencyTypeCode] UNIQUE NONCLUSTERED ([currencyTypeCode] ASC) WITH (FILLFACTOR = 80)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[CurrencyType])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_CurrencyType] ON;
        INSERT INTO [dbo].[tmp_ms_xx_CurrencyType] ([currencyTypeID], [currencyTypeDesc])
        SELECT   [currencyTypeID],
                 [currencyTypeDesc]
        FROM     [dbo].[CurrencyType]
        ORDER BY [currencyTypeID] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_CurrencyType] OFF;
    END

DROP TABLE [dbo].[CurrencyType];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_CurrencyType]', N'CurrencyType';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_CurrencyType_PK]', N'CurrencyType_PK', N'OBJECT';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_AK_currencyTypeCode_currencyTypeCode]', N'AK_currencyTypeCode_currencyTypeCode', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Altering [dbo].[ItemPrice]...';


GO
ALTER TABLE [dbo].[ItemPrice] ALTER COLUMN [uomID] INT NOT NULL;


GO
/*
The column [dbo].[ItemPriceType].[itemPriceTypeCode] on table [dbo].[ItemPriceType] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/
GO
PRINT N'Starting rebuilding table [dbo].[ItemPriceType]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_ItemPriceType] (
    [itemPriceTypeID]   INT            IDENTITY (1, 1) NOT NULL,
    [itemPriceTypeCode] NVARCHAR (3)   NOT NULL,
    [itemPriceTypeDesc] NVARCHAR (255) NULL,
    CONSTRAINT [tmp_ms_xx_constraint_ItemPriceType_PK] PRIMARY KEY CLUSTERED ([itemPriceTypeID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [tmp_ms_xx_constraint_AK_itemPriceTypeCode_itemPriceTypeCode] UNIQUE NONCLUSTERED ([itemPriceTypeCode] ASC) WITH (FILLFACTOR = 80)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[ItemPriceType])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_ItemPriceType] ON;
        INSERT INTO [dbo].[tmp_ms_xx_ItemPriceType] ([itemPriceTypeID], [itemPriceTypeDesc])
        SELECT   [itemPriceTypeID],
                 [itemPriceTypeDesc]
        FROM     [dbo].[ItemPriceType]
        ORDER BY [itemPriceTypeID] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_ItemPriceType] OFF;
    END

DROP TABLE [dbo].[ItemPriceType];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_ItemPriceType]', N'ItemPriceType';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_ItemPriceType_PK]', N'ItemPriceType_PK', N'OBJECT';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_AK_itemPriceTypeCode_itemPriceTypeCode]', N'AK_itemPriceTypeCode_itemPriceTypeCode', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Altering [dbo].[ItemTrait]...';


GO
ALTER TABLE [dbo].[ItemTrait] ALTER COLUMN [uomID] INT NULL;


GO
/*
The column [dbo].[ItemType].[itemTypeCode] on table [dbo].[ItemType] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/
GO
PRINT N'***Hack #1*** Starting rebuilding table [dbo].[ItemType]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_ItemType] (
    [itemTypeID]   INT            IDENTITY (1, 1) NOT NULL,
    [itemTypeCode] NVARCHAR (3)   NOT NULL,
    [itemTypeDesc] NVARCHAR (255) NULL,
    CONSTRAINT [tmp_ms_xx_constraint_ItemType_PK] PRIMARY KEY CLUSTERED ([itemTypeID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [tmp_ms_xx_constraint_AK_itemTypeCode_itemTypeCode] UNIQUE NONCLUSTERED ([itemTypeCode] ASC) WITH (FILLFACTOR = 80)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[ItemType])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_ItemType] ON;
        --INSERT INTO [dbo].[tmp_ms_xx_ItemType] ([itemTypeID], [itemTypeDesc])
        --SELECT   [itemTypeID],
        --         [itemTypeDesc]
        --FROM     [dbo].[ItemType]
        --ORDER BY [itemTypeID] ASC;
         INSERT INTO [dbo].[tmp_ms_xx_ItemType] ([itemTypeID], [itemTypeCode], [itemTypeDesc]) VALUES (1, 'RTL', N'Retail Sale')
         INSERT INTO [dbo].[tmp_ms_xx_ItemType] ([itemTypeID], [itemTypeCode], [itemTypeDesc]) VALUES (2, 'DEP', N'Deposit')
         INSERT INTO [dbo].[tmp_ms_xx_ItemType] ([itemTypeID], [itemTypeCode], [itemTypeDesc]) VALUES (3, 'TAR', N'Tare')
         SET IDENTITY_INSERT [dbo].[tmp_ms_xx_ItemType] OFF;
    END

DROP TABLE [dbo].[ItemType];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_ItemType]', N'ItemType';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_ItemType_PK]', N'ItemType_PK', N'OBJECT';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_AK_itemTypeCode_itemTypeCode]', N'AK_itemTypeCode_itemTypeCode', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Altering [dbo].[LocaleTrait]...';


GO
ALTER TABLE [dbo].[LocaleTrait] ALTER COLUMN [uomID] INT NULL;


GO
/*
The column [dbo].[LocaleType].[localeTypeCode] on table [dbo].[LocaleType] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/
GO
PRINT N'***Hack #2*** Starting rebuilding table [dbo].[LocaleType]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_LocaleType] (
    [localeTypeID]   INT            IDENTITY (1, 1) NOT NULL,
    [localeTypeCode] NVARCHAR (3)   NOT NULL,
    [localeTypeDesc] NVARCHAR (255) NULL,
    CONSTRAINT [tmp_ms_xx_constraint_LocaleType_PK] PRIMARY KEY CLUSTERED ([localeTypeID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [tmp_ms_xx_constraint_AK_localeTypeCode_localeTypeCode] UNIQUE NONCLUSTERED ([localeTypeCode] ASC) WITH (FILLFACTOR = 80)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[LocaleType])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_LocaleType] ON;
        --INSERT INTO [dbo].[tmp_ms_xx_LocaleType] ([localeTypeID], [localeTypeDesc])
        --SELECT   [localeTypeID],
        --         [localeTypeDesc]
        --FROM     [dbo].[LocaleType]
        --ORDER BY [localeTypeID] ASC;
        INSERT INTO [dbo].[tmp_ms_xx_LocaleType] ([localeTypeID], [localeTypeCode], [localeTypeDesc]) VALUES (1, 'CH', N'Chain')
        INSERT INTO [dbo].[tmp_ms_xx_LocaleType] ([localeTypeID], [localeTypeCode], [localeTypeDesc]) VALUES (2, 'RG', N'Region')
        INSERT INTO [dbo].[tmp_ms_xx_LocaleType] ([localeTypeID], [localeTypeCode], [localeTypeDesc]) VALUES (3, 'MT', N'Metro')
        INSERT INTO [dbo].[tmp_ms_xx_LocaleType] ([localeTypeID], [localeTypeCode], [localeTypeDesc]) VALUES (4, 'ST', N'Store')
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_LocaleType] OFF;
    END

DROP TABLE [dbo].[LocaleType];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_LocaleType]', N'LocaleType';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_LocaleType_PK]', N'LocaleType_PK', N'OBJECT';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_AK_localeTypeCode_localeTypeCode]', N'AK_localeTypeCode_localeTypeCode', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'***Hack #3***  Starting rebuilding table [dbo].[Organization]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Organization] (
    [orgPartyID]       INT            IDENTITY (1, 1) NOT NULL,
    [orgTypeID]        INT            NULL,
    [parentOrgPartyID] INT            NULL,
    [orgDesc]          NVARCHAR (255) NULL,
    CONSTRAINT [tmp_ms_xx_constraint_Organization_PK] PRIMARY KEY CLUSTERED ([orgPartyID] ASC) WITH (FILLFACTOR = 80)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Organization])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Organization] ON;
        --INSERT INTO [dbo].[tmp_ms_xx_Organization] ([orgPartyID], [orgTypeID], [parentOrgPartyID], [orgDesc])
        --SELECT   [orgPartyID],
        --         [orgTypeID],
        --         [parentOrgPartyID],
        --         [orgDesc]
        --FROM     [dbo].[Organization]
        --ORDER BY [orgPartyID] ASC;
        INSERT INTO [dbo].[tmp_ms_xx_Organization] ([orgPartyID], [orgTypeID], [parentOrgPartyID], [orgDesc]) VALUES (1, 1, NULL, N'Whole Foods')
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Organization] OFF;
    END

DROP TABLE [dbo].[Organization];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Organization]', N'Organization';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_Organization_PK]', N'Organization_PK', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
/*
The column [dbo].[OrganizationType].[orgTypeCode] on table [dbo].[OrganizationType] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/
GO
PRINT N'***Hack #4***  Starting rebuilding table [dbo].[OrganizationType]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_OrganizationType] (
    [orgTypeID]   INT            IDENTITY (1, 1) NOT NULL,
    [orgTypeCode] NVARCHAR (3)   NOT NULL,
    [orgTypeDesc] NVARCHAR (255) NULL,
    CONSTRAINT [tmp_ms_xx_constraint_OrganizationType_PK] PRIMARY KEY CLUSTERED ([orgTypeID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [tmp_ms_xx_constraint_AK_orgTypeCode_orgTypeCode] UNIQUE NONCLUSTERED ([orgTypeCode] ASC) WITH (FILLFACTOR = 80)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[OrganizationType])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_OrganizationType] ON;
        --INSERT INTO [dbo].[tmp_ms_xx_OrganizationType] ([orgTypeID], [orgTypeDesc])
        --SELECT   [orgTypeID],
        --         [orgTypeDesc]
        --FROM     [dbo].[OrganizationType]
        --ORDER BY [orgTypeID] ASC;
        INSERT INTO [dbo].[tmp_ms_xx_OrganizationType] ([orgTypeID], [orgTypeCode], [orgTypeDesc]) VALUES (1, 'RT', N'Retailer')
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_OrganizationType] OFF;
    END

DROP TABLE [dbo].[OrganizationType];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_OrganizationType]', N'OrganizationType';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_OrganizationType_PK]', N'OrganizationType_PK', N'OBJECT';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_AK_orgTypeCode_orgTypeCode]', N'AK_orgTypeCode_orgTypeCode', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
/*
The column [dbo].[PartyType].[partyTypeCode] on table [dbo].[PartyType] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/
GO
PRINT N'***Hack #5***  Starting rebuilding table [dbo].[PartyType]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_PartyType] (
    [partyTypeID]   INT            IDENTITY (1, 1) NOT NULL,
    [partyTypeCode] NVARCHAR (3)   NOT NULL,
    [partyTypeDesc] NVARCHAR (255) NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PartyType_PK] PRIMARY KEY CLUSTERED ([partyTypeID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [tmp_ms_xx_constraint_AK_partyTypeCode_partyTypeCode] UNIQUE NONCLUSTERED ([partyTypeCode] ASC) WITH (FILLFACTOR = 80)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[PartyType])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_PartyType] ON;
        --INSERT INTO [dbo].[tmp_ms_xx_PartyType] ([partyTypeID], [partyTypeDesc])
        --SELECT   [partyTypeID],
        --         [partyTypeDesc]
        --FROM     [dbo].[PartyType]
        --ORDER BY [partyTypeID] ASC;
        INSERT INTO [dbo].[tmp_ms_xx_PartyType] ([partyTypeID], [partyTypeCode], [partyTypeDesc]) VALUES (1, 'ORG', N'Organization')
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_PartyType] OFF;
    END

DROP TABLE [dbo].[PartyType];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_PartyType]', N'PartyType';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PartyType_PK]', N'PartyType_PK', N'OBJECT';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_AK_partyTypeCode_partyTypeCode]', N'AK_partyTypeCode_partyTypeCode', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Altering [dbo].[PhysicalAddress]...';


GO
ALTER TABLE [dbo].[PhysicalAddress] ALTER COLUMN [countryCode] NVARCHAR (3) NULL;


GO
PRINT N'Starting rebuilding table [dbo].[PostalCode]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_PostalCode] (
    [postalCode]  INT          NOT NULL,
    [countryCode] NVARCHAR (3) NOT NULL,
    [countyCode]  INT          NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PostalCode_PK] PRIMARY KEY CLUSTERED ([postalCode] ASC, [countryCode] ASC) WITH (FILLFACTOR = 80)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[PostalCode])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_PostalCode] ([postalCode], [countryCode], [countyCode])
        SELECT   [postalCode],
                 [countryCode],
                 [countyCode]
        FROM     [dbo].[PostalCode]
        ORDER BY [postalCode] ASC, [countryCode] ASC;
    END

DROP TABLE [dbo].[PostalCode];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_PostalCode]', N'PostalCode';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PostalCode_PK]', N'PostalCode_PK', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Altering [dbo].[Territory]...';


GO
ALTER TABLE [dbo].[Territory] ALTER COLUMN [countryCode] NVARCHAR (3) NOT NULL;


GO
PRINT N'***Hack #6***  Starting rebuilding table [dbo].[TraitGroup]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_TraitGroup] (
    [traitGroupID]   INT            IDENTITY (1, 1) NOT NULL,
    [traitGroupCode] NVARCHAR (3)   NOT NULL,
    [traitGroupDesc] NVARCHAR (255) NULL,
    CONSTRAINT [tmp_ms_xx_constraint_TraitGroup_PK] PRIMARY KEY CLUSTERED ([traitGroupID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [tmp_ms_xx_constraint_AK_traitGroupCode_traitGroupCode] UNIQUE NONCLUSTERED ([traitGroupCode] ASC) WITH (FILLFACTOR = 80)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[TraitGroup])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_TraitGroup] ON;
        --INSERT INTO [dbo].[tmp_ms_xx_TraitGroup] ([traitGroupID], [traitGroupCode], [traitGroupDesc])
        --SELECT   [traitGroupID],
        --         [traitGroupDesc]
        --FROM     [dbo].[TraitGroup]
        --ORDER BY [traitGroupID] ASC;
        INSERT INTO [dbo].[tmp_ms_xx_TraitGroup] ([traitGroupID], [traitGroupCode], [traitGroupDesc]) VALUES (1,'IA', N'Item Attributes')
        INSERT INTO [dbo].[tmp_ms_xx_TraitGroup] ([traitGroupID], [traitGroupCode], [traitGroupDesc]) VALUES (2,'ILA', N'Item-Locale Attributes')
        INSERT INTO [dbo].[tmp_ms_xx_TraitGroup] ([traitGroupID], [traitGroupCode], [traitGroupDesc]) VALUES (3,'PA', N'Price Attributes')
        INSERT INTO [dbo].[tmp_ms_xx_TraitGroup] ([traitGroupID], [traitGroupCode], [traitGroupDesc]) VALUES (4,'ECA', N'eCommerce Attributes')
        INSERT INTO [dbo].[tmp_ms_xx_TraitGroup] ([traitGroupID], [traitGroupCode], [traitGroupDesc]) VALUES (5,'LT', N'Locale Traits')
        INSERT INTO [dbo].[tmp_ms_xx_TraitGroup] ([traitGroupID], [traitGroupCode], [traitGroupDesc]) VALUES (6,'HT', N'History Traits')
        INSERT INTO [dbo].[tmp_ms_xx_TraitGroup] ([traitGroupID], [traitGroupCode], [traitGroupDesc]) VALUES (7,'HYT', N'Hierarchy Traits')
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_TraitGroup] OFF;
    END

DROP TABLE [dbo].[TraitGroup];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_TraitGroup]', N'TraitGroup';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_TraitGroup_PK]', N'TraitGroup_PK', N'OBJECT';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_AK_traitGroupCode_traitGroupCode]', N'AK_traitGroupCode_traitGroupCode', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO

/*
The column [dbo].[Trait].[traitCode] on table [dbo].[Trait] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/
GO
PRINT N'***Hack #7***  Starting rebuilding table [dbo].[Trait]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Trait] (
    [traitID]      INT            IDENTITY (1, 1) NOT NULL,
    [traitCode]    NVARCHAR (3)   NOT NULL,
    [traitPattern] NVARCHAR (255) NOT NULL,
    [traitDesc]    NVARCHAR (255) NULL,
    [traitGroupID] INT            NULL,
    CONSTRAINT [tmp_ms_xx_constraint_Trait_PK] PRIMARY KEY CLUSTERED ([traitID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [tmp_ms_xx_constraint_AK_traitCode_traitCode] UNIQUE NONCLUSTERED ([traitCode] ASC) WITH (FILLFACTOR = 80)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Trait])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Trait] ON;
        --INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitPattern], [traitDesc], [traitGroupID])
        --SELECT   [traitID],
        --         [traitPattern],
        --         [traitDesc],
        --         [traitGroupID]
        --FROM     [dbo].[Trait]
        --ORDER BY [traitID] ASC;
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('0','PRD', N'^[a-zA-Z0-9_]*$', N'Product Description', (select traitGroupID from traitgroup where traitGroupCode = 'IA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('1','POS', N'^[a-zA-Z0-9_]*$', N'POS Description', (select traitGroupID from traitgroup where traitGroupCode = 'IA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('2','PKG', N'^[0-9]*\.?[0-9]+$', N'Package Unit', (select traitGroupID from traitgroup where traitGroupCode = 'IA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('3','FSE', N'0|1', N'Food Stamp Eligible', (select traitGroupID from traitgroup where traitGroupCode = 'IA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('4','SCT', N'0|1', N'POS Scale Tare', (select traitGroupID from traitgroup where traitGroupCode = 'IA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('5','DPT', N'0|1', N'Department Sale', (select traitGroupID from traitgroup where traitGroupCode = 'IA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('6','GFT', N'0|1', N'Gift Card', (select traitGroupID from traitgroup where traitGroupCode = 'IA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('7','RSZ', N'^[0-9]*\.?[0-9]+$', N'Retail Size', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('8','RUM', N'^[0-9]*\.?[0-9]+$', N'Retail UOM', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('9','TMD', N'0|1', N'TM Discount Eligible', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('10','CSD', N'0|1', N'Case Discount Eligible', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('11','PRH', N'0|1', N'Prohibit Discount', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('12','AGE', N'^[0-9]*\.?[0-9]+$', N'Age Restrict', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('13','RCL', N'0|1', N'Recall', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('14','RES', N'^[0-9]*\.?[0-9]+$', N'Restricted Hours', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('15','SBW', N'0|1', N'Sold by Weight', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('16','FCT', N'0|1', N'Force Tare', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('17','QTY', N'0|1', N'Quantity Required', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('18','PRQ', N'0|1', N'Price Required', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('19','QPR', N'^[0-9]*\.?[0-9]+$', N'Quantity Prohibit', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('20','VV', N'0|1', N'Visual Verify', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('21','RS', N'0|1', N'Restrict Sale', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('22','NA', N'0|1', N'Not Authorized For Sale', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('23','DEL', N'0|1', N'Delete', (select traitGroupID from traitgroup where traitGroupCode = 'ILA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('24','LOC', N'^[0-9]*\.?[0-9]+$', N'Locale', (select traitGroupID from traitgroup where traitGroupCode = 'PA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('25','PRC', N'^[0-9]*\.?[0-9]+$', N'Price', (select traitGroupID from traitgroup where traitGroupCode = 'PA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('26','PM', N'^[0-9]*\.?[0-9]+$', N'Price Multiple', (select traitGroupID from traitgroup where traitGroupCode = 'PA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('27','ST', N'^(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d$', N'Price Start Date', (select traitGroupID from traitgroup where traitGroupCode = 'PA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('28','END', N'^(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d$', N'Price End Date', (select traitGroupID from traitgroup where traitGroupCode = 'PA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('29','SHT', N'^[a-zA-Z0-9_]*$', N'Short Romance', (select traitGroupID from traitgroup where traitGroupCode = 'ECA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('30','LNG', N'^[a-zA-Z0-9_]*$', N'Long Romance', (select traitGroupID from traitgroup where traitGroupCode = 'ECA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('31','GF', N'0|1', N'Gluten Free', (select traitGroupID from traitgroup where traitGroupCode = 'ECA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('32','PBC', N'0|1', N'Premium Body Care', (select traitGroupID from traitgroup where traitGroupCode = 'ECA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('33','EX', N'0|1', N'Exclusive', (select traitGroupID from traitgroup where traitGroupCode = 'ECA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('34','WT', N'0|1', N'Whole Trade', (select traitGroupID from traitgroup where traitGroupCode = 'ECA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('35','NGM', N'0|1', N'Non GMO', (select traitGroupID from traitgroup where traitGroupCode = 'ECA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('36','HSH', N'0|1', N'HSH', (select traitGroupID from traitgroup where traitGroupCode = 'ECA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('37','E2', N'0|1', N'E2', (select traitGroupID from traitgroup where traitGroupCode = 'ECA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('38','VGN', N'0|1', N'Vegan', (select traitGroupID from traitgroup where traitGroupCode = 'ECA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('39','VEG', N'0|1', N'Vegetarian', (select traitGroupID from traitgroup where traitGroupCode = 'ECA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('40','KSH', N'0|1', N'Kosher', (select traitGroupID from traitgroup where traitGroupCode = 'ECA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('41','ECO', N'Baseline|Premium|Ultra-Premium', N'ECO Scale Rating', (select traitGroupID from traitgroup where traitGroupCode = 'ECA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('42','OG', N'0|1', N'Organic', (select traitGroupID from traitgroup where traitGroupCode = 'ECA'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('43','ABB', N'^[a-zA-Z0-9_]*$', N'Region Abbreviation', (select traitGroupID from traitgroup where traitGroupCode = 'LT'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('44','BU', N'^[a-zA-Z0-9_]*$', N'PS Business Unit ID', (select traitGroupID from traitgroup where traitGroupCode = 'LT'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('45','VER', N'^[0-9]*\.?[0-9]+$', N'ScanCode Version', (select traitGroupID from traitgroup where traitGroupCode = 'HT'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('46','INS', N'^(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d$', N'Insert Date', (select traitGroupID from traitgroup where traitGroupCode = 'HT'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('47','MOD', N'^(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d$', N'Modified Date', (select traitGroupID from traitgroup where traitGroupCode = 'HT'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('48','VAL', N'^(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d$', N'Validation Date', (select traitGroupID from traitgroup where traitGroupCode = 'HT'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('49','MFM', N'^[a-zA-Z0-9_]*$', N'Merch Fin Mapping', (select traitGroupID from traitgroup where traitGroupCode = 'HT'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('50','GL', N'^[a-zA-Z0-9_]*$', N'GL Account', (select traitGroupID from traitgroup where traitGroupCode = 'HT'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('51','ABR', N'^[a-zA-Z0-9_]*$', N'Tax Abbreviation', (select traitGroupID from traitgroup where traitGroupCode = 'HT'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('52','SBC', N'^[a-zA-Z0-9_]*$', N'Sub Brick Code', (select traitGroupID from traitgroup where traitGroupCode = 'HT'))
INSERT INTO [dbo].[tmp_ms_xx_Trait] ([traitID], [traitCode], [traitPattern], [traitDesc], [traitGroupID]) VALUES ('53','FIN', N'^[a-zA-Z0-9_]*$', N'Financial Hierarchy Code', (select traitGroupID from traitgroup where traitGroupCode = 'HT'))
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Trait] OFF;
    END

DROP TABLE [dbo].[Trait];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Trait]', N'Trait';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_Trait_PK]', N'Trait_PK', N'OBJECT';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_AK_traitCode_traitCode]', N'AK_traitCode_traitCode', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
/*
The column [dbo].[TraitGroup].[traitGroupCode] on table [dbo].[TraitGroup] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/
GO
/*
The column [dbo].[UOM].[uomCode] on table [dbo].[UOM] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The type for column uomID in table [dbo].[UOM] is currently  NVARCHAR (5) NOT NULL but is being changed to  INT NOT NULL. Data loss could occur.
*/
GO
PRINT N'Starting rebuilding table [dbo].[UOM]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_UOM] (
    [uomID]   INT            NOT NULL,
    [uomCode] NVARCHAR (3)   NOT NULL,
    [uomName] NVARCHAR (100) NULL,
    CONSTRAINT [tmp_ms_xx_constraint_UOM_PK] PRIMARY KEY CLUSTERED ([uomID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [tmp_ms_xx_constraint_AK_uomCode_uomCode] UNIQUE NONCLUSTERED ([uomCode] ASC) WITH (FILLFACTOR = 80)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[UOM])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_UOM] ([uomID], [uomName])
        SELECT   [uomID],
                 [uomName]
        FROM     [dbo].[UOM]
        ORDER BY [uomID] ASC;
    END

DROP TABLE [dbo].[UOM];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_UOM]', N'UOM';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_UOM_PK]', N'UOM_PK', N'OBJECT';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_AK_uomCode_uomCode]', N'AK_uomCode_uomCode', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [app].[AppConfig]...';


GO
CREATE TABLE [app].[AppConfig] (
    [Id]            INT            IDENTITY (1, 1) NOT NULL,
    [Region]        NVARCHAR (2)   NOT NULL,
    [Configuration] NVARCHAR (255) NOT NULL,
    [Enabled]       BIT            NOT NULL,
    CONSTRAINT [PK_Id] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80)
);


GO
PRINT N'***Hack #8***  Changing dbo.plumap to [app].[PLUMap]...';

ALTER SCHEMA app TRANSFER [dbo].[PLUMap]
--GO
--CREATE TABLE [app].[PLUMap] (
--    [itemID] INT           NOT NULL,
--    [flPLU]  NVARCHAR (11) NULL,
--    [maPLU]  NVARCHAR (11) NULL,
--    [mwPLU]  NVARCHAR (11) NULL,
--    [naPLU]  NVARCHAR (11) NULL,
--    [ncPLU]  NVARCHAR (11) NULL,
--    [nePLU]  NVARCHAR (11) NULL,
--    [pnPLU]  NVARCHAR (11) NULL,
--    [rmPLU]  NVARCHAR (11) NULL,
--    [soPLU]  NVARCHAR (11) NULL,
--    [spPLU]  NVARCHAR (11) NULL,
--    [swPLU]  NVARCHAR (11) NULL,
--    [ukPLU]  NVARCHAR (11) NULL,
--    CONSTRAINT [PLUMap_PK] PRIMARY KEY CLUSTERED ([itemID] ASC) WITH (FILLFACTOR = 80)
--);


--GO
PRINT N'Creating [dbo].[HierarchyClassTrait]...';


GO
CREATE TABLE [dbo].[HierarchyClassTrait] (
    [traitID]          INT            NOT NULL,
    [hierarchyClassID] INT            NOT NULL,
    [uomID]            INT            NULL,
    [traitValue]       NVARCHAR (255) NULL,
    CONSTRAINT [HierarchyClassTrait_PK] PRIMARY KEY CLUSTERED ([traitID] ASC, [hierarchyClassID] ASC) WITH (FILLFACTOR = 80)
);


GO
PRINT N'Creating [dbo].[ItemGroupTrait]...';


GO
CREATE TABLE [dbo].[ItemGroupTrait] (
    [traitID]     INT            NOT NULL,
    [itemGroupID] INT            NOT NULL,
    [uomID]       INT            NULL,
    [traitValue]  NVARCHAR (255) NULL,
    CONSTRAINT [ItemGroupTrait_PK] PRIMARY KEY CLUSTERED ([traitID] ASC, [ItemGroupID] ASC) WITH (FILLFACTOR = 80)
);


GO
PRINT N'Creating Country_PhysicalAddress_FK1...';


GO
ALTER TABLE [dbo].[PhysicalAddress] WITH NOCHECK
    ADD CONSTRAINT [Country_PhysicalAddress_FK1] FOREIGN KEY ([countryCode]) REFERENCES [dbo].[Country] ([countryCode]);


GO
PRINT N'Creating Country_PostalCode_FK1...';


GO
ALTER TABLE [dbo].[PostalCode] WITH NOCHECK
    ADD CONSTRAINT [Country_PostalCode_FK1] FOREIGN KEY ([countryCode]) REFERENCES [dbo].[Country] ([countryCode]);


GO
PRINT N'Creating Country_Territory_FK1...';


GO
ALTER TABLE [dbo].[Territory] WITH NOCHECK
    ADD CONSTRAINT [Country_Territory_FK1] FOREIGN KEY ([countryCode]) REFERENCES [dbo].[Country] ([countryCode]);


GO
PRINT N'Creating CurrencyType_ItemPrice_FK1...';


GO
ALTER TABLE [dbo].[ItemPrice] WITH NOCHECK
    ADD CONSTRAINT [CurrencyType_ItemPrice_FK1] FOREIGN KEY ([currencyTypeID]) REFERENCES [dbo].[CurrencyType] ([currencyTypeID]);


GO
PRINT N'Creating UOM_ItemPrice_FK1...';


GO
ALTER TABLE [dbo].[ItemPrice] WITH NOCHECK
    ADD CONSTRAINT [UOM_ItemPrice_FK1] FOREIGN KEY ([uomID]) REFERENCES [dbo].[UOM] ([uomID]);


GO
PRINT N'Creating ItemPriceType_ItemPrice_FK1...';


GO
ALTER TABLE [dbo].[ItemPrice] WITH NOCHECK
    ADD CONSTRAINT [ItemPriceType_ItemPrice_FK1] FOREIGN KEY ([itemPriceTypeID]) REFERENCES [dbo].[ItemPriceType] ([itemPriceTypeID]);


GO
PRINT N'Creating UOM_ItemTrait_FK1...';


GO
ALTER TABLE [dbo].[ItemTrait] WITH NOCHECK
    ADD CONSTRAINT [UOM_ItemTrait_FK1] FOREIGN KEY ([uomID]) REFERENCES [dbo].[UOM] ([uomID]);


GO
PRINT N'Creating ItemType_Item_FK1...';


GO
ALTER TABLE [dbo].[Item] WITH NOCHECK
    ADD CONSTRAINT [ItemType_Item_FK1] FOREIGN KEY ([itemTypeID]) REFERENCES [dbo].[ItemType] ([itemTypeID]);


GO
PRINT N'Creating UOM_LocaleTrait_FK1...';


GO
ALTER TABLE [dbo].[LocaleTrait] WITH NOCHECK
    ADD CONSTRAINT [UOM_LocaleTrait_FK1] FOREIGN KEY ([uomID]) REFERENCES [dbo].[UOM] ([uomID]);


GO
PRINT N'Creating LocaleType_Locale_FK1...';


GO
ALTER TABLE [dbo].[Locale] WITH NOCHECK
    ADD CONSTRAINT [LocaleType_Locale_FK1] FOREIGN KEY ([localeTypeID]) REFERENCES [dbo].[LocaleType] ([localeTypeID]);


GO
PRINT N'Creating Organization_Locale_FK1...';


GO
ALTER TABLE [dbo].[Locale] WITH NOCHECK
    ADD CONSTRAINT [Organization_Locale_FK1] FOREIGN KEY ([ownerOrgPartyID]) REFERENCES [dbo].[Organization] ([orgPartyID]);


GO
PRINT N'Creating Party_Organization_FK1...';


GO
ALTER TABLE [dbo].[Organization] WITH NOCHECK
    ADD CONSTRAINT [Party_Organization_FK1] FOREIGN KEY ([orgPartyID]) REFERENCES [dbo].[Party] ([partyID]);


GO
PRINT N'Creating Organization_Organization_FK1...';


GO
ALTER TABLE [dbo].[Organization] WITH NOCHECK
    ADD CONSTRAINT [Organization_Organization_FK1] FOREIGN KEY ([parentOrgPartyID]) REFERENCES [dbo].[Organization] ([orgPartyID]);


GO
PRINT N'Creating OrganizationType_Organization_FK1...';


GO
ALTER TABLE [dbo].[Organization] WITH NOCHECK
    ADD CONSTRAINT [OrganizationType_Organization_FK1] FOREIGN KEY ([orgTypeID]) REFERENCES [dbo].[OrganizationType] ([orgTypeID]);


GO
PRINT N'Creating Organization_OrganizationName_FK1...';


GO
ALTER TABLE [dbo].[OrganizationName] WITH NOCHECK
    ADD CONSTRAINT [Organization_OrganizationName_FK1] FOREIGN KEY ([orgPartyID]) REFERENCES [dbo].[Organization] ([orgPartyID]);


GO
PRINT N'Creating PartyType_Party_FK1...';


GO
ALTER TABLE [dbo].[Party] WITH NOCHECK
    ADD CONSTRAINT [PartyType_Party_FK1] FOREIGN KEY ([partyTypeID]) REFERENCES [dbo].[PartyType] ([partyTypeID]);


GO
PRINT N'Creating PostalCode_PhysicalAddress_FK1...';


GO
ALTER TABLE [dbo].[PhysicalAddress] WITH NOCHECK
    ADD CONSTRAINT [PostalCode_PhysicalAddress_FK1] FOREIGN KEY ([postalCode], [countryCode]) REFERENCES [dbo].[PostalCode] ([postalCode], [countryCode]);


GO
PRINT N'Creating County_PostalCode_FK1...';


GO
ALTER TABLE [dbo].[PostalCode] WITH NOCHECK
    ADD CONSTRAINT [County_PostalCode_FK1] FOREIGN KEY ([countyCode]) REFERENCES [dbo].[County] ([countyCode]);


GO
PRINT N'Creating Trait_ItemTrait_FK1...';


GO
ALTER TABLE [dbo].[ItemTrait] WITH NOCHECK
    ADD CONSTRAINT [Trait_ItemTrait_FK1] FOREIGN KEY ([traitID]) REFERENCES [dbo].[Trait] ([traitID]);


GO
PRINT N'Creating Trait_LocaleTrait_FK1...';


GO
ALTER TABLE [dbo].[LocaleTrait] WITH NOCHECK
    ADD CONSTRAINT [Trait_LocaleTrait_FK1] FOREIGN KEY ([traitID]) REFERENCES [dbo].[Trait] ([traitID]);


GO
PRINT N'Creating TraitGroup_Trait_FK1...';


GO
ALTER TABLE [dbo].[Trait] WITH NOCHECK
    ADD CONSTRAINT [TraitGroup_Trait_FK1] FOREIGN KEY ([traitGroupID]) REFERENCES [dbo].[TraitGroup] ([traitGroupID]);


GO
PRINT N'***Hack #9***  Skipping: Creating Item_PLUMap_ItemID_FK...';


--GO
--ALTER TABLE [app].[PLUMap] WITH NOCHECK
--    ADD CONSTRAINT [Item_PLUMap_ItemID_FK] FOREIGN KEY ([itemID]) REFERENCES [dbo].[Item] ([itemID]);


GO
PRINT N'Creating UOM_HierarchyClassTrait_FK1...';


GO
ALTER TABLE [dbo].[HierarchyClassTrait] WITH NOCHECK
    ADD CONSTRAINT [UOM_HierarchyClassTrait_FK1] FOREIGN KEY ([uomID]) REFERENCES [dbo].[UOM] ([uomID]);


GO
PRINT N'Creating Trait_HierarchyClassTrait_FK1...';


GO
ALTER TABLE [dbo].[HierarchyClassTrait] WITH NOCHECK
    ADD CONSTRAINT [Trait_HierarchyClassTrait_FK1] FOREIGN KEY ([traitID]) REFERENCES [dbo].[Trait] ([traitID]);


GO
PRINT N'Creating HierarchyClass_HierarchyClassTrait_FK1...';


GO
ALTER TABLE [dbo].[HierarchyClassTrait] WITH NOCHECK
    ADD CONSTRAINT [HierarchyClass_HierarchyClassTrait_FK1] FOREIGN KEY ([HierarchyClassID]) REFERENCES [dbo].[HierarchyClass] ([hierarchyClassID]);


GO
PRINT N'Creating UOM_ItemGroupTrait_FK1...';


GO
ALTER TABLE [dbo].[ItemGroupTrait] WITH NOCHECK
    ADD CONSTRAINT [UOM_ItemGroupTrait_FK1] FOREIGN KEY ([uomID]) REFERENCES [dbo].[UOM] ([uomID]);


GO
PRINT N'Creating Trait_ItemGroupTrait_FK1...';


GO
ALTER TABLE [dbo].[ItemGroupTrait] WITH NOCHECK
    ADD CONSTRAINT [Trait_ItemGroupTrait_FK1] FOREIGN KEY ([traitID]) REFERENCES [dbo].[Trait] ([traitID]);


GO
PRINT N'Creating ItemGroup_ItemGroupTrait_FK1...';


GO
ALTER TABLE [dbo].[ItemGroupTrait] WITH NOCHECK
    ADD CONSTRAINT [ItemGroup_ItemGroupTrait_FK1] FOREIGN KEY ([ItemGroupID]) REFERENCES [dbo].[ItemGroup] ([itemGroupID]);


--GO
PRINT N'***Hack #10 - 14 ***  SKIPPING THE Refresh of Views like: Refreshing [app].[vItemBase]...';


--GO
--EXECUTE sp_refreshsqlmodule N'[app].[vItemBase]';


--GO
--PRINT N'Refreshing [app].[vItemImport]...';


--GO
--EXECUTE sp_refreshsqlmodule N'[app].[vItemImport]';


--GO
--PRINT N'Refreshing [app].[vItemsAndTraits]...';


--GO
--EXECUTE sp_refreshsqlmodule N'[app].[vItemsAndTraits]';


--GO
--PRINT N'Refreshing [app].[UpdateItemListByTrait]...';


--GO
--EXECUTE sp_refreshsqlmodule N'[app].[UpdateItemListByTrait]';


--GO
--PRINT N'Refreshing [app].[ItemImport]...';


--GO
--EXECUTE sp_refreshsqlmodule N'[app].[ItemImport]';


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[PhysicalAddress] WITH CHECK CHECK CONSTRAINT [Country_PhysicalAddress_FK1];

ALTER TABLE [dbo].[PostalCode] WITH CHECK CHECK CONSTRAINT [Country_PostalCode_FK1];

ALTER TABLE [dbo].[Territory] WITH CHECK CHECK CONSTRAINT [Country_Territory_FK1];

ALTER TABLE [dbo].[ItemPrice] WITH CHECK CHECK CONSTRAINT [CurrencyType_ItemPrice_FK1];

ALTER TABLE [dbo].[ItemPrice] WITH CHECK CHECK CONSTRAINT [UOM_ItemPrice_FK1];

ALTER TABLE [dbo].[ItemPrice] WITH CHECK CHECK CONSTRAINT [ItemPriceType_ItemPrice_FK1];

ALTER TABLE [dbo].[ItemTrait] WITH CHECK CHECK CONSTRAINT [UOM_ItemTrait_FK1];

ALTER TABLE [dbo].[Item] WITH CHECK CHECK CONSTRAINT [ItemType_Item_FK1];

ALTER TABLE [dbo].[LocaleTrait] WITH CHECK CHECK CONSTRAINT [UOM_LocaleTrait_FK1];

ALTER TABLE [dbo].[Locale] WITH CHECK CHECK CONSTRAINT [LocaleType_Locale_FK1];

ALTER TABLE [dbo].[Locale] WITH CHECK CHECK CONSTRAINT [Organization_Locale_FK1];

ALTER TABLE [dbo].[Organization] WITH CHECK CHECK CONSTRAINT [Party_Organization_FK1];

ALTER TABLE [dbo].[Organization] WITH CHECK CHECK CONSTRAINT [Organization_Organization_FK1];

ALTER TABLE [dbo].[Organization] WITH CHECK CHECK CONSTRAINT [OrganizationType_Organization_FK1];

ALTER TABLE [dbo].[OrganizationName] WITH CHECK CHECK CONSTRAINT [Organization_OrganizationName_FK1];

ALTER TABLE [dbo].[Party] WITH CHECK CHECK CONSTRAINT [PartyType_Party_FK1];

ALTER TABLE [dbo].[PhysicalAddress] WITH CHECK CHECK CONSTRAINT [PostalCode_PhysicalAddress_FK1];

ALTER TABLE [dbo].[PostalCode] WITH CHECK CHECK CONSTRAINT [County_PostalCode_FK1];

ALTER TABLE [dbo].[ItemTrait] WITH CHECK CHECK CONSTRAINT [Trait_ItemTrait_FK1];

ALTER TABLE [dbo].[LocaleTrait] WITH CHECK CHECK CONSTRAINT [Trait_LocaleTrait_FK1];

ALTER TABLE [dbo].[Trait] WITH CHECK CHECK CONSTRAINT [TraitGroup_Trait_FK1];

ALTER TABLE [app].[PLUMap] WITH CHECK CHECK CONSTRAINT [Item_PLUMap_ItemID_FK];

ALTER TABLE [dbo].[HierarchyClassTrait] WITH CHECK CHECK CONSTRAINT [UOM_HierarchyClassTrait_FK1];

ALTER TABLE [dbo].[HierarchyClassTrait] WITH CHECK CHECK CONSTRAINT [Trait_HierarchyClassTrait_FK1];

ALTER TABLE [dbo].[HierarchyClassTrait] WITH CHECK CHECK CONSTRAINT [HierarchyClass_HierarchyClassTrait_FK1];

ALTER TABLE [dbo].[ItemGroupTrait] WITH CHECK CHECK CONSTRAINT [UOM_ItemGroupTrait_FK1];

ALTER TABLE [dbo].[ItemGroupTrait] WITH CHECK CHECK CONSTRAINT [Trait_ItemGroupTrait_FK1];

ALTER TABLE [dbo].[ItemGroupTrait] WITH CHECK CHECK CONSTRAINT [ItemGroup_ItemGroupTrait_FK1];


GO
PRINT N'Update complete.';


GO
USE [$(DatabaseName)];


GO
--PRINT N'Dropping [dbo].[ItemTrait].[IX_ItemTrait_ItemID_INC_TraitIDAndValue]...';
--GO
--DROP INDEX [IX_ItemTrait_ItemID_INC_TraitIDAndValue]
--    ON [dbo].[ItemTrait];
--GO

PRINT N'Dropping Locale_ItemTrait_FK1...';
GO
ALTER TABLE [dbo].[ItemTrait] DROP CONSTRAINT [Locale_ItemTrait_FK1];
GO

PRINT N'Dropping UOM_ItemTrait_FK1...';
GO
ALTER TABLE [dbo].[ItemTrait] DROP CONSTRAINT [UOM_ItemTrait_FK1];
GO

PRINT N'Dropping Item_ItemTrait_FK1...';
GO
ALTER TABLE [dbo].[ItemTrait] DROP CONSTRAINT [Item_ItemTrait_FK1];
GO

PRINT N'Dropping Trait_ItemTrait_FK1...';
GO
ALTER TABLE [dbo].[ItemTrait] DROP CONSTRAINT [Trait_ItemTrait_FK1];
GO
/*
The column localeID on table [dbo].[ItemTrait] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/
GO
PRINT N'Starting rebuilding table [dbo].[ItemTrait]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_ItemTrait] (
    [traitID]    INT            NOT NULL,
    [itemID]     INT            NOT NULL,
    [uomID]      NVARCHAR (5)   NULL,
    [traitValue] NVARCHAR (255) NULL,
    [localeID]   INT            NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_ItemTrait_PK] PRIMARY KEY CLUSTERED ([traitID] ASC, [itemID] ASC, [localeID] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[ItemTrait])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_ItemTrait] ([traitID], [itemID], [localeID], [uomID], [traitValue])
        SELECT   [traitID],
                 [itemID],
                 1 as [localeID],
                 [uomID],
                 [traitValue]
        FROM     [dbo].[ItemTrait]
        ORDER BY [traitID] ASC, [itemID] ASC, [localeID] ASC;
    END

DROP TABLE [dbo].[ItemTrait];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_ItemTrait]', N'ItemTrait';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_ItemTrait_PK]', N'ItemTrait_PK', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating Locale_ItemTrait_FK1...';


GO
ALTER TABLE [dbo].[ItemTrait] WITH NOCHECK
    ADD CONSTRAINT [Locale_ItemTrait_FK1] FOREIGN KEY ([localeID]) REFERENCES [dbo].[Locale] ([localeID]);


GO
PRINT N'Creating Item_ItemTrait_FK1...';


GO
ALTER TABLE [dbo].[ItemTrait] WITH NOCHECK
    ADD CONSTRAINT [Item_ItemTrait_FK1] FOREIGN KEY ([itemID]) REFERENCES [dbo].[Item] ([itemID]);


GO
PRINT N'Creating Trait_ItemTrait_FK1...';


GO
ALTER TABLE [dbo].[ItemTrait] WITH NOCHECK
    ADD CONSTRAINT [Trait_ItemTrait_FK1] FOREIGN KEY ([traitID]) REFERENCES [dbo].[Trait] ([traitID]);


GO
GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[ItemTrait] WITH CHECK CHECK CONSTRAINT [Locale_ItemTrait_FK1];

ALTER TABLE [dbo].[ItemTrait] WITH CHECK CHECK CONSTRAINT [Item_ItemTrait_FK1];

ALTER TABLE [dbo].[ItemTrait] WITH CHECK CHECK CONSTRAINT [Trait_ItemTrait_FK1];


GO
PRINT N'Update complete.';


GO
