'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Distribution_FacilityOrderReport

    '''<summary>
    '''cmbFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFacility As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''IC_Facility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IC_Facility As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''rngValid_cmbStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngValid_cmbStore As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''dteBeginDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteBeginDate As Global.Infragistics.WebUI.WebSchedule.WebDateChooser

    '''<summary>
    '''reqfld_BeginDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqfld_BeginDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rngValid_BeginDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngValid_BeginDate As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''dteEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteEndDate As Global.Infragistics.WebUI.WebSchedule.WebDateChooser

    '''<summary>
    '''reqfld_EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqfld_EndDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rngValid_EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngValid_EndDate As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''comp_DateRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comp_DateRange As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''cmbPOStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPOStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkAll_Store control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAll_Store As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lbStoreList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbStoreList As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''IC_Store control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IC_Store As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''chkAll_SubTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAll_SubTeam As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lbSubTeamList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSubTeamList As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''IC_SubTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IC_SubTeam As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''optSortLevel1_Store control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optSortLevel1_Store As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''optSortLevel2_Store control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optSortLevel2_Store As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''optSortLevel3_Store control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optSortLevel3_Store As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''optSortLevel1_SubTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optSortLevel1_SubTeam As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''optSortLevel2_SubTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optSortLevel2_SubTeam As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''optSortLevel3_SubTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optSortLevel3_SubTeam As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''optSortLevel1_ExpectedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optSortLevel1_ExpectedDate As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''optSortLevel2_ExpectedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optSortLevel2_ExpectedDate As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''optSortLevel3_ExpectedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optSortLevel3_ExpectedDate As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblSortingError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSortingError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbReportFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbReportFormat As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport As Global.System.Web.UI.WebControls.Button
End Class
