//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irma.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IconItemLastChange
    {
        public int IconItemLastChangeId { get; set; }
        public string Identifier { get; set; }
        public Nullable<int> Subteam_No { get; set; }
        public Nullable<int> Brand_ID { get; set; }
        public string Item_Description { get; set; }
        public string POS_Description { get; set; }
        public Nullable<decimal> Package_Desc1 { get; set; }
        public Nullable<bool> Food_Stamps { get; set; }
        public Nullable<decimal> ScaleTare { get; set; }
        public Nullable<int> TaxClassID { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<bool> AreNutriFactsChanged { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> Package_Unit_ID { get; set; }
        public Nullable<decimal> Package_Desc2 { get; set; }
    }
}
