//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irma.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSignAttribute
    {
        public int ItemSignAttributeID { get; set; }
        public int Item_Key { get; set; }
        public string Locality { get; set; }
        public string SignRomanceTextLong { get; set; }
        public string SignRomanceTextShort { get; set; }
        public string AnimalWelfareRating { get; set; }
        public Nullable<bool> Biodynamic { get; set; }
        public string CheeseMilkType { get; set; }
        public Nullable<bool> CheeseRaw { get; set; }
        public string EcoScaleRating { get; set; }
        public Nullable<bool> GlutenFree { get; set; }
        public string HealthyEatingRating { get; set; }
        public Nullable<bool> Kosher { get; set; }
        public Nullable<bool> NonGmo { get; set; }
        public Nullable<bool> Organic { get; set; }
        public Nullable<bool> PremiumBodyCare { get; set; }
        public string ProductionClaims { get; set; }
        public string FreshOrFrozen { get; set; }
        public string SeafoodCatchType { get; set; }
        public Nullable<bool> Vegan { get; set; }
        public Nullable<bool> Vegetarian { get; set; }
        public Nullable<bool> WholeTrade { get; set; }
        public string UomRegulationChicagoBaby { get; set; }
        public Nullable<int> UomRegulationTagUom { get; set; }
        public Nullable<bool> Msc { get; set; }
        public Nullable<bool> GrassFed { get; set; }
        public Nullable<bool> PastureRaised { get; set; }
        public Nullable<bool> FreeRange { get; set; }
        public Nullable<bool> DryAged { get; set; }
        public Nullable<bool> AirChilled { get; set; }
        public Nullable<bool> MadeInHouse { get; set; }
        public Nullable<System.DateTime> Exclusive { get; set; }
        public Nullable<bool> ColorAdded { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
