//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irma.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemIdentifier
    {
        public int Identifier_ID { get; set; }
        public int Item_Key { get; set; }
        public string Identifier { get; set; }
        public byte Default_Identifier { get; set; }
        public byte Deleted_Identifier { get; set; }
        public byte Add_Identifier { get; set; }
        public byte Remove_Identifier { get; set; }
        public byte National_Identifier { get; set; }
        public string CheckDigit { get; set; }
        public string IdentifierType { get; set; }
        public Nullable<int> NumPluDigitsSentToScale { get; set; }
        public Nullable<bool> Scale_Identifier { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
