//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irma.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MammothItemLocaleChangeQueue
    {
        public int QueueID { get; set; }
        public int Item_Key { get; set; }
        public Nullable<int> Store_No { get; set; }
        public string Identifier { get; set; }
        public int EventTypeID { get; set; }
        public Nullable<int> EventReferenceID { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> ProcessFailedDate { get; set; }
        public Nullable<int> InProcessBy { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual MammothItemChangeEventType MammothItemChangeEventType { get; set; }
        public virtual Store Store { get; set; }
    }
}
