//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irma.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutriFacts
    {
        public NutriFacts()
        {
            this.ItemNutrition = new HashSet<ItemNutrition>();
            this.ItemScale = new HashSet<ItemScale>();
        }
    
        public int NutriFactsID { get; set; }
        public int Scale_LabelFormat_ID { get; set; }
        public Nullable<byte> ServingUnits { get; set; }
        public string Description { get; set; }
        public Nullable<int> ServingsPerPortion { get; set; }
        public Nullable<int> SizeWeight { get; set; }
        public Nullable<int> Calories { get; set; }
        public Nullable<int> CaloriesFat { get; set; }
        public Nullable<int> CaloriesSaturatedFat { get; set; }
        public string ServingPerContainer { get; set; }
        public Nullable<decimal> TotalFatWeight { get; set; }
        public Nullable<short> TotalFatPercentage { get; set; }
        public Nullable<decimal> SaturatedFatWeight { get; set; }
        public Nullable<short> SaturatedFatPercent { get; set; }
        public Nullable<decimal> PolyunsaturatedFat { get; set; }
        public Nullable<decimal> MonounsaturatedFat { get; set; }
        public Nullable<decimal> CholesterolWeight { get; set; }
        public Nullable<short> CholesterolPercent { get; set; }
        public Nullable<decimal> SodiumWeight { get; set; }
        public Nullable<short> SodiumPercent { get; set; }
        public Nullable<decimal> PotassiumWeight { get; set; }
        public Nullable<short> PotassiumPercent { get; set; }
        public Nullable<decimal> TotalCarbohydrateWeight { get; set; }
        public Nullable<short> TotalCarbohydratePercent { get; set; }
        public Nullable<decimal> DietaryFiberWeight { get; set; }
        public Nullable<short> DietaryFiberPercent { get; set; }
        public Nullable<decimal> SolubleFiber { get; set; }
        public Nullable<decimal> InsolubleFiber { get; set; }
        public Nullable<decimal> Sugar { get; set; }
        public Nullable<decimal> SugarAlcohol { get; set; }
        public Nullable<decimal> OtherCarbohydrates { get; set; }
        public Nullable<decimal> ProteinWeight { get; set; }
        public Nullable<short> ProteinPercent { get; set; }
        public Nullable<short> VitaminA { get; set; }
        public Nullable<short> Betacarotene { get; set; }
        public Nullable<short> VitaminC { get; set; }
        public Nullable<short> Calcium { get; set; }
        public Nullable<short> Iron { get; set; }
        public Nullable<short> VitaminD { get; set; }
        public Nullable<short> VitaminE { get; set; }
        public Nullable<short> Thiamin { get; set; }
        public Nullable<short> Riboflavin { get; set; }
        public Nullable<short> Niacin { get; set; }
        public Nullable<short> VitaminB6 { get; set; }
        public Nullable<short> Folate { get; set; }
        public Nullable<short> VitaminB12 { get; set; }
        public Nullable<short> Biotin { get; set; }
        public Nullable<short> PantothenicAcid { get; set; }
        public Nullable<short> Phosphorous { get; set; }
        public Nullable<short> Iodine { get; set; }
        public Nullable<short> Magnesium { get; set; }
        public Nullable<short> Zinc { get; set; }
        public Nullable<short> Copper { get; set; }
        public Nullable<decimal> Transfat { get; set; }
        public Nullable<int> CaloriesFromTransFat { get; set; }
        public Nullable<decimal> Om6Fatty { get; set; }
        public Nullable<decimal> Om3Fatty { get; set; }
        public Nullable<decimal> Starch { get; set; }
        public Nullable<short> Chloride { get; set; }
        public Nullable<short> Chromium { get; set; }
        public Nullable<short> VitaminK { get; set; }
        public Nullable<short> Manganese { get; set; }
        public Nullable<short> Molybdenum { get; set; }
        public Nullable<short> Selenium { get; set; }
        public string ServingSizeDesc { get; set; }
        public Nullable<decimal> TransfatWeight { get; set; }
        public Nullable<int> HshRating { get; set; }
        public Nullable<byte> OverwriteServingSizeFlag { get; set; }
        public string Descriptors { get; set; }
    
        public virtual ICollection<ItemNutrition> ItemNutrition { get; set; }
        public virtual ICollection<ItemScale> ItemScale { get; set; }
    }
}
