//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irma.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_SumByItem
    {
        public System.DateTime Date_Key { get; set; }
        public int Store_No { get; set; }
        public int Item_Key { get; set; }
        public int SubTeam_No { get; set; }
        public byte Price_Level { get; set; }
        public Nullable<int> Sales_Quantity { get; set; }
        public Nullable<int> Return_Quantity { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Sales_Amount { get; set; }
        public Nullable<decimal> Return_Amount { get; set; }
        public Nullable<decimal> Markdown_Amount { get; set; }
        public Nullable<decimal> Promotion_Amount { get; set; }
        public Nullable<decimal> Store_Coupon_Amount { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual SubTeam SubTeam { get; set; }
        public virtual Store Store { get; set; }
    }
}
