//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irma.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreSubTeam
    {
        public int Store_No { get; set; }
        public int Team_No { get; set; }
        public int SubTeam_No { get; set; }
        public decimal CasePriceDiscount { get; set; }
        public decimal CostFactor { get; set; }
        public Nullable<int> ICVID { get; set; }
        public Nullable<int> PS_Team_No { get; set; }
        public Nullable<int> PS_SubTeam_No { get; set; }
    
        public virtual SubTeam SubTeam { get; set; }
        public virtual Store Store { get; set; }
    }
}
