USE [master]
GO

/****** Object:  Database [POReports]    Script Date: 11/11/2013 12:32:51 PM ******/
CREATE DATABASE [POReports] ON  PRIMARY 
( NAME = N'POReports', FILENAME = N'Q:\SQL_DATA\POReports.mdf' , SIZE = 2376256KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'POReports_log', FILENAME = N'Q:\SQL_LOGS\POReports_log.ldf' , SIZE = 2214848KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [POReports] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [POReports].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [POReports] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [POReports] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [POReports] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [POReports] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [POReports] SET ARITHABORT OFF 
GO

ALTER DATABASE [POReports] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [POReports] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [POReports] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [POReports] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [POReports] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [POReports] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [POReports] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [POReports] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [POReports] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [POReports] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [POReports] SET  DISABLE_BROKER 
GO

ALTER DATABASE [POReports] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [POReports] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [POReports] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [POReports] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [POReports] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [POReports] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [POReports] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [POReports] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [POReports] SET  MULTI_USER 
GO

ALTER DATABASE [POReports] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [POReports] SET DB_CHAINING OFF 
GO

ALTER DATABASE [POReports] SET  READ_WRITE 
GO