CREATE TABLE [infor].[GpmConversionTprCancellations]
(
	[GUID] UNIQUEIDENTIFIER NOT NULL,
	ITEM_ID INT NOT NULL,
	STORE_NUMBER INT NOT NULL,
	PRICE SMALLMONEY NOT NULL,
	MULTIPLE TINYINT NOT NULL,
	SELLING_UOM NVARCHAR(3) NOT NULL,
	PRICE_TYPE_CODE NVARCHAR(3) NOT NULL,
	PRICE_ATTRIBUTE_CODE NVARCHAR(10) NOT NULL,
	TAG_EXPIRATION_DATE DATETIME2(0) NULL,
	START_DATE DATETIME2(0) NOT NULL,
	END_DATE DATETIME2(0) NULL,
	CREATED_DATE DATETIME2(0) NOT NULL,
	REGION_CODE NVARCHAR(2) NOT NULL,
	SCAN_CODE NVARCHAR(13) NOT NULL,
	REWARDS_PERCENT_OFF NVARCHAR(50) NULL
)
GO

CREATE INDEX [IX_GpmConversionTprCancellations_ITEM_ID_STORE_NUMBER] ON [infor].[GpmConversionTprCancellations] ([ITEM_ID] ASC, [STORE_NUMBER] ASC)
GO
