CREATE TABLE [dbo].[VIMRetailPriceFileLoad] (
    [UPC]           VARCHAR (26) NULL,
    [REGION]        VARCHAR (2)  NOT NULL,
    [PS_BU]         INT          NULL,
    [PRICEZONE]     INT          NULL,
    [POS_DEPT]      VARCHAR (5)  NULL,
    [REG_PRICE]     SMALLMONEY   NOT NULL,
    [REG_MULTIPLE]  TINYINT      NOT NULL,
    [EFF_PRICE]     SMALLMONEY   NOT NULL,
    [EFF_MULTIPLE]  TINYINT      NOT NULL,
    [EFF_PRICETYPE] VARCHAR (4)  NULL,
    [START_DATE]    VARCHAR (10) NULL,
    [END_DATE]      VARCHAR (10) NULL,
    [EFF_DATE]      VARCHAR (10) NULL,
    [PROMO_CODE]    VARCHAR (4)  NOT NULL
);


GO
CREATE CLUSTERED INDEX [idxVIMRetailPriceFileLoad]
    ON [dbo].[VIMRetailPriceFileLoad]([UPC] ASC, [REGION] ASC, [POS_DEPT] ASC, [REG_PRICE] ASC, [REG_MULTIPLE] ASC, [EFF_PRICE] ASC, [EFF_MULTIPLE] ASC, [EFF_PRICETYPE] ASC, [START_DATE] ASC, [END_DATE] ASC, [EFF_DATE] ASC, [PROMO_CODE] ASC) WITH (FILLFACTOR = 80);

