CREATE TABLE [dbo].[wfsc1] (
    [scale_upc]   CHAR (5)  NULL,
    [upcno]       CHAR (13) NULL,
    [desc1]       CHAR (32) NULL,
    [desc2]       CHAR (32) NULL,
    [desc3]       CHAR (32) NULL,
    [desc4]       CHAR (32) NULL,
    [dsc1_font]   SMALLINT  NULL,
    [dsc2_font]   SMALLINT  NULL,
    [dsc3_font]   SMALLINT  NULL,
    [dsc4_font]   SMALLINT  NULL,
    [label_frmt1] SMALLINT  NULL,
    [label_rot1]  SMALLINT  NULL,
    [label_frmt2] SMALLINT  NULL,
    [label_rot2]  SMALLINT  NULL,
    [forc_tare]   CHAR (1)  NULL,
    [logo_no]     SMALLINT  NULL,
    [mssg_no]     SMALLINT  NULL,
    [tray_no]     SMALLINT  NULL,
    [uf1]         CHAR (30) NULL,
    [uf2]         CHAR (30) NULL,
    [uf3]         CHAR (30) NULL,
    [uf4]         CHAR (30) NULL,
    [uf5]         INT       NULL,
    [uf6]         INT       NULL,
    [uf7]         INT       NULL,
    [uf8]         INT       NULL,
    [status]      CHAR (1)  NULL
);

