'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Item_ItemsMarkedIgnorePackUpdate

    '''<summary>
    '''ddlSubteam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSubteam As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Subteams control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Subteams As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ddlVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVendor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''GetVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetVendors As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cblVendorItemStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblVendorItemStatus As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''GetVendorItemStatuses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetVendorItemStatuses As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''chkDefaultIdentifier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDefaultIdentifier As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport As Global.System.Web.UI.WebControls.Button
End Class
