CREATE TABLE [irma].[ItemScale] (
    [Region]                    NCHAR (2)    NOT NULL,
    [ItemScale_ID]              INT          NOT NULL,
    [Item_Key]                  INT          NOT NULL,
    [Nutrifact_ID]              INT          NULL,
    [Scale_ExtraText_ID]        INT          NULL,
    [Scale_Tare_ID]             INT          NULL,
    [Scale_Alternate_Tare_ID]   INT          NULL,
    [Scale_LabelStyle_ID]       INT          NULL,
    [Scale_EatBy_ID]            INT          NULL,
    [Scale_Grade_ID]            INT          NULL,
    [Scale_RandomWeightType_ID] INT          NULL,
    [Scale_ScaleUOMUnit_ID]     INT          NULL,
    [Scale_FixedWeight]         VARCHAR (25) NULL,
    [Scale_ByCount]             INT          NULL,
    [ForceTare]                 BIT          CONSTRAINT [DF_ItemScale_ForceTare] DEFAULT ((0)) NOT NULL,
    [PrintBlankShelfLife]       BIT          CONSTRAINT [DF_ItemScale_PrintBlankShelfLife] DEFAULT ((0)) NOT NULL,
    [PrintBlankEatBy]           BIT          CONSTRAINT [DF_ItemScale_PrintBlankEatBy] DEFAULT ((0)) NOT NULL,
    [PrintBlankPackDate]        BIT          CONSTRAINT [DF_ItemScale_PrintBlankPackDate] DEFAULT ((0)) NOT NULL,
    [PrintBlankWeight]          BIT          CONSTRAINT [DF_ItemScale_PrintBlankWeight] DEFAULT ((0)) NOT NULL,
    [PrintBlankUnitPrice]       BIT          CONSTRAINT [DF_ItemScale_PrintBlankUnitPrice] DEFAULT ((0)) NOT NULL,
    [PrintBlankTotalPrice]      BIT          CONSTRAINT [DF_ItemScale_PrintBlankTotalPrice] DEFAULT ((0)) NOT NULL,
    [Scale_Description1]        VARCHAR (64) NULL,
    [Scale_Description2]        VARCHAR (64) NULL,
    [Scale_Description3]        VARCHAR (64) NULL,
    [Scale_Description4]        VARCHAR (64) NULL,
    [ShelfLife_Length]          SMALLINT     NULL,
    [Scale_Ingredient_ID]       INT          NULL,
    [Scale_Allergen_ID]         INT          NULL,
    CONSTRAINT [PK_ItemScale] PRIMARY KEY CLUSTERED ([Region] ASC, [ItemScale_ID] ASC) WITH (FILLFACTOR = 100)
);

