CREATE TABLE [irma].[ItemScaleOverride] (
    [Region]                    NCHAR (2)    NOT NULL,
    [Item_Key]                  INT          NOT NULL,
    [StoreJurisdictionID]       INT          NOT NULL,
    [Scale_Description1]        VARCHAR (64) NULL,
    [Scale_Description2]        VARCHAR (64) NULL,
    [Scale_Description3]        VARCHAR (64) NULL,
    [Scale_Description4]        VARCHAR (64) NULL,
    [Scale_ExtraText_ID]        INT          NULL,
    [Scale_Tare_ID]             INT          NULL,
    [Scale_LabelStyle_ID]       INT          NULL,
    [Scale_ScaleUOMUnit_ID]     INT          NULL,
    [Scale_RandomWeightType_ID] INT          NULL,
    [Scale_FixedWeight]         VARCHAR (25) NULL,
    [Scale_ByCount]             INT          NULL,
    [ShelfLife_Length]          SMALLINT     NULL,
    [ForceTare]                 BIT          NOT NULL,
    [Scale_Alternate_Tare_ID]   INT          NULL,
    [Scale_EatBy_ID]            INT          NULL,
    [Scale_Grade_ID]            INT          NULL,
    [PrintBlankShelfLife]       BIT          NOT NULL,
    [PrintBlankEatBy]           BIT          NOT NULL,
    [PrintBlankPackDate]        BIT          NOT NULL,
    [PrintBlankWeight]          BIT          NOT NULL,
    [PrintBlankUnitPrice]       BIT          NOT NULL,
    [PrintBlankTotalPrice]      BIT          NOT NULL,
    [Nutrifact_ID]              INT          NULL,
    CONSTRAINT [PK_ItemScaleOverride] PRIMARY KEY CLUSTERED ([Region] ASC, [Item_Key] ASC, [StoreJurisdictionID] ASC) WITH (FILLFACTOR = 100)
);

