CREATE TABLE [irma].[ItemAttribute] (
    [ItemAttribute_ID]    INT          NOT NULL,
    [Item_Key]            INT          NULL,
    [Check_Box_1]         BIT          DEFAULT ((0)) NULL,
    [Check_Box_2]         BIT          DEFAULT ((0)) NULL,
    [Check_Box_3]         BIT          DEFAULT ((0)) NULL,
    [Check_Box_4]         BIT          DEFAULT ((0)) NULL,
    [Check_Box_5]         BIT          DEFAULT ((0)) NULL,
    [Check_Box_6]         BIT          DEFAULT ((0)) NULL,
    [Check_Box_7]         BIT          DEFAULT ((0)) NULL,
    [Check_Box_8]         BIT          DEFAULT ((0)) NULL,
    [Check_Box_9]         BIT          DEFAULT ((0)) NULL,
    [Check_Box_10]        BIT          DEFAULT ((0)) NULL,
    [Check_Box_11]        BIT          DEFAULT ((0)) NULL,
    [Check_Box_12]        BIT          DEFAULT ((0)) NULL,
    [Check_Box_13]        BIT          DEFAULT ((0)) NULL,
    [Check_Box_14]        BIT          DEFAULT ((0)) NULL,
    [Check_Box_15]        BIT          DEFAULT ((0)) NULL,
    [Check_Box_16]        BIT          DEFAULT ((0)) NULL,
    [Check_Box_17]        BIT          DEFAULT ((0)) NULL,
    [Check_Box_18]        BIT          DEFAULT ((0)) NULL,
    [Check_Box_19]        BIT          DEFAULT ((0)) NULL,
    [Check_Box_20]        BIT          DEFAULT ((0)) NULL,
    [Text_1]              VARCHAR (50) NULL,
    [Text_2]              VARCHAR (50) NULL,
    [Text_3]              VARCHAR (50) NULL,
    [Text_4]              VARCHAR (50) NULL,
    [Text_5]              VARCHAR (50) NULL,
    [Text_6]              VARCHAR (50) NULL,
    [Text_7]              VARCHAR (50) NULL,
    [Text_8]              VARCHAR (50) NULL,
    [Text_9]              VARCHAR (50) NULL,
    [Text_10]             VARCHAR (50) NULL,
    [Date_Time_1]         DATETIME     NULL,
    [Date_Time_2]         DATETIME     NULL,
    [Date_Time_3]         DATETIME     NULL,
    [Date_Time_4]         DATETIME     NULL,
    [Date_Time_5]         DATETIME     NULL,
    [Date_Time_6]         DATETIME     NULL,
    [Date_Time_7]         DATETIME     NULL,
    [Date_Time_8]         DATETIME     NULL,
    [Date_Time_9]         DATETIME     NULL,
    [Date_Time_10]        DATETIME     NULL,
    [LastUpdateTimestamp] DATETIME     NULL,
    CONSTRAINT [PK_ItemAttribute] PRIMARY KEY CLUSTERED ([ItemAttribute_ID] ASC) WITH (FILLFACTOR = 100)
);

