CREATE TABLE [irma].[ItemSignAttribute] (
    [Region]                   NCHAR (2)      NOT NULL,
    [ItemSignAttributeID]      INT            NOT NULL,
    [Item_Key]                 INT            NOT NULL,
    [Locality]                 NVARCHAR (50)  NULL,
    [SignRomanceTextLong]      NVARCHAR (300) NULL,
    [SignRomanceTextShort]     NVARCHAR (140) NULL,
    [AnimalWelfareRating]      NVARCHAR (10)  NULL,
    [Biodynamic]               BIT            NULL,
    [CheeseMilkType]           NVARCHAR (40)  NULL,
    [CheeseRaw]                BIT            NULL,
    [EcoScaleRating]           NVARCHAR (30)  NULL,
    [GlutenFree]               BIT            NULL,
    [HealthyEatingRating]      NVARCHAR (10)  NULL,
    [Kosher]                   BIT            NULL,
    [NonGmo]                   BIT            NULL,
    [Organic]                  BIT            NULL,
    [PremiumBodyCare]          BIT            NULL,
    [ProductionClaims]         NVARCHAR (30)  NULL,
    [FreshOrFrozen]            NVARCHAR (30)  NULL,
    [SeafoodCatchType]         NVARCHAR (15)  NULL,
    [Vegan]                    BIT            NULL,
    [Vegetarian]               BIT            NULL,
    [WholeTrade]               BIT            NULL,
    [UomRegulationChicagoBaby] NVARCHAR (50)  NULL,
    [UomRegulationTagUom]      INT            NULL,
    [Msc]                      BIT            NULL,
    [GrassFed]                 BIT            NULL,
    [PastureRaised]            BIT            NULL,
    [FreeRange]                BIT            NULL,
    [DryAged]                  BIT            NULL,
    [AirChilled]               BIT            NULL,
    [MadeInHouse]              BIT            NULL,
    [Exclusive]                DATETIME       NULL,
    [ColorAdded]               BIT            NULL,
    CONSTRAINT [PK_ItemSignAttribute] PRIMARY KEY CLUSTERED ([Region] ASC, [ItemSignAttributeID] ASC) WITH (FILLFACTOR = 100)
);

