Public Class SubTeamBO
	Public Property SubTeamNo() As Integer
	Public Property SubTeamName() As String
	Public Property TeamNo() As Integer?
	Public Property SubTeamAbbreviation() As String
	Public Property DeptNo() As Integer?
	Public Property SubDeptNo() As Integer?
	Public Property BuyerUserId() As Integer?
	Public Property TargetMargin() As Single
	Public Property JDA() As Integer?
	Public Property GLPurchaseAcct() As Integer?
	Public Property GLDistributionAcct() As Integer?
	Public Property GLTransferAcct() As Integer?
	Public Property GLSalesAcct() As Integer?
	Public Property GLPackagingAcct() As Integer?
	Public Property GLSuppliesAcct() As Integer?
	Public Property TransferToMarkup() As Single?
	Public Property EXEWarehouseSent() As Boolean
	Public Property Retail() As Boolean
	Public Property InventoryCountByCase() As Boolean
	Public Property EXEDistributed() As Boolean
	Public Property ScaleDept() As Integer?
	Public Property SubTeamTypeId() As Integer?
	Public Property Distribution() As Boolean
	Public Property FixedSpoilage() As Boolean
	Public Property Beverage() As Boolean
	Public Property AlignedSubTeam() As Boolean
	Public Property IsDisabled As Boolean
	Public Property IsUnrestricted As Boolean
	Public Property PurchaseThresholdCouponAvailable As Boolean
	Public Property SubTeamDescription() As String
End Class