'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Distribution_QOHVendorPack

    '''<summary>
    '''cmbSubTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSubTeam As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''IC_SubTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IC_SubTeam As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''rngValid_cmbSubTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngValid_cmbSubTeam As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''cmbDCStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbDCStore As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''IC_DCStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IC_DCStore As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''rngValid_cmbDCStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngValid_cmbDCStore As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''cmbReportFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbReportFormat As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport As Global.System.Web.UI.WebControls.Button
End Class
