//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("", ClrNamespace="")]


[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="IcixUpdate", Namespace="")]
public partial class IcixUpdate : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private IcixUpdate.IncidentReportDetailsType IncidentReportDetailsField;
    
    private IcixUpdate.ProductInformationType ProductInformationField;
    
    private IcixUpdate.VendorInformationType VendorInformationField;
    
    private IcixUpdate.ClaimInformationType ClaimInformationField;
    
    private IcixUpdate.GFSSType GFSSField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
    public IcixUpdate.IncidentReportDetailsType IncidentReportDetails
    {
        get
        {
            return this.IncidentReportDetailsField;
        }
        set
        {
            this.IncidentReportDetailsField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
    public IcixUpdate.ProductInformationType ProductInformation
    {
        get
        {
            return this.ProductInformationField;
        }
        set
        {
            this.ProductInformationField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
    public IcixUpdate.VendorInformationType VendorInformation
    {
        get
        {
            return this.VendorInformationField;
        }
        set
        {
            this.VendorInformationField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
    public IcixUpdate.ClaimInformationType ClaimInformation
    {
        get
        {
            return this.ClaimInformationField;
        }
        set
        {
            this.ClaimInformationField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
    public IcixUpdate.GFSSType GFSS
    {
        get
        {
            return this.GFSSField;
        }
        set
        {
            this.GFSSField = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IcixUpdate.IncidentReportDetailsType", Namespace="")]
    public partial class IncidentReportDetailsType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SubjectField;
        
        private string CategoryField;
        
        private string AssignedToField;
        
        private string DateCompletedField;
        
        private string RootCauseIDField;
        
        private string VendorActionRequiredField;
        
        private string QuiverIDField;
        
        private string StatusField;
        
        private string CommentsToVendorField;
        
        private string ClassificationField;
        
        private string RegionField;
        
        private string StoreField;
        
        private string IncidentDateField;
        
        private string SubmittedToICIXDateField;
        
        private string ComplaintTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string AssignedTo
        {
            get
            {
                return this.AssignedToField;
            }
            set
            {
                this.AssignedToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string DateCompleted
        {
            get
            {
                return this.DateCompletedField;
            }
            set
            {
                this.DateCompletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string RootCauseID
        {
            get
            {
                return this.RootCauseIDField;
            }
            set
            {
                this.RootCauseIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string VendorActionRequired
        {
            get
            {
                return this.VendorActionRequiredField;
            }
            set
            {
                this.VendorActionRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string QuiverID
        {
            get
            {
                return this.QuiverIDField;
            }
            set
            {
                this.QuiverIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=8)]
        public string CommentsToVendor
        {
            get
            {
                return this.CommentsToVendorField;
            }
            set
            {
                this.CommentsToVendorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=9)]
        public string Classification
        {
            get
            {
                return this.ClassificationField;
            }
            set
            {
                this.ClassificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=10)]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=11)]
        public string Store
        {
            get
            {
                return this.StoreField;
            }
            set
            {
                this.StoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=12)]
        public string IncidentDate
        {
            get
            {
                return this.IncidentDateField;
            }
            set
            {
                this.IncidentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=13)]
        public string SubmittedToICIXDate
        {
            get
            {
                return this.SubmittedToICIXDateField;
            }
            set
            {
                this.SubmittedToICIXDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=14)]
        public string ComplaintType
        {
            get
            {
                return this.ComplaintTypeField;
            }
            set
            {
                this.ComplaintTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IcixUpdate.ProductInformationType", Namespace="")]
    public partial class ProductInformationType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UPCField;
        
        private string ProductNameField;
        
        private string BrandField;
        
        private string LotCodeField;
        
        private string SellByDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UPC
        {
            get
            {
                return this.UPCField;
            }
            set
            {
                this.UPCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string Brand
        {
            get
            {
                return this.BrandField;
            }
            set
            {
                this.BrandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string LotCode
        {
            get
            {
                return this.LotCodeField;
            }
            set
            {
                this.LotCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string SellByDate
        {
            get
            {
                return this.SellByDateField;
            }
            set
            {
                this.SellByDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IcixUpdate.VendorInformationType", Namespace="")]
    public partial class VendorInformationType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string VendorField;
        
        private IcixUpdate.VendorInformationType.FacilityIDsType FacilityIDsField;
        
        private string DistributorField;
        
        private string MemberNameField;
        
        private string RQAContactField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Vendor
        {
            get
            {
                return this.VendorField;
            }
            set
            {
                this.VendorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public IcixUpdate.VendorInformationType.FacilityIDsType FacilityIDs
        {
            get
            {
                return this.FacilityIDsField;
            }
            set
            {
                this.FacilityIDsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string Distributor
        {
            get
            {
                return this.DistributorField;
            }
            set
            {
                this.DistributorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string MemberName
        {
            get
            {
                return this.MemberNameField;
            }
            set
            {
                this.MemberNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string RQAContact
        {
            get
            {
                return this.RQAContactField;
            }
            set
            {
                this.RQAContactField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="IcixUpdate.VendorInformationType.FacilityIDsType", Namespace="", ItemName="FacilityID")]
        public class FacilityIDsType : System.Collections.Generic.List<string>
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IcixUpdate.ClaimInformationType", Namespace="")]
    public partial class ClaimInformationType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IsClaimField;
        
        private string ClaimTypeField;
        
        private string RiskFacsIDField;
        
        private string CustomerCommentsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string IsClaim
        {
            get
            {
                return this.IsClaimField;
            }
            set
            {
                this.IsClaimField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string ClaimType
        {
            get
            {
                return this.ClaimTypeField;
            }
            set
            {
                this.ClaimTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Risk-FacsID", IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string RiskFacsID
        {
            get
            {
                return this.RiskFacsIDField;
            }
            set
            {
                this.RiskFacsIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string CustomerComments
        {
            get
            {
                return this.CustomerCommentsField;
            }
            set
            {
                this.CustomerCommentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IcixUpdate.GFSSType", Namespace="")]
    public partial class GFSSType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RiskLevelField;
        
        private string CommentsField;
        
        private string SampleRecievedField;
        
        private string PhotoRecievedField;
        
        private string DatePhotoRecievedField;
        
        private string WFMRecipientField;
        
        private IcixUpdate.GFSSType.SupportingDocumentsType SupportingDocumentsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string RiskLevel
        {
            get
            {
                return this.RiskLevelField;
            }
            set
            {
                this.RiskLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string SampleRecieved
        {
            get
            {
                return this.SampleRecievedField;
            }
            set
            {
                this.SampleRecievedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string PhotoRecieved
        {
            get
            {
                return this.PhotoRecievedField;
            }
            set
            {
                this.PhotoRecievedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string DatePhotoRecieved
        {
            get
            {
                return this.DatePhotoRecievedField;
            }
            set
            {
                this.DatePhotoRecievedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string WFMRecipient
        {
            get
            {
                return this.WFMRecipientField;
            }
            set
            {
                this.WFMRecipientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public IcixUpdate.GFSSType.SupportingDocumentsType SupportingDocuments
        {
            get
            {
                return this.SupportingDocumentsField;
            }
            set
            {
                this.SupportingDocumentsField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="IcixUpdate.GFSSType.SupportingDocumentsType", Namespace="", ItemName="SupportingDocument")]
        public class SupportingDocumentsType : System.Collections.Generic.List<object>
        {
        }
    }
}
