CREATE TABLE [dbo].[LinkGroup]
(
	[LinkGroupId] INT NOT NULL IDENTITY PRIMARY KEY, 
    [GroupName] NVARCHAR(100) NOT NULL, 
    [GroupDescription] NVARCHAR(500) NOT NULL,
    [InsertDateUtc] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[LastUpdatedDateUtc] DATETIME2 NULL 
)