CREATE LOGIN [TibcoDataReader] 
WITH PASSWORD=N'TibcoDataReader', 
DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], 
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN [TibcoDataWriter] 
WITH PASSWORD=N'TibcoDataWriter', 
DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], 
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
