//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irma.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemOrigin
    {
        public int Origin_ID { get; set; }
        public string Origin_Name { get; set; }
        public Nullable<int> User_ID { get; set; }
    }
}
