CREATE TABLE gpm.price(
    price_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    gpm_id uuid,
    region character varying(2) COLLATE pg_catalog."default" NOT NULL,
    scan_code character varying(13) COLLATE pg_catalog."default" NOT NULL,
    item_id integer NOT NULL,
    business_unit_id integer NOT NULL,
    start_date timestamp(0) without time zone NOT NULL,
    end_date timestamp(0) without time zone,
    price numeric(9,2) NOT NULL,
    percent_off numeric(5,2),
    price_type character varying(3) COLLATE pg_catalog."default" NOT NULL,
    price_type_attribute character varying(10) COLLATE pg_catalog."default" NOT NULL,
    sellable_uom character varying(3) COLLATE pg_catalog."default" NOT NULL,
    currency_code character varying(3) COLLATE pg_catalog."default",
    multiple smallint NOT NULL,
    tag_expiration_date timestamp(0) without time zone,
    insert_date_utc timestamp(6) without time zone NOT NULL,
    modified_date_utc timestamp(6) without time zone
);