CREATE TYPE [dbo].[IconItemNutriFactsType] AS TABLE(
	[Plu] [varchar](50) NULL,
	[RecipeName] [nvarchar](100) NULL,
	[Allergens] [nvarchar](510) NULL,
	[Ingredients] [nvarchar](4000) NULL,
	[ServingsPerPortion] [float] NULL,
	[ServingSizeDesc] [nvarchar](50) NULL,
	[ServingPerContainer] [nvarchar](50) NULL,
	[HshRating] [int] NULL,
	[ServingUnits] [tinyint] NULL,
	[SizeWeight] [int] NULL,
	[Calories] [int] NULL,
	[CaloriesFat] [int] NULL,
	[CaloriesSaturatedFat] [int] NULL,
	[TotalFatWeight] [decimal](10, 1) NULL,
	[TotalFatPercentage] [smallint] NULL,
	[SaturatedFatWeight] [decimal](10, 1) NULL,
	[SaturatedFatPercent] [smallint] NULL,
	[PolyunsaturatedFat] [decimal](10, 1) NULL,
	[MonounsaturatedFat] [decimal](10, 1) NULL,
	[CholesterolWeight] [decimal](10, 1) NULL,
	[CholesterolPercent] [smallint] NULL,
	[SodiumWeight] [decimal](10, 1) NULL,
	[SodiumPercent] [smallint] NULL,
	[PotassiumWeight] [decimal](10, 1) NULL,
	[PotassiumPercent] [smallint] NULL,
	[TotalCarbohydrateWeight] [decimal](10, 1) NULL,
	[TotalCarbohydratePercent] [smallint] NULL,
	[DietaryFiberWeight] [decimal](10, 1) NULL,
	[DietaryFiberPercent] [smallint] NULL,
	[SolubleFiber] [decimal](10, 1) NULL,
	[InsolubleFiber] [decimal](10, 1) NULL,
	[Sugar] [decimal](10, 1) NULL,
	[SugarAlcohol] [decimal](10, 1) NULL,
	[OtherCarbohydrates] [decimal](10, 1) NULL,
	[ProteinWeight] [decimal](10, 1) NULL,
	[ProteinPercent] [smallint] NULL,
	[VitaminA] [smallint] NULL,
	[Betacarotene] [smallint] NULL,
	[VitaminC] [smallint] NULL,
	[Calcium] [smallint] NULL,
	[Iron] [smallint] NULL,
	[VitaminD] [smallint] NULL,
	[VitaminE] [smallint] NULL,
	[Thiamin] [smallint] NULL,
	[Riboflavin] [smallint] NULL,
	[Niacin] [smallint] NULL,
	[VitaminB6] [smallint] NULL,
	[Folate] [smallint] NULL,
	[VitaminB12] [smallint] NULL,
	[Biotin] [smallint] NULL,
	[PantothenicAcid] [smallint] NULL,
	[Phosphorous] [smallint] NULL,
	[Iodine] [smallint] NULL,
	[Magnesium] [smallint] NULL,
	[Zinc] [smallint] NULL,
	[Copper] [smallint] NULL,
	[Transfat] [decimal](10, 1) NULL,
	[CaloriesFromTransfat] [int] NULL,
	[Om6Fatty] [decimal](10, 1) NULL,
	[Om3Fatty] [decimal](10, 1) NULL,
	[Starch] [decimal](10, 1) NULL,
	[Chloride] [smallint] NULL,
	[Chromium] [smallint] NULL,
	[VitaminK] [smallint] NULL,
	[Manganese] [smallint] NULL,
	[Molybdenum] [smallint] NULL,
	[Selenium] [smallint] NULL,
	[TransfatWeight] [decimal](10, 1) NULL
)
GO