CREATE TABLE [dbo].[REGION] (
    [ID]          INT          IDENTITY (1, 1) NOT NULL,
    [REGION_ABBR] VARCHAR (5)  NOT NULL,
    [REGION_NAME] VARCHAR (50) NOT NULL,
    [IS_VISIBLE]  VARCHAR (10) NOT NULL,
    CONSTRAINT [PK_REGION] PRIMARY KEY CLUSTERED ([ID] ASC)
);

