CREATE SCHEMA [amz]
	AUTHORIZATION [dbo];
GO

GRANT INSERT ON SCHEMA :: amz TO [IRSUser];
GO
GRANT SELECT ON SCHEMA :: amz TO [IRSUser];
GO

GRANT INSERT ON SCHEMA :: amz TO [IRMAClientRole];
GO
GRANT SELECT ON SCHEMA :: amz TO [IRMAClientRole];
GO

GRANT SELECT ON SCHEMA :: amz TO [IRMAReports];
GO