//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushController.Controller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PushController.Controller.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Error: Unhandled Exception in ESB Module.
        /// </summary>
        internal static string EsbUnhandledExceptionEmailSubject {
            get {
                return ResourceManager.GetString("EsbUnhandledExceptionEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred in the ESB processing module (controller {0})..
        /// </summary>
        internal static string EsbUnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("EsbUnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following items have a sale start date that occurs after the sale end date and cannot be transmitted to R10:.
        /// </summary>
        internal static string InvalidSaleDatesEmailMessage {
            get {
                return ResourceManager.GetString("InvalidSaleDatesEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Error - Incorrect Sale Start and End Dates.
        /// </summary>
        internal static string InvalidSaleDatesEmailSubject {
            get {
                return ResourceManager.GetString("InvalidSaleDatesEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRMAPush entities could not be created for the following items:.
        /// </summary>
        internal static string IrmaPushEntityBuildFailureEmailMessage {
            get {
                return ResourceManager.GetString("IrmaPushEntityBuildFailureEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Error: Failed to Build IRMAPush Entities.
        /// </summary>
        internal static string IrmaPushEntityBuildFailureEmailSubject {
            get {
                return ResourceManager.GetString("IrmaPushEntityBuildFailureEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following IconPosPushPublish records could not be saved to Icon:.
        /// </summary>
        internal static string IrmaPushEntitySaveFailureEmailMessage {
            get {
                return ResourceManager.GetString("IrmaPushEntitySaveFailureEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Error: Failed to Save IRMAPush Entities.
        /// </summary>
        internal static string IrmaPushEntitySaveFailureEmailSubject {
            get {
                return ResourceManager.GetString("IrmaPushEntitySaveFailureEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The POS Push Controller encountered an error while staging IRMAPush entities.  Falling back to row-by-row processing for the current batch..
        /// </summary>
        internal static string IrmaPushEntitySaveFallbackEmailMessage {
            get {
                return ResourceManager.GetString("IrmaPushEntitySaveFallbackEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Warning: Falling Back to Row-By-Row Processing.
        /// </summary>
        internal static string IrmaPushEntitySaveFallbackEmailSubject {
            get {
                return ResourceManager.GetString("IrmaPushEntitySaveFallbackEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemLink updates could not be created for the following items:.
        /// </summary>
        internal static string ItemLinkEntityBuildFailureEmailMessage {
            get {
                return ResourceManager.GetString("ItemLinkEntityBuildFailureEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Error: Failed to Build ItemLink Entities.
        /// </summary>
        internal static string ItemLinkEntityBuildFailureEmailSubject {
            get {
                return ResourceManager.GetString("ItemLinkEntityBuildFailureEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following ItemLink entities could not be saved to the database:.
        /// </summary>
        internal static string ItemLinkEntitySaveFailureEmailMessage {
            get {
                return ResourceManager.GetString("ItemLinkEntitySaveFailureEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Error: Failed to Save ItemLink Entities.
        /// </summary>
        internal static string ItemLinkEntitySaveFailureEmailSubject {
            get {
                return ResourceManager.GetString("ItemLinkEntitySaveFailureEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The POS Push Controller encountered an error during bulk ItemLink entity processing.  Falling back to row-by-row processing for the current batch..
        /// </summary>
        internal static string ItemLinkEntitySaveFallbackEmailMessage {
            get {
                return ResourceManager.GetString("ItemLinkEntitySaveFallbackEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Warning: Falling Back to Row-By-Row Processing.
        /// </summary>
        internal static string ItemLinkEntitySaveFallbackEmailSubject {
            get {
                return ResourceManager.GetString("ItemLinkEntitySaveFallbackEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemLocale messages could not be created for the following items:.
        /// </summary>
        internal static string ItemLocaleMessageBuildFailureEmailMessage {
            get {
                return ResourceManager.GetString("ItemLocaleMessageBuildFailureEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Error: Failed to Build ItemLocale Messages.
        /// </summary>
        internal static string ItemLocaleMessageBuildFailureEmailSubject {
            get {
                return ResourceManager.GetString("ItemLocaleMessageBuildFailureEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following ItemLocale messages could not be saved to the database:.
        /// </summary>
        internal static string ItemLocaleMessageSaveFailureEmailMessage {
            get {
                return ResourceManager.GetString("ItemLocaleMessageSaveFailureEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Error: Failed to Save ItemLocale Messages.
        /// </summary>
        internal static string ItemLocaleMessageSaveFailureEmailSubject {
            get {
                return ResourceManager.GetString("ItemLocaleMessageSaveFailureEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The POS Push Controller encountered an error during bulk ItemLocale message processing.  Falling back to row-by-row processing for the current batch..
        /// </summary>
        internal static string ItemLocaleMessageSaveFallbackEmailMessage {
            get {
                return ResourceManager.GetString("ItemLocaleMessageSaveFallbackEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Warning: Falling Back to Row-By-Row Processing.
        /// </summary>
        internal static string ItemLocaleMessageSaveFallbackEmailSubject {
            get {
                return ResourceManager.GetString("ItemLocaleMessageSaveFallbackEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemPrice updates could not be created for the following items:.
        /// </summary>
        internal static string ItemPriceEntityBuildFailureEmailMessage {
            get {
                return ResourceManager.GetString("ItemPriceEntityBuildFailureEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Error: Failed to Build ItemPrice Entities.
        /// </summary>
        internal static string ItemPriceEntityBuildFailureEmailSubject {
            get {
                return ResourceManager.GetString("ItemPriceEntityBuildFailureEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following ItemPrice entities could not be saved to the database:.
        /// </summary>
        internal static string ItemPriceEntitySaveFailureEmailMessage {
            get {
                return ResourceManager.GetString("ItemPriceEntitySaveFailureEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Error: Failed to Save ItemPrice Entities.
        /// </summary>
        internal static string ItemPriceEntitySaveFailureEmailSubject {
            get {
                return ResourceManager.GetString("ItemPriceEntitySaveFailureEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The POS Push Controller encountered an error during bulk ItemPrice entity processing.  Falling back to row-by-row processing for the current batch..
        /// </summary>
        internal static string ItemPriceEntitySaveFallbackEmailMessage {
            get {
                return ResourceManager.GetString("ItemPriceEntitySaveFallbackEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Warning: Falling Back to Row-By-Row Processing.
        /// </summary>
        internal static string ItemPriceEntitySaveFallbackEmailSubject {
            get {
                return ResourceManager.GetString("ItemPriceEntitySaveFallbackEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item scubscription could not be marked as deleted for the following items:.
        /// </summary>
        internal static string ItemSubscriptionDeleteFailureEmailMessage {
            get {
                return ResourceManager.GetString("ItemSubscriptionDeleteFailureEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The POS Push Controller encountered an error during Item subscription delete processing.  Falling back to row-by-row processing for the current batch..
        /// </summary>
        internal static string ItemSubscriptionDeleteFallbackEmailSubject {
            get {
                return ResourceManager.GetString("ItemSubscriptionDeleteFallbackEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price messages could not be created for the following items:.
        /// </summary>
        internal static string PriceMessageBuildFailureEmailMessage {
            get {
                return ResourceManager.GetString("PriceMessageBuildFailureEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Error: Failed to Build Price Messages.
        /// </summary>
        internal static string PriceMessageBuildFailureEmailSubject {
            get {
                return ResourceManager.GetString("PriceMessageBuildFailureEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following Price messages could not be saved to the database:.
        /// </summary>
        internal static string PriceMessageSaveFailureEmailMessage {
            get {
                return ResourceManager.GetString("PriceMessageSaveFailureEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Error: Failed to Save Price Messages.
        /// </summary>
        internal static string PriceMessageSaveFailureEmailSubject {
            get {
                return ResourceManager.GetString("PriceMessageSaveFailureEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The POS Push Controller encountered an error during bulk Price message processing.  Falling back to row-by-row processing for the current batch..
        /// </summary>
        internal static string PriceMessageSaveFallbackEmailMessage {
            get {
                return ResourceManager.GetString("PriceMessageSaveFallbackEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Warning: Falling Back to Row-By-Row Processing.
        /// </summary>
        internal static string PriceMessageSaveFallbackEmailSubject {
            get {
                return ResourceManager.GetString("PriceMessageSaveFallbackEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Error: Unhandled Exception in IRMAPush Staging Module.
        /// </summary>
        internal static string StagingUnhandledExceptionEmailSubject {
            get {
                return ResourceManager.GetString("StagingUnhandledExceptionEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - An unhandled exception occurred in the IRMAPush staging processing module (controller {1})..
        /// </summary>
        internal static string StagingUnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("StagingUnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Push Controller Error: Unhandled Exception in UDM Module.
        /// </summary>
        internal static string UdmUnhandledExceptionEmailSubject {
            get {
                return ResourceManager.GetString("UdmUnhandledExceptionEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred in the UDM processing module (controller {0})..
        /// </summary>
        internal static string UdmUnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("UdmUnhandledExceptionMessage", resourceCulture);
            }
        }
    }
}
