'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''AdminSettingsInterface class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class AdminSettingsInterface

    '''<summary>
    '''dsAdminSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAdminSettings As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''dsAdminSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAdminSetting As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''pnlAdminSettingList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdminSettingList As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvAdminSettingsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAdminSettingsList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnAddAdminSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddAdminSetting As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlAdminSettingDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdminSettingDetails As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dvAdminSettingDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvAdminSettingDetail As Global.System.Web.UI.WebControls.DetailsView
End Class
