//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attribute()
        {
            this.AttributeCharacterSets = new HashSet<AttributeCharacterSet>();
            this.PickListDatas = new HashSet<PickListData>();
        }
    
        public int AttributeId { get; set; }
        public string DisplayName { get; set; }
        public string AttributeName { get; set; }
        public Nullable<int> AttributeGroupId { get; set; }
        public Nullable<bool> HasUniqueValues { get; set; }
        public string Description { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<bool> RequiredForPublishing { get; set; }
        public string SpecialCharactersAllowed { get; set; }
        public string TraitCode { get; set; }
        public Nullable<int> DataTypeId { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> InitialValue { get; set; }
        public Nullable<int> IncrementBy { get; set; }
        public Nullable<int> InitialMax { get; set; }
        public string DisplayType { get; set; }
        public Nullable<int> MaxLengthAllowed { get; set; }
        public string NumberValidationRule { get; set; }
        public bool PickList { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeCharacterSet> AttributeCharacterSets { get; set; }
        public virtual AttributeGroup AttributeGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickListData> PickListDatas { get; set; }
    }
}
