'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class CompetitorStore
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CompetitorStore", GetType(CompetitorStore).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt; All &gt;.
        '''</summary>
        Friend Shared ReadOnly Property AllItems() As String
            Get
                Return ResourceManager.GetString("AllItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to One or more of the rows you have selected cannot be re-matched..
        '''</summary>
        Friend Shared ReadOnly Property CannotRematchItem() As String
            Get
                Return ResourceManager.GetString("CannotRematchItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Competitor Price Search.
        '''</summary>
        Friend Shared ReadOnly Property CompetitorPriceSearch() As String
            Get
                Return ResourceManager.GetString("CompetitorPriceSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm Quit.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmQuitTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmQuitTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Row {0}: .
        '''</summary>
        Friend Shared ReadOnly Property ExcelErrorRowIndex() As String
            Get
                Return ResourceManager.GetString("ExcelErrorRowIndex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are {0} competitor prices that already exist. Do you want to overwrite them?.
        '''</summary>
        Friend Shared ReadOnly Property ExistingCompetitorPrices() As String
            Get
                Return ResourceManager.GetString("ExistingCompetitorPrices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pricing info exists.
        '''</summary>
        Friend Shared ReadOnly Property ExistingCompetitorPricesTitle() As String
            Get
                Return ResourceManager.GetString("ExistingCompetitorPricesTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Not Found.
        '''</summary>
        Friend Shared ReadOnly Property FileNotFound() As String
            Get
                Return ResourceManager.GetString("FileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fiscal week range cannot end before it starts.
        '''</summary>
        Friend Shared ReadOnly Property FiscalWeekRange() As String
            Get
                Return ResourceManager.GetString("FiscalWeekRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fiscal Week Range.
        '''</summary>
        Friend Shared ReadOnly Property FiscalWeekRangeTitle() As String
            Get
                Return ResourceManager.GetString("FiscalWeekRangeTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please fix errors before continuing; they are highlighted in yellow..
        '''</summary>
        Friend Shared ReadOnly Property FixErrors() As String
            Get
                Return ResourceManager.GetString("FixErrors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Validation.
        '''</summary>
        Friend Shared ReadOnly Property FixErrorsTitle() As String
            Get
                Return ResourceManager.GetString("FixErrorsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to quit Competitor Store Import?.
        '''</summary>
        Friend Shared ReadOnly Property ImportConfirmQuit() As String
            Get
                Return ResourceManager.GetString("ImportConfirmQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Validation failed: {0}.
        '''</summary>
        Friend Shared ReadOnly Property ImportErrorGeneric() As String
            Get
                Return ResourceManager.GetString("ImportErrorGeneric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reached limit of {0} errors..
        '''</summary>
        Friend Shared ReadOnly Property ImportErrorLimit() As String
            Get
                Return ResourceManager.GetString("ImportErrorLimit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Validation failed: Data is missing or columns are malformatted..
        '''</summary>
        Friend Shared ReadOnly Property ImportErrorMessage() As String
            Get
                Return ResourceManager.GetString("ImportErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please fix the following issues.
        '''</summary>
        Friend Shared ReadOnly Property ImportErrorTitle() As String
            Get
                Return ResourceManager.GetString("ImportErrorTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import failed..
        '''</summary>
        Friend Shared ReadOnly Property ImportFailed() As String
            Get
                Return ResourceManager.GetString("ImportFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Malformatted value for column {0}.
        '''</summary>
        Friend Shared ReadOnly Property ImportMalformattedValue() As String
            Get
                Return ResourceManager.GetString("ImportMalformattedValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Matching.
        '''</summary>
        Friend Shared ReadOnly Property ImportMatching() As String
            Get
                Return ResourceManager.GetString("ImportMatching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing or malformatted value for column {0}.
        '''</summary>
        Friend Shared ReadOnly Property ImportMissingOrMalformattedValue() As String
            Get
                Return ResourceManager.GetString("ImportMissingOrMalformattedValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing value for column {0}.
        '''</summary>
        Friend Shared ReadOnly Property ImportMissingValue() As String
            Get
                Return ResourceManager.GetString("ImportMissingValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import successful!.
        '''</summary>
        Friend Shared ReadOnly Property ImportSuccessful() As String
            Get
                Return ResourceManager.GetString("ImportSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uploading Data....
        '''</summary>
        Friend Shared ReadOnly Property ImportUploadingData() As String
            Get
                Return ResourceManager.GetString("ImportUploadingData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Validating.
        '''</summary>
        Friend Shared ReadOnly Property ImportValidating() As String
            Get
                Return ResourceManager.GetString("ImportValidating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPC: {0} - {1}.
        '''</summary>
        Friend Shared ReadOnly Property ItemDescription() As String
            Get
                Return ResourceManager.GetString("ItemDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item must be matched.
        '''</summary>
        Friend Shared ReadOnly Property MatchItem() As String
            Get
                Return ResourceManager.GetString("MatchItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt; None &gt;.
        '''</summary>
        Friend Shared ReadOnly Property NoItems() As String
            Get
                Return ResourceManager.GetString("NoItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No prices found..
        '''</summary>
        Friend Shared ReadOnly Property NoPricesFound() As String
            Get
                Return ResourceManager.GetString("NoPricesFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No worksheets found to import..
        '''</summary>
        Friend Shared ReadOnly Property NoWorksheetFound() As String
            Get
                Return ResourceManager.GetString("NoWorksheetFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select a single store to change priority.
        '''</summary>
        Friend Shared ReadOnly Property PriorityChangeSingleStore() As String
            Get
                Return ResourceManager.GetString("PriorityChangeSingleStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Competitor is required.
        '''</summary>
        Friend Shared ReadOnly Property RequireCompetitor() As String
            Get
                Return ResourceManager.GetString("RequireCompetitor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Competitor Location is required.
        '''</summary>
        Friend Shared ReadOnly Property RequireCompetitorLocation() As String
            Get
                Return ResourceManager.GetString("RequireCompetitorLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Competitor Store is required.
        '''</summary>
        Friend Shared ReadOnly Property RequireCompetitorStore() As String
            Get
                Return ResourceManager.GetString("RequireCompetitorStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fiscal Year is required.
        '''</summary>
        Friend Shared ReadOnly Property RequireFiscalYear() As String
            Get
                Return ResourceManager.GetString("RequireFiscalYear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price is required.
        '''</summary>
        Friend Shared ReadOnly Property RequirePrice() As String
            Get
                Return ResourceManager.GetString("RequirePrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price multiple is required.
        '''</summary>
        Friend Shared ReadOnly Property RequirePriceMultiple() As String
            Get
                Return ResourceManager.GetString("RequirePriceMultiple", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Size is required.
        '''</summary>
        Friend Shared ReadOnly Property RequireSize() As String
            Get
                Return ResourceManager.GetString("RequireSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select a competitor store to continue..
        '''</summary>
        Friend Shared ReadOnly Property SelectCompetitorStore() As String
            Get
                Return ResourceManager.GetString("SelectCompetitorStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a competitor store.
        '''</summary>
        Friend Shared ReadOnly Property SelectCompetitorStoreTitle() As String
            Get
                Return ResourceManager.GetString("SelectCompetitorStoreTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select an item to continue..
        '''</summary>
        Friend Shared ReadOnly Property SelectItem() As String
            Get
                Return ResourceManager.GetString("SelectItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select an Item.
        '''</summary>
        Friend Shared ReadOnly Property SelectItemTitle() As String
            Get
                Return ResourceManager.GetString("SelectItemTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select One Store.
        '''</summary>
        Friend Shared ReadOnly Property SelectOneStore() As String
            Get
                Return ResourceManager.GetString("SelectOneStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select one or more rows..
        '''</summary>
        Friend Shared ReadOnly Property SelectRows() As String
            Get
                Return ResourceManager.GetString("SelectRows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Rows.
        '''</summary>
        Friend Shared ReadOnly Property SelectRowsTitle() As String
            Get
                Return ResourceManager.GetString("SelectRowsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select a store..
        '''</summary>
        Friend Shared ReadOnly Property SelectStore() As String
            Get
                Return ResourceManager.GetString("SelectStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a Store.
        '''</summary>
        Friend Shared ReadOnly Property SelectStoreTitle() As String
            Get
                Return ResourceManager.GetString("SelectStoreTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to open workbook..
        '''</summary>
        Friend Shared ReadOnly Property UnableToOpenWorkbook() As String
            Get
                Return ResourceManager.GetString("UnableToOpenWorkbook", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unavailable Rows.
        '''</summary>
        Friend Shared ReadOnly Property UnavailableRows() As String
            Get
                Return ResourceManager.GetString("UnavailableRows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have unsaved changes. Do you want to discard them and exit?.
        '''</summary>
        Friend Shared ReadOnly Property UnsavedChangesBeforeExit() As String
            Get
                Return ResourceManager.GetString("UnsavedChangesBeforeExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like to save your changes before continuing? No will discard them and Cancel will leave the changes and stop the search..
        '''</summary>
        Friend Shared ReadOnly Property UnsavedChangesBeforeSearch() As String
            Get
                Return ResourceManager.GetString("UnsavedChangesBeforeSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unsaved Changes.
        '''</summary>
        Friend Shared ReadOnly Property UnsavedChangesTitle() As String
            Get
                Return ResourceManager.GetString("UnsavedChangesTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upload failed..
        '''</summary>
        Friend Shared ReadOnly Property UploadFailed() As String
            Get
                Return ResourceManager.GetString("UploadFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prices.
        '''</summary>
        Friend Shared ReadOnly Property UploadProgressItemName() As String
            Get
                Return ResourceManager.GetString("UploadProgressItemName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please wait....
        '''</summary>
        Friend Shared ReadOnly Property UploadProgressMessage() As String
            Get
                Return ResourceManager.GetString("UploadProgressMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uploading competitor data.
        '''</summary>
        Friend Shared ReadOnly Property UploadProgressTitle() As String
            Get
                Return ResourceManager.GetString("UploadProgressTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upload Complete.{0}Upload duration: {1:0.00} seconds{0}Matching duration: {2:0.00}.
        '''</summary>
        Friend Shared ReadOnly Property UploadStatistics() As String
            Get
                Return ResourceManager.GetString("UploadStatistics", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
