'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ItemBulkLoad
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ItemBulkLoad", GetType(ItemBulkLoad).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply Date cannot be in the past.
        '''</summary>
        Friend Shared ReadOnly Property ApplyDateNotPast() As String
            Get
                Return ResourceManager.GetString("ApplyDateNotPast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End Date for competitive priced batches must be within 60 days of the Check Date for any of the items in the batch..
        '''</summary>
        Friend Shared ReadOnly Property CompetitiveBatchDateTooFar() As String
            Get
                Return ResourceManager.GetString("CompetitiveBatchDateTooFar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Competitive priced batches must consist of all items which have been imported via the competitive module..
        '''</summary>
        Friend Shared ReadOnly Property CompetitiveBatchMissingItems() As String
            Get
                Return ResourceManager.GetString("CompetitiveBatchMissingItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please correct in your spreadsheet and re-import..
        '''</summary>
        Friend Shared ReadOnly Property Correct_Spreadsheet() As String
            Get
                Return ResourceManager.GetString("Correct_Spreadsheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have some items that have not been uploaded.  Do you want to cancel upload?.
        '''</summary>
        Friend Shared ReadOnly Property DataChanged_WarningMessage() As String
            Get
                Return ResourceManager.GetString("DataChanged_WarningMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discontinued.
        '''</summary>
        Friend Shared ReadOnly Property Discontinued_Column() As String
            Get
                Return ResourceManager.GetString("Discontinued_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Employee Discountable.
        '''</summary>
        Friend Shared ReadOnly Property Discountable_Column() As String
            Get
                Return ResourceManager.GetString("Discountable_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upload experienced fatal errors - Please contact your administrator..
        '''</summary>
        Friend Shared ReadOnly Property EmailErrorMessage() As String
            Get
                Return ResourceManager.GetString("EmailErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User = {0}{1}Date = {2}{3}This is an automated email generated by WholeFoods.IRMA.ItemMaintenanceBulkLoad version: {4}{5}This email was sent to: {6}.
        '''</summary>
        Friend Shared ReadOnly Property EmailMessage() As String
            Get
                Return ResourceManager.GetString("EmailMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Maintenance Bulk Load Confirmation.
        '''</summary>
        Friend Shared ReadOnly Property EmailSubject() As String
            Get
                Return ResourceManager.GetString("EmailSubject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Food Stamps.
        '''</summary>
        Friend Shared ReadOnly Property FoodStamps_Column() As String
            Get
                Return ResourceManager.GetString("FoodStamps_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Identifier.
        '''</summary>
        Friend Shared ReadOnly Property Identifier_Column() As String
            Get
                Return ResourceManager.GetString("Identifier_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Discontinued Value.  It can be either 0 or 1, or left blank to indicate no changes to current value..
        '''</summary>
        Friend Shared ReadOnly Property Invalid_Discontinued() As String
            Get
                Return ResourceManager.GetString("Invalid_Discontinued", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Employee Discount Value. It can be either 0 or 1, or left blank to indicate no changes to current value..
        '''</summary>
        Friend Shared ReadOnly Property Invalid_EmployeeDiscount() As String
            Get
                Return ResourceManager.GetString("Invalid_EmployeeDiscount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Food Stamp Value for Identifier.  It can be either 0 or 1, or left blank to indicate no changes to current value..
        '''</summary>
        Friend Shared ReadOnly Property Invalid_FoodStamp() As String
            Get
                Return ResourceManager.GetString("Invalid_FoodStamp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid National Class!.
        '''</summary>
        Friend Shared ReadOnly Property Invalid_NationalClass() As String
            Get
                Return ResourceManager.GetString("Invalid_NationalClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Restricted Hours Value.  It can be either 0 or 1, or left blank to indicate no changes to current value..
        '''</summary>
        Friend Shared ReadOnly Property Invalid_RestrictedHrs() As String
            Get
                Return ResourceManager.GetString("Invalid_RestrictedHrs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Tax Class!.
        '''</summary>
        Friend Shared ReadOnly Property Invalid_TaxClass() As String
            Get
                Return ResourceManager.GetString("Invalid_TaxClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description cannot exceed 60 characters!.
        '''</summary>
        Friend Shared ReadOnly Property ItemDesc_MaxLength() As String
            Get
                Return ResourceManager.GetString("ItemDesc_MaxLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property ItemDescription_Column() As String
            Get
                Return ResourceManager.GetString("ItemDescription_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Identifier Valid.
        '''</summary>
        Friend Shared ReadOnly Property ItemIdentifierValid_Column() As String
            Get
                Return ResourceManager.GetString("ItemIdentifierValid_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This item was not uploaded due to errors..
        '''</summary>
        Friend Shared ReadOnly Property ItemNotUploaded() As String
            Get
                Return ResourceManager.GetString("ItemNotUploaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.
        '''</summary>
        Friend Shared ReadOnly Property ItemUpload_Type() As String
            Get
                Return ResourceManager.GetString("ItemUpload_Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ItemUploadDetail_ID.
        '''</summary>
        Friend Shared ReadOnly Property ItemUploadDetailID_Column() As String
            Get
                Return ResourceManager.GetString("ItemUploadDetailID_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to National Class.
        '''</summary>
        Friend Shared ReadOnly Property NationalClass_Column() As String
            Get
                Return ResourceManager.GetString("NationalClass_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to POS Description cannot exceed 26 characters!.
        '''</summary>
        Friend Shared ReadOnly Property POSDesc_MaxLength() As String
            Get
                Return ResourceManager.GetString("POSDesc_MaxLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to POS Description.
        '''</summary>
        Friend Shared ReadOnly Property POSDescription_Column() As String
            Get
                Return ResourceManager.GetString("POSDescription_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An identifier column is required.
        '''</summary>
        Friend Shared ReadOnly Property Required_Identifier() As String
            Get
                Return ResourceManager.GetString("Required_Identifier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restricted Hours.
        '''</summary>
        Friend Shared ReadOnly Property RestrictedHrs_Column() As String
            Get
                Return ResourceManager.GetString("RestrictedHrs_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Maintenance Bulk Load.
        '''</summary>
        Friend Shared ReadOnly Property Screen_Title() As String
            Get
                Return ResourceManager.GetString("Screen_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You do not have access to items in this sub team..
        '''</summary>
        Friend Shared ReadOnly Property SubTeam_NotAllowed() As String
            Get
                Return ResourceManager.GetString("SubTeam_NotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sub Team Allowed.
        '''</summary>
        Friend Shared ReadOnly Property SubTeamAllowed_Column() As String
            Get
                Return ResourceManager.GetString("SubTeamAllowed_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sub Team Name.
        '''</summary>
        Friend Shared ReadOnly Property SubTeamName_Column() As String
            Get
                Return ResourceManager.GetString("SubTeamName_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sub Team No.
        '''</summary>
        Friend Shared ReadOnly Property SubTeamNo_Column() As String
            Get
                Return ResourceManager.GetString("SubTeamNo_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tax Class.
        '''</summary>
        Friend Shared ReadOnly Property TaxClass_Column() As String
            Get
                Return ResourceManager.GetString("TaxClass_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Maintenance Bulk Load Results: {0}Item Upload ID = {1}{2}Items Processed Count = {3}{4}Items Loaded Count = {5}{6}Errors Count = {7}{8}.
        '''</summary>
        Friend Shared ReadOnly Property UploadResults() As String
            Get
                Return ResourceManager.GetString("UploadResults", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
