//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Core.Models.Irma
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreItemVendor
    {
        public int StoreItemVendorID { get; set; }
        public int Store_No { get; set; }
        public int Item_Key { get; set; }
        public int Vendor_ID { get; set; }
        public Nullable<short> AverageDelivery { get; set; }
        public bool PrimaryVendor { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteWorkStation { get; set; }
        public Nullable<System.DateTime> LastCostAddedDate { get; set; }
        public System.DateTime LastCostRefreshedDate { get; set; }
        public bool DiscontinueItem { get; set; }
    }
}
