
-- Change History
-- Date			Initial		TFS		Comments
-- 07/02/2015	DN			16245	Renamed Columns:
--									Size			-> ServingsPerPortion
--									Size Text		-> ServingSizeDesc
--									PerContainer	-> ServingPerContainer

CREATE PROCEDURE dbo.Scale_InsertUpdateNutriFact
	@ID int,
	@Description varchar(50),
	@Scale_LabelFormat_ID int,
	@ServingUnits tinyint,
	@ServingsPerPortion float,
	@SizeWeight int,
	@Calories int,
	@CaloriesFat int,
	@CaloriesSaturatedFat int,
	@ServingPerContainer varchar(10),
	@TotalFatWeight decimal(5,1),
	@TotalFatPercentage smallint,
	@SaturatedFatWeight decimal(5,1),
	@SaturatedFatPercent smallint,
	@PolyunsaturatedFat decimal(10, 1),
	@MonounsaturatedFat decimal(10, 1),
	@CholesterolWeight decimal(5,1),
	@CholesterolPercent smallint,
	@SodiumWeight decimal(5,1),
	@SodiumPercent smallint,
	@PotassiumWeight decimal(5,1),
	@PotassiumPercent smallint,
	@TotalCarbohydrateWeight decimal(5,1),
	@TotalCarbohydratePercent smallint,
	@DietaryFiberWeight decimal(5,1),
	@DietaryFiberPercent smallint,
	@SolubleFiber decimal(5,1),
	@InsolubleFiber decimal(5,1),
	@Sugar decimal(5,1),
	@SugarAlcohol decimal(5,1),
	@OtherCarbohydrates decimal(5,1),
	@ProteinWeight decimal(5,1),
	@ProteinPercent smallint,
	@VitaminA smallint,
	@Betacarotene smallint,
	@VitaminC smallint,
	@Calcium smallint,
	@Iron smallint,
	@VitaminD smallint,
	@VitaminE smallint,
	@Thiamin smallint,
	@Riboflavin smallint,
	@Niacin smallint,
	@VitaminB6 smallint,
	@Folate smallint,
	@VitaminB12 smallint,
	@Biotin smallint,
	@PantothenicAcid smallint,
	@Phosphorous smallint,
	@Iodine smallint,
	@Magnesium smallint,
	@Zinc smallint,
	@Copper smallint,
	@Transfat smallint,
	@TransfatWeight decimal(5,1),
	@CaloriesFromTransFat int,
	@Om6Fatty decimal(5,1),
	@Om3Fatty decimal(5,1),
	@Starch decimal(5,1),
	@Chloride smallint,
	@Chromium smallint,
	@VitaminK smallint,
	@Manganese smallint,
	@Molybdenum smallint,
	@Selenium smallint,
	@ServingSizeDesc varchar(28)


AS 
BEGIN 
	IF @ID > 0 
		BEGIN
			UPDATE 
				NutriFacts
			SET 
				Description = @Description,
				Scale_LabelFormat_ID = @Scale_LabelFormat_ID,
				ServingUnits = @ServingUnits,
				ServingsPerPortion = @ServingsPerPortion,
				SizeWeight = @SizeWeight,
				Calories = @Calories,
				CaloriesFat = @CaloriesFat,
				CaloriesSaturatedFat = @CaloriesSaturatedFat,
				ServingPerContainer = @ServingPerContainer,
				TotalFatWeight = @TotalFatWeight,
				TotalFatPercentage = @TotalFatPercentage,
				SaturatedFatWeight = @SaturatedFatWeight,
				SaturatedFatPercent = @SaturatedFatPercent,
				PolyunsaturatedFat = @PolyunsaturatedFat,
				MonounsaturatedFat = @MonounsaturatedFat,
				CholesterolWeight = @CholesterolWeight,
				CholesterolPercent = @CholesterolPercent,
				SodiumWeight = @SodiumWeight,
				SodiumPercent = @SodiumPercent,
				PotassiumWeight = @PotassiumWeight,
				PotassiumPercent = @PotassiumPercent,
				TotalCarbohydrateWeight = @TotalCarbohydrateWeight,
				TotalCarbohydratePercent = @TotalCarbohydratePercent,
				DietaryFiberWeight = @DietaryFiberWeight,
				DietaryFiberPercent = @DietaryFiberPercent,
				SolubleFiber = @SolubleFiber,
				InsolubleFiber = @InsolubleFiber,
				Sugar = @Sugar,
				SugarAlcohol = @SugarAlcohol,
				OtherCarbohydrates = @OtherCarbohydrates,
				ProteinWeight = @ProteinWeight,
				ProteinPercent = @ProteinPercent,
				VitaminA = @VitaminA,
				Betacarotene = @Betacarotene,
				VitaminC = @VitaminC,
				Calcium = @Calcium,
				Iron = @Iron,
				VitaminD = @VitaminD,
				VitaminE = @VitaminE,
				Thiamin = @Thiamin,
				Riboflavin = @Riboflavin,
				Niacin = @Niacin,
				VitaminB6 = @VitaminB6,
				Folate = @Folate,
				VitaminB12 = @VitaminB12,
				Biotin = @Biotin,
				PantothenicAcid = @PantothenicAcid,
				Phosphorous = @Phosphorous,
				Iodine = @Iodine,
				Magnesium = @Magnesium,
				Zinc = @Zinc,
				Copper = @Copper,
				Transfat = @Transfat,
				TransfatWeight = @TransfatWeight,
				CaloriesFromTransFat = @CaloriesFromTransFat,
				Om6Fatty = @Om6Fatty,
				Om3Fatty = @Om3Fatty,
				Starch = @Starch,
				Chloride = @Chloride,
				Chromium = @Chromium,
				VitaminK = @VitaminK,
				Manganese = @Manganese,
				Molybdenum = @Molybdenum,
				Selenium = @Selenium,
				ServingSizeDesc = @ServingSizeDesc
			WHERE 
				NutriFactsID = @ID
		END
	ELSE
		BEGIN
			INSERT INTO NutriFacts
				(Description, Scale_LabelFormat_ID, ServingUnits, ServingsPerPortion, 
				SizeWeight, Calories, CaloriesFat, CaloriesSaturatedFat, 
				ServingPerContainer, TotalFatWeight, TotalFatPercentage, 
				SaturatedFatWeight, SaturatedFatPercent, PolyunsaturatedFat, 
				MonounsaturatedFat, CholesterolWeight, CholesterolPercent, 
				SodiumWeight, SodiumPercent, PotassiumWeight, PotassiumPercent, 
				TotalCarbohydrateWeight, TotalCarbohydratePercent, DietaryFiberWeight, 
				DietaryFiberPercent, SolubleFiber, InsolubleFiber, Sugar, 
				SugarAlcohol, OtherCarbohydrates, ProteinWeight, ProteinPercent, 
				VitaminA, Betacarotene, VitaminC, Calcium, Iron, VitaminD, VitaminE, 
				Thiamin, Riboflavin, Niacin, VitaminB6, Folate, VitaminB12, Biotin, 
				PantothenicAcid, Phosphorous, Iodine, Magnesium, Zinc, Copper, 
				Transfat, CaloriesFromTransFat, Om6Fatty, Om3Fatty, Starch, Chloride, 
				Chromium, VitaminK, Manganese, Molybdenum, Selenium, ServingSizeDesc, TransfatWeight)
			VALUES 
				(@Description, @Scale_LabelFormat_ID, @ServingUnits, @ServingsPerPortion, 
				@SizeWeight, @Calories, @CaloriesFat, @CaloriesSaturatedFat, 
				@ServingPerContainer, @TotalFatWeight, @TotalFatPercentage, 
				@SaturatedFatWeight, @SaturatedFatPercent, @PolyunsaturatedFat, 
				@MonounsaturatedFat, @CholesterolWeight, @CholesterolPercent, 
				@SodiumWeight, @SodiumPercent, @PotassiumWeight, @PotassiumPercent, 
				@TotalCarbohydrateWeight, @TotalCarbohydratePercent, @DietaryFiberWeight, 
				@DietaryFiberPercent, @SolubleFiber, @InsolubleFiber, @Sugar, 
				@SugarAlcohol, @OtherCarbohydrates, @ProteinWeight, @ProteinPercent, 
				@VitaminA, @Betacarotene, @VitaminC, @Calcium, @Iron, @VitaminD, 
				@VitaminE, @Thiamin, @Riboflavin, @Niacin, @VitaminB6, @Folate, 
				@VitaminB12, @Biotin, @PantothenicAcid, @Phosphorous, @Iodine, 
				@Magnesium, @Zinc, @Copper, @Transfat, @CaloriesFromTransFat, 
				@Om6Fatty, @Om3Fatty, @Starch, @Chloride, @Chromium, @VitaminK, 
				@Manganese, @Molybdenum, @Selenium, @ServingSizeDesc, @TransfatWeight)
		END
END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[Scale_InsertUpdateNutriFact] TO [IRMAClientRole]
    AS [dbo];

