SET IDENTITY_INSERT app.MessageQueueProduct ON

INSERT INTO app.MessageQueueProduct
		([MessageQueueId]
		   ,[MessageTypeId]
           ,[MessageStatusId]
           ,[MessageHistoryId]
           ,[InsertDate]
           ,[ItemId]
           ,[LocaleId]
           ,[ItemTypeCode]
           ,[ItemTypeDesc]
           ,[ScanCodeId]
           ,[ScanCode]
           ,[ScanCodeTypeId]
           ,[ScanCodeTypeDesc]
           ,[ProductDescription]
           ,[PosDescription]
           ,[PackageUnit]
           ,[RetailSize]
           ,[RetailUom]
           ,[FoodStampEligible]
           ,[ProhibitDiscount]
           ,[DepartmentSale]
           ,[BrandId]
           ,[BrandName]
           ,[BrandLevel]
           ,[BrandParentId]
           ,[BrowsingClassId]
           ,[BrowsingClassName]
           ,[BrowsingLevel]
           ,[BrowsingParentId]
           ,[MerchandiseClassId]
           ,[MerchandiseClassName]
           ,[MerchandiseLevel]
           ,[MerchandiseParentId]
           ,[TaxClassId]
           ,[TaxClassName]
           ,[TaxLevel]
           ,[TaxParentId]
           ,[FinancialClassId]
           ,[FinancialClassName]
           ,[FinancialLevel]
           ,[FinancialParentId]
           ,[InProcessBy]
           ,[ProcessedDate]
           ,[AnimalWelfareRating]
           ,[Biodynamic]
           ,[CheeseMilkType]
           ,[CheeseRaw]
           ,[EcoScaleRating]
           ,[GlutenFreeAgency]
           ,[HealthyEatingRating]
           ,[KosherAgency]
           ,[Msc]
           ,[NonGmoAgency]
           ,[OrganicAgency]
           ,[PremiumBodyCare]
           ,[SeafoodFreshOrFrozen]
           ,[SeafoodCatchType]
           ,[VeganAgency]
           ,[Vegetarian]
           ,[WholeTrade]
           ,[GrassFed]
           ,[PastureRaised]
           ,[FreeRange]
           ,[DryAged]
           ,[AirChilled]
           ,[MadeInHouse]
           ,[CustomerFriendlyDescription]
           ,[NutritionRequired]
           ,[GlobalPricingProgram])
SELECT *
FROM ##TempMessageQueueProduct

SET IDENTITY_INSERT app.MessageQueueProduct OFF

SET IDENTITY_INSERT app.MessageQueueNutrition ON

INSERT INTO app.MessageQueueNutrition
           ([MessageQueueNutritionId]
		   ,[MessageQueueId]
           ,[Plu]
           ,[RecipeName]
           ,[Allergens]
           ,[Ingredients]
           ,[ServingsPerPortion]
           ,[ServingSizeDesc]
           ,[ServingPerContainer]
           ,[HshRating]
           ,[ServingUnits]
           ,[SizeWeight]
           ,[Calories]
           ,[CaloriesFat]
           ,[CaloriesSaturatedFat]
           ,[TotalFatWeight]
           ,[TotalFatPercentage]
           ,[SaturatedFatWeight]
           ,[SaturatedFatPercent]
           ,[PolyunsaturatedFat]
           ,[MonounsaturatedFat]
           ,[CholesterolWeight]
           ,[CholesterolPercent]
           ,[SodiumWeight]
           ,[SodiumPercent]
           ,[PotassiumWeight]
           ,[PotassiumPercent]
           ,[TotalCarbohydrateWeight]
           ,[TotalCarbohydratePercent]
           ,[DietaryFiberWeight]
           ,[DietaryFiberPercent]
           ,[SolubleFiber]
           ,[InsolubleFiber]
           ,[Sugar]
           ,[SugarAlcohol]
           ,[OtherCarbohydrates]
           ,[ProteinWeight]
           ,[ProteinPercent]
           ,[VitaminA]
           ,[Betacarotene]
           ,[VitaminC]
           ,[Calcium]
           ,[Iron]
           ,[VitaminD]
           ,[VitaminE]
           ,[Thiamin]
           ,[Riboflavin]
           ,[Niacin]
           ,[VitaminB6]
           ,[Folate]
           ,[VitaminB12]
           ,[Biotin]
           ,[PantothenicAcid]
           ,[Phosphorous]
           ,[Iodine]
           ,[Magnesium]
           ,[Zinc]
           ,[Copper]
           ,[Transfat]
           ,[CaloriesFromTransfat]
           ,[Om6Fatty]
           ,[Om3Fatty]
           ,[Starch]
           ,[Chloride]
           ,[Chromium]
           ,[VitaminK]
           ,[Manganese]
           ,[Molybdenum]
           ,[Selenium]
           ,[TransfatWeight]
           ,[HazardousMaterialFlag]
           ,[HazardousMaterialTypeCode]
           ,[InsertDate])
SELECT *
FROM ##TempMessageQueueNutrition

SET IDENTITY_INSERT app.MessageQueueNutrition OFF

DROP TABLE ##TempMessageQueueProduct
DROP TABLE ##TempMessageQueueNutrition