CREATE TABLE [dbo].[SOURCE] (
    [ID]                 INT           IDENTITY (1, 1) NOT NULL,
    [SOURCE_DESCRIPTION] VARCHAR (100) NULL,
    CONSTRAINT [PK_SOURCE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

