//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace OOSCommon.DataContext
{
    public partial class REPORT_DETAIL_ATTRIBUTE
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int REPORT_DETAIL_ID
        {
            get { return _rEPORT_DETAIL_ID; }
            set
            {
                if (_rEPORT_DETAIL_ID != value)
                {
                    if (REPORT_DETAIL != null && REPORT_DETAIL.ID != value)
                    {
                        REPORT_DETAIL = null;
                    }
                    _rEPORT_DETAIL_ID = value;
                }
            }
        }
        private int _rEPORT_DETAIL_ID;
    
        public virtual int REPORT_DETAIL_ATTRIBUTE_TYPE_ID
        {
            get { return _rEPORT_DETAIL_ATTRIBUTE_TYPE_ID; }
            set
            {
                if (_rEPORT_DETAIL_ATTRIBUTE_TYPE_ID != value)
                {
                    if (REPORT_DETAIL_ATTRIBUTE_TYPE != null && REPORT_DETAIL_ATTRIBUTE_TYPE.ID != value)
                    {
                        REPORT_DETAIL_ATTRIBUTE_TYPE = null;
                    }
                    _rEPORT_DETAIL_ATTRIBUTE_TYPE_ID = value;
                }
            }
        }
        private int _rEPORT_DETAIL_ATTRIBUTE_TYPE_ID;
    
        public virtual string VALUE
        {
            get;
            set;
        }
    
        public virtual string CREATED_BY
        {
            get;
            set;
        }
    
        public virtual System.DateTime CREATED_DATE
        {
            get;
            set;
        }
    
        public virtual string LAST_UPDATED_BY
        {
            get;
            set;
        }
    
        public virtual string LAST_UPDATED_DATE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual REPORT_DETAIL REPORT_DETAIL
        {
            get { return _rEPORT_DETAIL; }
            set
            {
                if (!ReferenceEquals(_rEPORT_DETAIL, value))
                {
                    var previousValue = _rEPORT_DETAIL;
                    _rEPORT_DETAIL = value;
                    FixupREPORT_DETAIL(previousValue);
                }
            }
        }
        private REPORT_DETAIL _rEPORT_DETAIL;
    
        public virtual REPORT_DETAIL_ATTRIBUTE_TYPE REPORT_DETAIL_ATTRIBUTE_TYPE
        {
            get { return _rEPORT_DETAIL_ATTRIBUTE_TYPE; }
            set
            {
                if (!ReferenceEquals(_rEPORT_DETAIL_ATTRIBUTE_TYPE, value))
                {
                    var previousValue = _rEPORT_DETAIL_ATTRIBUTE_TYPE;
                    _rEPORT_DETAIL_ATTRIBUTE_TYPE = value;
                    FixupREPORT_DETAIL_ATTRIBUTE_TYPE(previousValue);
                }
            }
        }
        private REPORT_DETAIL_ATTRIBUTE_TYPE _rEPORT_DETAIL_ATTRIBUTE_TYPE;

        #endregion
        #region Association Fixup
    
        private void FixupREPORT_DETAIL(REPORT_DETAIL previousValue)
        {
            if (previousValue != null && previousValue.REPORT_DETAIL_ATTRIBUTE.Contains(this))
            {
                previousValue.REPORT_DETAIL_ATTRIBUTE.Remove(this);
            }
    
            if (REPORT_DETAIL != null)
            {
                if (!REPORT_DETAIL.REPORT_DETAIL_ATTRIBUTE.Contains(this))
                {
                    REPORT_DETAIL.REPORT_DETAIL_ATTRIBUTE.Add(this);
                }
                if (REPORT_DETAIL_ID != REPORT_DETAIL.ID)
                {
                    REPORT_DETAIL_ID = REPORT_DETAIL.ID;
                }
            }
        }
    
        private void FixupREPORT_DETAIL_ATTRIBUTE_TYPE(REPORT_DETAIL_ATTRIBUTE_TYPE previousValue)
        {
            if (previousValue != null && previousValue.REPORT_DETAIL_ATTRIBUTE.Contains(this))
            {
                previousValue.REPORT_DETAIL_ATTRIBUTE.Remove(this);
            }
    
            if (REPORT_DETAIL_ATTRIBUTE_TYPE != null)
            {
                if (!REPORT_DETAIL_ATTRIBUTE_TYPE.REPORT_DETAIL_ATTRIBUTE.Contains(this))
                {
                    REPORT_DETAIL_ATTRIBUTE_TYPE.REPORT_DETAIL_ATTRIBUTE.Add(this);
                }
                if (REPORT_DETAIL_ATTRIBUTE_TYPE_ID != REPORT_DETAIL_ATTRIBUTE_TYPE.ID)
                {
                    REPORT_DETAIL_ATTRIBUTE_TYPE_ID = REPORT_DETAIL_ATTRIBUTE_TYPE.ID;
                }
            }
        }

        #endregion
    }
}
