//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace OOSCommon.DataContext
{
    public partial class REPORT_DETAIL_ATTRIBUTE_TYPE
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string DESCRIPTION
        {
            get;
            set;
        }
    
        public virtual string QUERY
        {
            get;
            set;
        }
    
        public virtual string CREATED_BY
        {
            get;
            set;
        }
    
        public virtual System.DateTime CREATED_DATE
        {
            get;
            set;
        }
    
        public virtual string LAST_UPDATED_BY
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LAST_UPDATED_DATE
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<REGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP> REGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP
        {
            get
            {
                if (_rEGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP == null)
                {
                    var newCollection = new FixupCollection<REGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP>();
                    newCollection.CollectionChanged += FixupREGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP;
                    _rEGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP = newCollection;
                }
                return _rEGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP;
            }
            set
            {
                if (!ReferenceEquals(_rEGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP, value))
                {
                    var previousValue = _rEGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP as FixupCollection<REGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupREGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP;
                    }
                    _rEGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP = value;
                    var newValue = value as FixupCollection<REGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupREGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP;
                    }
                }
            }
        }
        private ICollection<REGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP> _rEGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP;
    
        public virtual ICollection<REPORT_DETAIL_ATTRIBUTE> REPORT_DETAIL_ATTRIBUTE
        {
            get
            {
                if (_rEPORT_DETAIL_ATTRIBUTE == null)
                {
                    var newCollection = new FixupCollection<REPORT_DETAIL_ATTRIBUTE>();
                    newCollection.CollectionChanged += FixupREPORT_DETAIL_ATTRIBUTE;
                    _rEPORT_DETAIL_ATTRIBUTE = newCollection;
                }
                return _rEPORT_DETAIL_ATTRIBUTE;
            }
            set
            {
                if (!ReferenceEquals(_rEPORT_DETAIL_ATTRIBUTE, value))
                {
                    var previousValue = _rEPORT_DETAIL_ATTRIBUTE as FixupCollection<REPORT_DETAIL_ATTRIBUTE>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupREPORT_DETAIL_ATTRIBUTE;
                    }
                    _rEPORT_DETAIL_ATTRIBUTE = value;
                    var newValue = value as FixupCollection<REPORT_DETAIL_ATTRIBUTE>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupREPORT_DETAIL_ATTRIBUTE;
                    }
                }
            }
        }
        private ICollection<REPORT_DETAIL_ATTRIBUTE> _rEPORT_DETAIL_ATTRIBUTE;

        #endregion
        #region Association Fixup
    
        private void FixupREGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (REGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP item in e.NewItems)
                {
                    item.REPORT_DETAIL_ATTRIBUTE_TYPE = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (REGION_REPORT_DETAIL_ATTRIBUTE_TYPE_MAP item in e.OldItems)
                {
                    if (ReferenceEquals(item.REPORT_DETAIL_ATTRIBUTE_TYPE, this))
                    {
                        item.REPORT_DETAIL_ATTRIBUTE_TYPE = null;
                    }
                }
            }
        }
    
        private void FixupREPORT_DETAIL_ATTRIBUTE(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (REPORT_DETAIL_ATTRIBUTE item in e.NewItems)
                {
                    item.REPORT_DETAIL_ATTRIBUTE_TYPE = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (REPORT_DETAIL_ATTRIBUTE item in e.OldItems)
                {
                    if (ReferenceEquals(item.REPORT_DETAIL_ATTRIBUTE_TYPE, this))
                    {
                        item.REPORT_DETAIL_ATTRIBUTE_TYPE = null;
                    }
                }
            }
        }

        #endregion
    }
}
