CREATE TABLE [app].[IRMAItem](
	[irmaItemID] [int] IDENTITY(1,1) NOT NULL,
	[regioncode] [varchar](2) NOT NULL,
	[identifier] [varchar](13) NOT NULL,
	[defaultIdentifier] [bit] NOT NULL CONSTRAINT [DF_defaultIdentifier]  DEFAULT ((1)),
	[brandName] [varchar](35) NOT NULL,
	[itemDescription] [varchar](60) NOT NULL,
	[posDescription] [varchar](60) NOT NULL,
	[packageUnit] [int] NOT NULL,
	[retailSize] [decimal](9, 4) NULL,
	[retailUom] [varchar](100) NULL,
	[foodStamp] [bit] NOT NULL,
	[posScaleTare] [decimal](18, 0) NOT NULL,
	[departmentSale] [bit] NOT NULL,
	[giftCard] [bit] NULL,
	[taxClassID] [int] NULL,
	[irmaSubTeamName] [varchar](100) NULL,
	[merchandiseClassID] [int] NULL,	
	[nationalClassID] INT NULL,
	[insertDate] [datetime2](7) NOT NULL,
	[AnimalWelfareRating] NVARCHAR(255) NULL,
	[Biodynamic] [bit] NULL,
	[MilkType] NVARCHAR(255) NULL,
	[CheeseRaw] [bit] NULL,
	[EcoScaleRating] NVARCHAR(255) NULL,
	[HealthyEatingRatingId] [int] NULL,
	[Msc] [bit] NULL,
	[PremiumBodyCare] [bit] NULL,
	[FreshOrFrozen] NVARCHAR(255) NULL,
	[SeafoodCatchType] NVARCHAR(255) NULL,
	[Vegetarian] [bit] NULL,
	[WholeTrade] [bit] NULL,
	[GrassFed] [bit] NULL,
	[PastureRaised] [bit] NULL,
	[FreeRange] [bit] NULL,
	[DryAged] [bit] NULL,
	[AirChilled] [bit] NULL,
	[MadeInHouse] [bit] NULL,
	[DeliverySystem] NVARCHAR(255) NULL,
	[AlcoholByVolume] [decimal] (5,2) NULL
 CONSTRAINT [PK_IRMAItem] PRIMARY KEY CLUSTERED 
(
	[irmaItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
