CREATE TABLE app.MessageQueueProduct (
    MessageQueueId				INT            IDENTITY (1, 1) NOT NULL,
    MessageTypeId				INT            NOT NULL,
    MessageStatusId				INT            NOT NULL,
    MessageHistoryId			INT            NULL,
    InsertDate					DATETIME2 (7)  CONSTRAINT DF_MessageQueueProduct_InsertDate DEFAULT (sysdatetime()) NOT NULL,
    ItemId						INT            NOT NULL,
    LocaleId					INT            NOT NULL,
    ItemTypeCode				NVARCHAR (3)   NOT NULL,
    ItemTypeDesc				NVARCHAR (255) NOT NULL,
    ScanCodeId					INT            NOT NULL,
    ScanCode					NVARCHAR (13)  NOT NULL,
    ScanCodeTypeId				INT            NOT NULL,
    ScanCodeTypeDesc			NVARCHAR (255) NOT NULL,
    ProductDescription			NVARCHAR (255) NOT NULL,
    PosDescription				NVARCHAR (255) NOT NULL,
    PackageUnit					NVARCHAR (255) NOT NULL,
	RetailSize					NVARCHAR (255) NULL,
	RetailUom					NVARCHAR (255) NULL,
    FoodStampEligible			NVARCHAR (255) NOT NULL,
	ProhibitDiscount			BIT			NOT NULL,
    DepartmentSale				NVARCHAR (255) NOT NULL,
    BrandId						INT            NOT NULL,
    BrandName					NVARCHAR (255) NOT NULL,
    BrandLevel					INT            NOT NULL,
    BrandParentId				INT            NULL,
    BrowsingClassId				INT            NULL,
    BrowsingClassName			NVARCHAR (255) NULL,
    BrowsingLevel				INT            NULL,
    BrowsingParentId			INT            NULL,
    MerchandiseClassId			INT            NOT NULL,
    MerchandiseClassName		NVARCHAR (255) NOT NULL,
    MerchandiseLevel			INT            NOT NULL,
    MerchandiseParentId			INT            NULL,
    TaxClassId					INT            NOT NULL,
    TaxClassName				NVARCHAR (255) NOT NULL,
    TaxLevel					INT            NOT NULL,
    TaxParentId					INT            NULL,
    FinancialClassId			NVARCHAR (32)  NOT NULL,
    FinancialClassName			NVARCHAR (255) NOT NULL,
    FinancialLevel				INT            NOT NULL,
    FinancialParentId			INT            NULL,
    InProcessBy					INT            NULL,
    ProcessedDate				DATETIME2 (7)  NULL,
	AnimalWelfareRating			NVARCHAR(50) NULL,
	Biodynamic					NVARCHAR(1) NULL,
	CheeseMilkType				NVARCHAR(50) NULL,
	CheeseRaw					NVARCHAR(1) NULL,
	EcoScaleRating				NVARCHAR(50) NULL,
	GlutenFreeAgency			NVARCHAR(255) NULL,
	HealthyEatingRating			NVARCHAR(50) NULL,
	KosherAgency				NVARCHAR(50) NULL, 
	Msc							NVARCHAR(1) NULL,
	NonGmoAgency				NVARCHAR(255) NULL,
	OrganicAgency				NVARCHAR(255) NULL,
	PremiumBodyCare				NVARCHAR(1) NULL,
	SeafoodFreshOrFrozen		NVARCHAR(50) NULL,
	SeafoodCatchType			NVARCHAR(50) NULL,
	VeganAgency					NVARCHAR(255) NULL,
	Vegetarian					NVARCHAR(1) NULL,
	WholeTrade					NVARCHAR(1) NULL,
	GrassFed					NVARCHAR(1) NULL,
	PastureRaised				NVARCHAR(1) NULL,
	FreeRange					NVARCHAR(1) NULL,
	DryAged						NVARCHAR(1) NULL,
	AirChilled					NVARCHAR(1) NULL,
	MadeInHouse					NVARCHAR(1) NULL,
	CustomerFriendlyDescription NVARCHAR (60) NULL,
	NutritionRequired			NVARCHAR(255) NULL,
	GlobalPricingProgram		NVARCHAR(255) NULL,
	SelfCheckoutItemTareGroup	NVARCHAR(60) NULL,
	FlexibleText				NVARCHAR(300) NULL,
	ShelfLife					INT NULL,
	FairTradeCertified			NVARCHAR(255) NULL,
	MadeWithOrganicGrapes		NVARCHAR(255) NULL,
	PrimeBeef					BIT NULL,
	RainforestAlliance			BIT NULL,
	Refrigerated				NVARCHAR(255) NULL,
	SmithsonianBirdFriendly		BIT NULL,
	WicEligible					BIT NULL,
    NationalClassId				INT NULL,
    NationalClassName			NVARCHAR (255) NULL,
    NationalLevel				INT NULL,
    NationalParentId			INT NULL,
	Hidden						BIT NULL,
    Line						NVARCHAR(255) NULL,
    SKU							NVARCHAR(255) NULL,
    PriceLine					NVARCHAR(255) NULL,
    VariantSize 				NVARCHAR(255) NULL,
    EStoreNutritionRequired		BIT NOT NULL DEFAULT(0),
    PrimeNowEligible			BIT NULL,
    EstoreEligible 				BIT NOT NULL DEFAULT(0),
    TSFEligible 				BIT NULL,
    WFMEligilble 				BIT NULL,
    Other3PEligible 			BIT NULL,
    HospitalityItem				BIT null,
	KitchenItem					BIT null,
	KitchenDescription			NVARCHAR(15) null,
	ImageURL					NVARCHAR(255) null
    CONSTRAINT PK_MessageQueueProduct PRIMARY KEY CLUSTERED (MessageQueueId ASC) WITH (FILLFACTOR = 80),
	[DataSource] NVARCHAR(255) NULL, 
    [NonGMOTransparency] NVARCHAR(255) NULL,
	[ItemDepth]  DECIMAL(10,4) NULL,  
    [ItemHeight]  DECIMAL(10,4) NULL,
    [ItemWidth]  DECIMAL(10,4) NULL,
	[Cube]  DECIMAL(10,4) NULL,
	[ItemWeight]  DECIMAL(10,4) NULL,
	[TrayDepth]  DECIMAL(10,4) NULL,
	[TrayHeight]  DECIMAL(10,4) NULL,
	[TrayWidth]  DECIMAL(10,4) NULL, 
	[Labeling]  NVARCHAR(255) NULL,
	[CountryOfOrigin]  NVARCHAR(255) NULL,
	[PackageGroup]  INT NULL,
	[PackageGroupType]  NVARCHAR(255) NULL,
	[PrivateLabel]  NVARCHAR(255) NULL,
	[Appellation]  NVARCHAR(255) NULL,
	[FairTradeClaim]  BIT NULL,
	[GlutenFreeClaim]  BIT NULL,
	[NonGMOClaim]  BIT NULL,
	[OrganicClaim]  BIT NULL,
	[Varietal]  NVARCHAR(255) NULL,
	[BeerStyle]  NVARCHAR(255) NULL,
	[LineExtension]  NVARCHAR(255) NULL
    CONSTRAINT FK_MessageQueueProduct_MessageHistoryId FOREIGN KEY (MessageHistoryId) REFERENCES app.MessageHistory (MessageHistoryId) ON DELETE CASCADE,
    CONSTRAINT FK_MessageQueueProduct_MessageStatusId FOREIGN KEY (MessageStatusId) REFERENCES app.MessageStatus (MessageStatusId),
    CONSTRAINT FK_MessageQueueProduct_MessageTypeId FOREIGN KEY (MessageTypeId) REFERENCES app.MessageType (MessageTypeId)
);