CREATE TABLE [app].[MessageQueuePrice] (
    [MessageQueueId]        INT            IDENTITY (1, 1) NOT NULL,
    [MessageTypeId]         INT            NOT NULL,
    [MessageStatusId]       INT            NOT NULL,
    [MessageHistoryId]      INT            NULL,
    [IRMAPushID]            INT            NOT NULL,
    [InsertDate]            DATETIME2 (7)  CONSTRAINT [DF_MessageQueuePrice_InsertDate] DEFAULT (sysdatetime()) NOT NULL,
    [RegionCode]            NVARCHAR (4)   NOT NULL,
    [BusinessUnit_ID]       INT            NOT NULL,
    [ItemId]                INT            NOT NULL,
    [ItemTypeCode]          NVARCHAR (3)   NOT NULL,
    [ItemTypeDesc]          NVARCHAR (255) NOT NULL,
    [LocaleId]              INT            NOT NULL,
    [LocaleName]            NVARCHAR (255) NOT NULL,
    [ScanCodeId]            INT            NOT NULL,
    [ScanCode]              NVARCHAR (13)  NOT NULL,
    [ScanCodeTypeId]        INT            NOT NULL,
    [ScanCodeTypeDesc]      NVARCHAR (255) NOT NULL,
    [ChangeType]            NVARCHAR (32)  NOT NULL,
    [UomCode]               NVARCHAR (3)   NOT NULL,
    [UomName]               NVARCHAR (100) NULL,
    [CurrencyCode]          NVARCHAR (3)   NOT NULL,
    [Price]                 MONEY          NULL,
    [Multiple]              INT            NULL,
    [SalePrice]             MONEY          NULL,
    [SaleMultiple]          INT            NULL,
    [SaleStartDate]         DATETIME2 (7)  NULL,
    [SaleEndDate]           DATETIME2 (7)  NULL,
    [PreviousSalePrice]     MONEY          NULL,
    [PreviousSaleMultiple]  INT            NULL,
    [PreviousSaleStartDate] DATETIME2 (7)  NULL,
    [PreviousSaleEndDate]   DATETIME2 (7)  NULL,
    [InProcessBy]           INT            NULL,
    [ProcessedDate]         DATETIME2 (7)  NULL,
    CONSTRAINT [PK_MessageQueuePrice] PRIMARY KEY CLUSTERED ([MessageQueueId] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_MessageQueuePrice_CurrencyCode] FOREIGN KEY ([CurrencyCode]) REFERENCES [dbo].[CurrencyType] ([currencyTypeCode]),
    CONSTRAINT [FK_MessageQueuePrice_IRMAPushID] FOREIGN KEY ([IRMAPushID]) REFERENCES [app].[IRMAPush] ([IRMAPushID]) ON DELETE CASCADE,
    CONSTRAINT [FK_MessageQueuePrice_MessageHistoryId] FOREIGN KEY ([MessageHistoryId]) REFERENCES [app].[MessageHistory] ([MessageHistoryId]) ON DELETE CASCADE,
    CONSTRAINT [FK_MessageQueuePrice_MessageStatusId] FOREIGN KEY ([MessageStatusId]) REFERENCES [app].[MessageStatus] ([MessageStatusId]),
    CONSTRAINT [FK_MessageQueuePrice_MessageTypeID] FOREIGN KEY ([MessageTypeId]) REFERENCES [app].[MessageType] ([MessageTypeId])
);
GO

create nonclustered index IX_MessageQueuePrice_MarkInProcess on app.MessageQueuePrice (MessageStatusId, BusinessUnit_ID, InProcessBy)
GO
