
CREATE TABLE[app].[PLUSequence](
	[sequence] [int] not NULL,
 CONSTRAINT [PLUSequence_PK] PRIMARY KEY CLUSTERED 
(
	[sequence] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO
