'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MovementDetail

    '''<summary>
    '''rdbtnTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbtnTop As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdbtnBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbtnBottom As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResults As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''reqfld_txtResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqfld_txtResults As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cmbZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbZone As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ICZones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ICZones As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''reqfld_cmbZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqfld_cmbZone As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lbStores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbStores As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''ICStores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ICStores As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cmbSubteam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSubteam As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ICSubteams control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ICSubteams As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''reqfld_cmbSubteam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqfld_cmbSubteam As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''dteBegin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteBegin As Global.Infragistics.WebUI.WebSchedule.WebDateChooser

    '''<summary>
    '''reqfld_dteBegin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqfld_dteBegin As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''dteEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteEnd As Global.Infragistics.WebUI.WebSchedule.WebDateChooser

    '''<summary>
    '''reqfld_dteEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqfld_dteEnd As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cmbReportFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbReportFormat As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rngValid_txtResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngValid_txtResults As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''cmp_BeginDateValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmp_BeginDateValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''cmp_EndDateValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmp_EndDateValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''cmp_txtBeginDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmp_txtBeginDate As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''cmp_txtEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmp_txtEndDate As Global.System.Web.UI.WebControls.CompareValidator
End Class
